### ISSUE TITLE
Feature request: Smooth scroll

### ISSUE THREAD

**Issue by C0derLint** [squidfunk/mkdocs-material#1011]
Add a smooth scrolling effect when clicking in-page links in the TOC.

**Comment by squidfunk** [comment]
I think quite ambivalently about smooth scrolling, as it introduces motion that surely conveys information that the page is moving in some direction, but may introduce nausea for people that get motion sick easily (e.g. people with epilepsy). For this reasons there may be concerns of reduced accessibility which is why it won't be added to Material by default.

However, if you like to add this to your documentation, you can do so easily by adding a library that supports this as custom JavaScript. Please see the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) for further assistance.

**Comment by C0derLint** [comment]
I see. Thanks for your help. I got it working using the below css rule:
```css
html {
  scroll-behavior: smooth;
}
```
But seriously, I think this should be feature, but disabled by default.

**Comment by squidfunk** [comment]
Glad you got it working. Note that your solution only works for Chrome and Firefox (see https://caniuse.com/#feat=css-scroll-behavior). If you want a cross-browser solution, some JavaScript is necessary. As there are tons of JavaScript libraries which implement this feature, picking a specific one may be good for some users but undesired for others. For this reason it won’t be included as a feature as I want to keep t as unopinionated as possible and adding a library is dead-simple.
