### ISSUE TITLE
Display error at a specific zoom ratio in Chromium

### ISSUE THREAD

**Issue by WAAutoMaton** [squidfunk/mkdocs-material#1027]
## Description

When the browser's zoom ratio is adjusted to a certain size, the display will have a serious error.
![image](https://user-images.githubusercontent.com/24771667/54116405-a9862700-4429-11e9-8d64-9afec4e5d979.png)

And this error will not reappear on Firefox.

### Steps to reproduce the bug

1. Open any Material website. Such as the official Material website.
2. Adjust browser zoom ratio.
3. Page displays error.

### System information

* OS: KDE neon 18.04.
* Browser: Chromium 72.0.3626.121

**Comment by squidfunk** [comment]
Thanks for reporting. Does this happen for a specific window width or for all window widths above 1220px? I’m not able to reproduce this with Chrone on Mac

**Comment by WAAutoMaton** [comment]
In my computer, it only happens when browser window is maximizes.
My screen is 1920*1080px.

**Comment by squidfunk** [comment]
Well, it seems that this is a subpixel rounding error because of the automatic scaling of the site on bigger screens, which is probably not fixable. I cannot reproduce in Chrome, so it may only appear in Chromium. As it only happens when the page is zoomed out on a large screen, I would triage it as a minor bug that may not impact a lot of users.

**Comment by squidfunk** [comment]
Closing for housekeeping. Unfortunately not fixable.
