### ISSUE TITLE
How to add brython

### ISSUE THREAD

**Issue by CesMak** [squidfunk/mkdocs-material#1048]
Hey there,

I would like to add [brython](https://github.com/brython-dev/brython) to my material site. 

I first added the brython.js to **mkdocs.yml:**

```
extra_javascript:
  - 'javascripts/brython.js' 
```

and then on a **test.md** page I tried:

```
## My Brython Test:
        <body onload="brython()">

            <script type="text/python">
            from browser import document, alert

            def echo(event):
                alert(document["zone"].value)

            document["mybutton"].bind("click", echo)
            </script>

            <input id="zone"><button id="mybutton">click !</button>

        </body>

```

Unfortunately this did not work.... I think the body tag might be missunderstood or the script is not imported correctly..... any ideas how to use brython with mkdocs material?

Thanks.

**Comment by facelessuser** [comment]
First off, since you've indented your HTML, I imagine it was treated as a code block. Also, I think you should have a blank line before the body tag. On top of that, the way you have it, I'm pretty sure it would generate the body tag under the document body tag (nested body tags), is that your intention?

I have no idea what your project looks like, or the requirements of brython, so I cannot comment further.

If the brython script is where your config says it is, and mkdocs finds it, I imagine that is as much as anyone could help you. Any help beyond that I would expect to be out of scope for Material support issues.

**Comment by CesMak** [comment]
I just solved it. I used brython to code a 

**tic tac toe game**

[Code here on simact.de](http://simact.de/games/tic_tac_toe/index.html)
