### ISSUE TITLE
Add support for sticky tabs

### ISSUE THREAD

**Issue by lgeiger** [squidfunk/mkdocs-material#1154]
## Description

If would be great to have the option of a sticky tab navigation that stays on top during scrolling. Currently during scrolling the tab bar disappears and only the title of the current section stays on top. Reducing the height of the navigation bar is great for readability on devices with smaller screens. Unfortunately this approach hides the top-level navigation, which can be important for sites that have many top-level pages. Instead, showing the title of the current section is redundant since it is highlighted on the left sidebar anyway.

### Current Behaviour: Expanded Header
<img width="1440" alt="top" src="https://user-images.githubusercontent.com/13285808/60459814-6d7a0a80-9c42-11e9-8275-388fb264eae4.png">

### Current Behaviour: Collapsed Header with Section Title
<img width="1439" alt="scroll" src="https://user-images.githubusercontent.com/13285808/60459852-7bc82680-9c42-11e9-97c7-1f47e20227f8.png">

### Proposed Behaviour: Collapsed Header with Tabs
<img width="1439" alt="scroll proposed" src="https://user-images.githubusercontent.com/13285808/60459897-9a2e2200-9c42-11e9-8087-4ae8009adbc4.png">

**Comment by squidfunk** [comment]
To cut it short: not possible. I'm sorry. Why? Because:

1. I don't really see how the approach you suggested could be implemented without having duplicate HTML and increasing maintenance by a significant margin
2. Providing options for everything is beyond the scope of this project. There've been some requests for sticky tabs in the past, albeit all slightly different: some people would like tabs to disappear when scrolling down and reappear when scrolling up, some people would like the tabs to be visible at all times, you would like the tabs to merge with the header, hiding the title, which some other people might not like, yada yada yada. I think you see where this is going.

I'm trying very hard to build something that solves a lot of use cases with simple configuration, but it's obviously not possible to solve every use case. However, you could implement it yourself. You could modify `base.html` and move the include of `tabs.html` partial into `header.html`. Then, add some JavaScript to get the behavior you want and you should be good to go.

**Comment by squidfunk** [comment]
Nevertheless: big up for the mockup! I immediately understood what you want to achieve, saving us both a lot of time.

**Comment by lgeiger** [comment]
Thanks for the fast response. I understand the reasoning that adding more and more options doesn't scale and hurts maintainability.

For me the problem with the current behaviour, is that the collapsed header hides important information about how to navigate the page. Instead the current section title (that is also visible in the sidebar) is duplicated in the UI. While this behaviour looks really cool, it can become problematic on websites with many top level pages.

How do you feel about only supporting a minimal collapsed tab view without any animations? Basically the proposed option from above but without the possibility to expand? As far as I can tell, this would only require two conditionals [here](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/header.html#L51-L67) and [here](https://github.com/squidfunk/mkdocs-material/blob/master/src/base.html#L253-L255). It would probably satisfy most of the users who are looking for a minimal sticky tab bar that doesn't take up a lot of screen realestate.

**Comment by squidfunk** [comment]
> For me the problem with the current behaviour, is that the collapsed header hides important information about how to navigate the page. 

An easy solution to your problem is to disable tabs entirely, so the whole navigation is visible as part of the sidebar. Furthermore, tabs are only visible for the `screen` break point, because the menu is collapsed into the drawer for all breakpoints below.

> Instead the current section title (that is also visible in the sidebar) is duplicated in the UI.

You mean that the active menu item equals the header when scrolling below the `h1`? The header can be changed through `page.meta.title`, so it doesn't necessarily equal the menu item, see:

https://github.com/squidfunk/mkdocs-material/blob/49b2dad3eb35b85460a118d0ea1edbf8216be5d5/src/partials/header.html#L59-L65

> As far as I can tell, this would only require two conditionals here and here.

The sidebar scroll-locking _should_ work when you include the tabs in the `header.html` partial instead of `base.html`, so in theory yes, it should work. However, I want to repeat my second argument from my last comment:

> Providing options for everything is beyond the scope of this project. There've been some requests for sticky tabs in the past, albeit all slightly different: some people would like tabs to disappear when scrolling down and reappear when scrolling up, some people would like the tabs to be visible at all times, you would like the tabs to merge with the header, hiding the title, which some other people might not like, yada yada yada. I think you see where this is going.

This is the main reason why I would kindly ask you to implement it yourself exactly the way you like it. I really want to keep it simple.

**Comment by squidfunk** [comment]
Closing for housekeeping.

**Comment by lgeiger** [comment]
Thanks for your help. I was able to modify it to our requirements.

**Comment by WaldemarEnns** [comment]
> Thanks for your help. I was able to modify it to our requirements.

@lgeiger could you provide/share some code? I would like to use the same behavior you mentioned in my application! :)

**Comment by lgeiger** [comment]
> could you provide/share some code? 

@WaldemarEnns You can checkout the website at https://docs.larq.dev/ with code available at https://github.com/larq/docs
