### ISSUE TITLE
Question: Are all the search capabilities of lunr.js supported?

### ISSUE THREAD

**Issue by oneandersson** [squidfunk/mkdocs-material#1221]
Hi

I've hopefully a short question and that is wether or not all the capabilities of the lunr.js search is expected to work? In https://lunrjs.com/guides/searching.html, wildcards, fields, boosts, fuzzy matches and term presence search capabilities are mentionned, but when trying it out on our documentation set nothing but basic one word search appear to work.

Otherwise thx for the nice work.

**Comment by squidfunk** [comment]
Searching with operators (i.e. `foo* or +foo`) is currently not supported. Searching for multiple words however is:

<img width="697" alt="Bildschirmfoto 2019-08-23 um 09 17 19" src="https://user-images.githubusercontent.com/932156/63573946-edf42200-c586-11e9-954c-e0408e4f4def.png">

My Google Analytics tells me that on the official documentation no one ever uses operators, people are more used to entering a single word or multiple words.

**Comment by oneandersson** [comment]
Thx for the quick answer. In our case, it will be required, so we'll probably look into supporting that.

**Comment by squidfunk** [comment]
This is the place where searching is taking place:

https://github.com/squidfunk/mkdocs-material/blob/0a93a26364016518ba36f62b18e6f65a5e164942/src/assets/javascripts/components/Material/Search/Result.jsx#L283-L290

We're actually using `idx.query` instead of `idx.search`. The Lunr integration was built two years ago, so the API might have changed. I'm happy to merge new functionality, as long as doesn't break the "old" way of searching. We might put it behind a flag, so it can be enabled explicitly if desired.

**Comment by squidfunk** [comment]
Closing as answered.
