### ISSUE TITLE
Lunr Languages JavaScript files missing .min.js extension

### ISSUE THREAD

**Issue by hughmcmaster** [squidfunk/mkdocs-material#1247]
## Description
The Lunr Languages JavaScript files are minified in `mkdocs-material`, but the file extension does not indicate this.

This causes problems when packaging for Debian, as the package checker expects the `.min.js` file extension to appear on minified source files.

### Expected behaviour
The file extension on all Lunr Languages JavaScript files should be `<filename>.min.js`. (The files are also missing their copyright attribution, which is present upstream.)

### Package versions
Material: 4.4.2

**Comment by squidfunk** [comment]
No bandwidth right now. If somebody wants to tackle it - it's a great first PR. Changes need to be made in `webpack.config.js`.

**Comment by squidfunk** [comment]
Thanks for your PR. However, I realized that this seemingly minor change may have the potential to break customized installations, because some people extend the theme by overriding partials or template blocks. If somebody has overridden `main.html` or the `scripts` block and uses a language different from English which will lead to one of the files in question being loaded, he will now see a 404 with the search not working anymore. The line which you forgot to adapt in your PR is here:

https://github.com/squidfunk/mkdocs-material/blob/4b7810a367a851205ef6b8c7ac18d587a041aa1a/src/base.html#L364

You obviously also haven't tested your changes or you would have seen that search won't work anymore for anything different from English.

My highest priority is maintaining downward compatibility while fixing bugs and keeping the theme up-to-date. This, sometimes, means that minor changes are not that trivial to implement, see for example #756. As this issue is about something that has zero upside for the user, I'm closing it as it won't be considered. I'm sorry, but I hope you understand the reason behind this decision.

**Comment by hughmcmaster** [comment]
I'm not sure I understand. If I specify German ('de') in `mkdocs_theme.yml`, the navigation, search etc. appear in German.

If someone overrides one of the template blocks, they obviously know what they're doing. Updating a file extension is hardly going to be problem. And besides, any patches would be applied from the source, so they would catch any problems during development and testing.

Having said that, I can't say I'm not disappointed.

I'll leave an updated branch open in case there's a need to revisit this later (or you change your mind).

**Comment by squidfunk** [comment]
> I'm not sure I understand. If I specify German ('de') in mkdocs_theme.yml, the navigation, search context etc. appear in German. And I can search in German as well.

I don't know how you tested it, but without updating the HTML which includes the files which extensions you changed it cannot possibly work. Maybe the search still works, but the stemmers should have failed to be loaded with a 404.

> If someone overrides one of the template blocks, they obviously know what they're doing. Updating a file extension is hardly going to be problem.

That's a bold statement. There are many people fiddling around with the templates. Have you seen how many issues are opened for this project regarding seemingly trivial stuff from users that don't really know what they're doing? This means more work for me answering those issues and even less time for important stuff like working on bugs or feature requests.

> And besides, any patches would be applied from the source, so they would catch any problems during development and testing.

That implies that people fork the theme and work on the original files. This is not how overriding works. See the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) for more information.

> Having said that, I can't say I'm not disappointed.

I understand that this might be important for you, but I see no point issuing a major release for something that has literally zero upside for the UX or DX. We might include such a change in the next major release, but there will be no major release exclusively for this. I understand that you have problems which are related to Debian packaging, but Debian is not the way to use or install this theme. For this reason it's no priority. I'm sorry.

**Comment by hughmcmaster** [comment]
> I don't know how you tested it, but without updating the HTML which includes the files which extensions you changed it cannot possibly work. Maybe the search still works, but the stemmers should have failed to be loaded with a 404.

I've just checked again. And yes, the stemmers did fail to load. I pushed the wrong branch.

> Have you seen how many issues are opened for this project regarding seemingly trivial stuff from users that don't really know what they're doing? I can't say I've followed things that closely. But you are incredibly responsive and patient.

> I understand that this might be important for you, but I see no point issuing a major release for something that has literally zero upside for the UX or DX.

I didn't ask you to make this a priority or a major release, nor did I expect you to. I'd like to see it happen at some point, but if you really don't want to, I'll accept that.

**Comment by squidfunk** [comment]
Will be fixed with #1306

**Comment by hughmcmaster** [comment]
Thank you!
