### ISSUE TITLE
Allow settings in mkdocs.yml to alter search behaviour

### ISSUE THREAD

**Issue by martinbira** [squidfunk/mkdocs-material#1362]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Extend the search capabilities using the built in clauses in lunr to include strict or fuzzy matches.

**Disclaimer** I'm not that good at JavaScript, so definitions and methods may not be 100% correct, but it's my interpretation of the source code.

### Use Cases

Depending on the knowledge level of a user of what to search for, a strict term presence may increase matching for experienced users when using multiple terms, or a fuzzy match when the target user group may be less knowledgeable. Taking stemming into account, a strict term presence can assist in separating hyphened words.

###  Mockups

The search capabilities should be defined in the  `mkdocs.yml` file.
```
search:
    method: (undefined)/default/strict/fuzzy
```
**(undefined)/default:** The default/current search behavior is used, ` wildcard: lunr.Query.wildcard.TRAILING`
**strict:** The search query should use the option `presence: lunr.Query.presence.REQUIRED`
**fuzzy:** The search query should use the option `editDistance: 1` 

If no method is set, the search method should use `default`. 

---

The rendered HTML should include the search method in the same manner as the tokenizer and languages are defined. This could be omitted if undefined or set to `default`.

``` 
<meta name="lang:search.method" content="default">
<meta name="lang:search.method" content="strict">
<meta name="lang:search.method" content="fuzzy">
```

---

The search method is retrieved in the `Results.jsx` file, perhaps in the constructor where the tokenizer and languages are defined, line 153.

```
/* Load search method */
const method = translate("search.method")
if (method === "strict")
	/* relevant code to set the options for strict. */
elseif (method === "fuzzy")
	/* relevant code to set the options for fuzzy. */
else
      /* relevant code to set the default search options  */
```

The search query, I guess it's line 288, should be altered from using a static option to a dynamic option based on the set search method.

```
...
query.term(term, { wildcard: lunr.Query.wildcard.TRAILING })
...
```

### Backwards compatibility

If no method is set, the search method should be `default`, thus not requiring users of Material for MkDocs to alter their `mkdocs.yml`-file

### Performance implications

Unsure if there will be any major implications of performance 

### References

https://lunrjs.com/guides/searching.html
https://lunrjs.com/docs/lunr.Query.html
https://lunrjs.com/docs/query.js.html#line76

**Comment by squidfunk** [comment]
Thanks for your research and the directions! Looks pretty good, actually. Some thoughts/questions:

1. Shouldn't this be implemented in the MkDocs search plugin? More themes could participate from this I think. Furthermore it would be configurable as an option of the search plugin. Material v5 will try to move as many options as possible into the search plugin config.

2. Are the options (default, strict, fuzzy) mutually exclusive? As far as I understood: `presence` switches from `OR` to `AND`, which might also work with wildcard or fuzzy search, wouldn't it?

**Comment by martinbira** [comment]
You know what, I fully agree that this would probably be much better utilised if directly added to the MkDocs search plugin. As for the options, I do not think that they are mutually exclusive but the question is how complicated a search configuration should be, both for a user and for implementation.

The only change I thought from `default` to `strict` is the `presence` switch from `OR`to `AND`, and if there was a practical need to combine a `fuzzy` and `strict` search.

I think I'll have a look at this again and post as a suggestion to MkDocs.

**Comment by martinbira** [comment]
Created https://github.com/mkdocs/mkdocs/issues/1914 for MkDocs. Closing the issue.

**Comment by squidfunk** [comment]
Great! We can then add support for this the moment the search plugin is updated.

**Comment by martinbira** [comment]
Well it looks like the ability to alter the default search will not be added to the search plugin:

> Given the above, I'm inclined to suggest that any such settings could be added to a theme, rather than the plugin itself. Yes, the theme devs would need to write their own JavaScript to make use of those settings

**Comment by squidfunk** [comment]
I don't quite share waylan's view here. I think that users should get the optimal experience right out of the box, whereas _optimal_ is something the content author should decide. I would assume that only a small fraction of the people using Google search know they can exclude a term with a `-` prefix. 

For this reason I think this is a good addition and will reopen this issue for further consideration. I just wanted to run it by waylan in order to check whether it could be considered for upstream integration, so all themes could benefit from it. If I remember correctly, tokenization was also added as a configuration option long after Material supported it.

The downside of this is that search configuration is split across `plugins` and `theme` or `extra`. I'll try and come up with a good configuration proposal for v5.

**Comment by bhathiya** [comment]
I went through this issue as well as the one in mkdocs. I have a similar requirement where I want to give priority to doc titles rather than the number of occurrences of the search term on a page. 

After reading the issue in mkdocs, what I realized was that I should be able to get it done at the theme level. Is there any extension points I can use for that?  

You can find my original requirement in [1].

[1] https://github.com/mkdocs/mkdocs/issues/1916

**Comment by squidfunk** [comment]
It's currently not configurable. You would have to fork the theme and patch it yourself. See here:

https://github.com/squidfunk/mkdocs-material/blob/54bd366a71dad91eb59792b6d4aad5b69f51c56b/src/assets/javascripts/components/Material/Search/Result.jsx#L206-L238

... and here:

https://github.com/squidfunk/mkdocs-material/blob/54bd366a71dad91eb59792b6d4aad5b69f51c56b/src/assets/javascripts/components/Material/Search/Result.jsx#L284-L290

I will try to improve configurability with the next major release.

**Comment by bhathiya** [comment]
Thank you. I'll give it a try.

**Comment by bhathiya** [comment]
I can see you have already set `boost: 10` for the `title`. Shouldn't that already cater to my requirement? Or do you think I should find my own value there?

**Comment by squidfunk** [comment]
The easiest way is to try it out and tune the parameters 😀I can't say what's best for your use case.

**Comment by bhathiya** [comment]
Ah no, I wasn't talking about the number, but the param `boost`. Anyway, yeah I'll try and see how it behaves. Thanks. :)

**Comment by waylan** [comment]
While looking into /mkdocs/mkdocs#1916 I was reminded that lunr.js provides two mechanisms for doing a search:

1. A [query][1] method which accepts a custom built [Query][2] instance.
2. A [search][3] method which accepts a [querystring][4]. Internally, that `querystring` is parsed by lunr.js and converted into a `Query` instance.

The default implementation provided with the `search` plugin uses option 2 (the `search` method) while it appears that Material uses option 1 (the `query` method). Therefore, the default implementation gets full support for all the [querystring functions][5] for free (with no configuration needed) while Material needs to implement them separately. Basically, you guys have made more work for yourselves. But, in return you get more control over how search works. It's a trade-off and I'm glad to see different options available for users. 

[1]: https://lunrjs.com/docs/lunr.Index.html#query
[2]: https://lunrjs.com/docs/lunr.Query.html
[3]: https://lunrjs.com/docs/lunr.Index.html#search
[4]: https://lunrjs.com/docs/lunr.Index.html#~QueryString
[5]: https://lunrjs.com/guides/searching.html

**Comment by squidfunk** [comment]
@waylan I will consider it for the refactoring. It's mainly used to set explicit trailing wildcards, but this might also be solvable with simple string processing. Honestly, I don't know why I changed it in 357c6f41221231927f5eb2662ba88988db18087e, but I think it had to do with non-whitespace or non-latin languages. Remember that Material supports 40 languages, including Chinese, Japanese and Arabic. It's quite tricky to get it working for all languages out of the box.

**Comment by waylan** [comment]
> I can see you have already set `boost: 10` for the `title`. Shouldn't that already cater to my requirement? Or do you think I should find my own value there?

@bhathiya I assume you are referring to this:

https://github.com/squidfunk/mkdocs-material/blob/54bd366a71dad91eb59792b6d4aad5b69f51c56b/src/assets/javascripts/components/Material/Search/Result.jsx#L231-L234

IIRC, in version 2.0 lunr.js removed support for setting boost on the filed definitions. You won't get any error, but it is ignored. Instead, you need to define it on the query (using the `boost` option with [Queary.term][1], which was the reason I assumed @squidfunk has the theme defining its own custom query. However, looking at the custom query, I don't see any boost being defining there. Although, weirdly, according to the documentation, boost can only be defined in relation to a "term", not a field (the term can also be restricted to a field, but the boost is on the term not the field). IIRC, the developer of lunr.js commented at some point that he regretted removing the ability to define boost for a field (given the large number of complaints from users) and suggested it may be added back in a future release (3.0?). However, I don't believe that has happened and I am unsure if it ever will.

[1]: https://lunrjs.com/docs/lunr.Query.html

**Comment by waylan** [comment]
I went to search for the comments by the lunr.js developer and found olivernn/lunr.js#312. According to that, field boost support was restored in version 2.3.0. MkDocs currently uses 2.3.2, so we should be good there.

**Comment by waylan** [comment]
FYI, we will be adding field boost back to the default plugin, which would only affect Material if you started making use of the option prebuilt index.  However, we might also add support for document boost. See mkdocs/mkdocs#1918 for details and/or to provide feedback. Of note to Material is that document boost would be included in the JSON data used to build the search index. While Material could ignore that data, I'm curious if you would find it useful.

**Comment by bhathiya** [comment]
I think that will be a good feature for authors to control search results. Voted in mkdocs/mkdocs#1918

**Comment by squidfunk** [comment]
Prebuilt index will very likely not be supported, so this will have no effect. It brings little upside, unfortunately. Analyzed it in another issue/PR but I’m on mobile right now, so cannot link.

**Comment by squidfunk** [comment]
... regarding document boosts - that should be easy to add.

**Comment by bhathiya** [comment]
> @waylan I will consider it for the refactoring. It's mainly used to set explicit trailing wildcards, but this might also be solvable with simple string processing. Honestly, I don't know why I changed it in [357c6f4](https://github.com/squidfunk/mkdocs-material/commit/357c6f41221231927f5eb2662ba88988db18087e), but I think it had to do with non-whitespace or non-latin languages. Remember that Material supports 40 languages, including Chinese, Japanese and Arabic. It's quite tricky to get it working for all languages out of the box.

I managed to revert [this change](https://github.com/squidfunk/mkdocs-material/commit/357c6f41221231927f5eb2662ba88988db18087e#diff-8d5b767cb91a4401d3a9735774b182b3R196-R207) and now I can see my original search query (i.e. `Create API Product`) works fine. However, strangely some search queries give nothing now without appending `*` at the end. That might be the reason why you had to do the same. But I don't understand why we need that. Any guesses?

**Comment by squidfunk** [comment]
@bhathiya without the wildcard, Lunr will match for entire tokens. If a Stemmer is in place, the word “colorize” will be stemmed to “color”, which will only match if you entered all five letters.

Material uses wildcard matching to provide a good typeahead experience. Furthermore the results with wildcards when entering more and more characters are more stable than token based matching which may differ quite fundamentally.

**Comment by squidfunk** [comment]
I thought about this some more and I think getting this right is quite tricky. I think I also remembered why it is currently done the way it is. Here is an attempt of explanation:

### Requirements

I've got some experience on search UX (actually, search was the central USP of my previous startup), so I want the search to be (1) _easy to use_ and to provide (2) _predictable results_. IMHO, a good typeahead experience is crucial for a good UX, as this is exactly what people are familiar with coming from Google and other search UIs. Google is the de-facto standard of search in the web, so every search UI/UX should try to live up to those standards.

### Lunr's default behavior

Lunr.js default behavior when indexing strings is:

1. Tokenize the string
2. Stem each token to its root, if given
3. Associate the document with each token

Given a query, Lunr.js will do the following:

1. Tokenizer the query string
2. Steam each token to its root, if given
3. Query the union of documents matching each token __exactly__ + sort according to a scoring function

### Lunr's behavior within Material

As tokens are matched __exactly__, there's no typeahead in place. What Material does is:

1. Split the query string at whitespace (which is suboptimal, it should be split with the same tokenization algorithm) into terms.
2. Implicitly append an `*` to each term by providing the respective `wildcard.TRAILING` flag.

@waylan's idea is to leave the query string as-is, in order to provide the user with the maximum flexibility in regards to search. While this may be suitable for technical users, which is probably a reasonable assumption, given that this is a theme for project documentation, it doesn't provide a typeahead out-of-the-box. In my eyes, this is suboptimal, as you, as it's impractical to suffix each term with `*` _while_ typing. Also, some users may not know about this search syntax, so they will get suboptimal results. I'm a big fan for things to work great out-of-the-box and am willing to take some hits on more complex and specific use cases where people may want to provide more flexibility.

### Where to go from here

So, actually it could be possible to combine both approaches, i.e. to provide typeahead while retaining the possibility to exclude or include specific terms or perform fuzzy search or span queries (if Lunr.js supports them). For this to work, we would have to check whether a term contains a qualifier like for example `+`, `-` or `~`. If it doesn't, we add the `*` to the end of the term, providing typeahead. If it does, we leave the term as is.

I don't know whether combining qualifiers with trailing wildcards is possible and whether it provides good results, so I would regards this as mutually exclusive. Is that something that would work for you guys?

### Prebuilding the index

See my comments [here](https://github.com/squidfunk/mkdocs-material/pull/1302#issuecomment-541335189) and [here](https://github.com/squidfunk/mkdocs-material/pull/1302#issuecomment-541428403) why IMHO prebuilding is not an option.

**Comment by bhathiya** [comment]
Thank you for the detailed explanation. Your hybrid solution seems to cater to many cases. I will give it a try too. 

However, the way you explain how the search query work is not the same as what I experience (as I explained above). See the 2 cases below. 

![image](https://user-images.githubusercontent.com/3960742/70427160-3bdf5800-1a9a-11ea-8171-24c909432e3f.png)

![image](https://user-images.githubusercontent.com/3960742/70427185-47cb1a00-1a9a-11ea-951d-454de3cd49b4.png)

This might be due to some issues in the indexes I guess. Is there a way I can check that? Is it `site/search/search_index.json` that I should check?

**Comment by squidfunk** [comment]
Could be related to stemming issues. Do you see something if you enter “Analytic”?

**Comment by bhathiya** [comment]
Nope, nothing unfortunately.

**Comment by squidfunk** [comment]
Hard to debug remotely. This is why I mentioned that search is tricky to get right 😊

**Comment by bhathiya** [comment]
Yeah I know. :) Could you please answer my question about index files if possible?

**Comment by squidfunk** [comment]
`site/search/search_index.json` is generated by MkDocs and then fetched and indexed by Material. See https://github.com/squidfunk/mkdocs-material/issues/1362#issuecomment-562074002

**Comment by squidfunk** [comment]
I've prototyped the new search locally (not yet committed, needs cleanup) and I think I came up with a reasonably customizable approach. I think waylan is right - we should just use the `search` function, giving users the possibility to use all features that [lunr supports](https://lunrjs.com/guides/searching.html).

However, I also want to keep the current trailing wildcard behavior as it has proven to be a very good default for most of the cases. To see it in action, compare Material's search with the one on [mkdocs.org](https://mkdocs.org) which doesn't add implicit trailing wildcards.

For this reason, I think the best approach is to take the input string from the search query field and apply the following transformation:

``` js
query.trim().replace(/\s+|$/g, "* ")
```

This will lead to the following transforms:

```
foo bar       => foo* bar*
foo -bar      => foo* -bar*
foo +bar      => foo* +bar*
```

Of course this needs some further validation, for example whether and how we can handle fuzzy queries with that. To change the default behavior, we could add a function to the configuration which the Material application receives in `base.html`, so the author can override the default query transform behavior.

@martinbira any thoughts?

**Comment by martinbira** [comment]
@squidfunk That sounds like an excellent solution! Great job!

**Comment by bhathiya** [comment]
Just for the record, in case it will be useful to someone else too, this is how I customized the theme to give priority to titles. 

```
diff --git a/src/assets/javascripts/components/Material/Search/Result.jsx b/src/assets/javascripts/components/Material/Search/Result.jsx
index 4c876de..0b4b250 100644
--- a/src/assets/javascripts/components/Material/Search/Result.jsx
+++ b/src/assets/javascripts/components/Material/Search/Result.jsx
@@ -229,7 +229,7 @@ export default class Result {
           }

           /* Index fields */
-          this.field("title", { boost: 10 })
+          this.field("title", { boost: 100 })
           this.field("text")
           this.ref("location")

@@ -286,7 +286,12 @@ export default class Result {
             .filter(Boolean)
             .forEach(term => {
               query.term(term, { wildcard: lunr.Query.wildcard.TRAILING })
-            })
+              query.term(term, {
+                fields: ["title"],
+                boost: 200,
+                usePipeline: false
+              })
+           })
         })
```

Had to use `usePipeline: false` to avoid strange stemming.

**Comment by squidfunk** [comment]
This issue is superseded by #1518, which defines the next steps to be taken.
