### ISSUE TITLE
manifest.json handling

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#1374]
Hey there, I don't quite understand providing a functioning manifest.json and serviceworker should work with mkdocs-material. It is recommended to put both sw.js and manifest.json in the root of the site, that's not possible when using a custom build of material theme because the material theme overwrites it with it's own manifest.json which is a list of files.

Using the paths from your examples here https://github.com/squidfunk/mkdocs-material/issues/810#issuecomment-438442460

My suggestion would be altering the webpack config to add the `fileName: "file_manifest.json"` argument to it so the file names no longer clash

**Comment by squidfunk** [comment]
First: this is a question for clarification and it should be asked on the Gitter channel or StackOverflow.

The `manifest.json` is generated as part of the Webpack build process to map the original filenames to the ones with chunk hashes for cache busting, e.g. `application.js` -> `application-XXXXXXXX.js`. It is not part of the released theme, but it may be copied if you built the theme locally.

I understand that the current build process may not be ideal, so in order to fix this you might just use another name for your manifest file, e.g. `manifest.webmanifest`. The build process will be overhauled as part of v5.

If you have any more questions, I would kindly ask you to move the discussion to Gitter.

**Comment by Stanzilla** [comment]
I'll just make a PR for the current version, I guess.

**Comment by squidfunk** [comment]
Fixed in 633bcac.
