### ISSUE TITLE
[Feature Request] Extra Font

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#1379]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

A new options parameter to pass a font name to load an additional font from Google fonts
### Use Cases

I want to use more than one extra font and love to avoid changing the template for that

**Comment by squidfunk** [comment]
I wouldn’t regard this being a common use case, so it’s nothing I would want to maintain. It’ll probably make configuration more complex. For this reason I would recommend that you just overwrite the respective block. It’s not much code and you can customize it exactly the way you need it 😊

**Comment by Stanzilla** [comment]
I do that, yeah. Just thought other people might have the same use case etc. Want to close the issue then?

**Comment by squidfunk** [comment]
Yeah. We really have to strike a balance between configurability and extensibility. IMO, your request belongs in the latter, because specifying a third font breaks out of the current mechanics of configuration and the use cases may be very different. If it comes up more often and we can deduce some repeating patterns, we may think about it, but you're currently the only one. Nevertheless, there's an issue now and it's searchable, so if somebody comes across something similar, we'll know.

Closing (for now).
