### ISSUE TITLE
Accessibility Part 2

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#1392]
So after yesterday I took a look at a few more things and found that the current recommendation for `Skip to main content` links is to not set `tabindex` to `1` but to `0` (https://web.dev/control-focus-with-tabindex/) While that is not the ideal solution, it's the one that does not require extra JavasScript. To be 100% correct it would be https://github.com/selfthinker/dokuwiki_template_writr/blob/master/js/skip-link-focus-fix.js

**Comment by squidfunk** [comment]
I guess we could set the `tabindex` on the skip link to 0, as it is the first focusable element in tree order anyway, so it shouldn't matter. Would you like to create a PR?

On a side note: I'm sorry to remind you, but I would kindly ask you to stick to the issue template when creating issues, like everyone else. Otherwise, let's discuss on Gitter.

**Comment by Stanzilla** [comment]
Yes and sorry, will do!

**Comment by squidfunk** [comment]
Closing, let's further discuss in Gitter or via a PR.
