### ISSUE TITLE
Custom Mobile Width

### ISSUE THREAD

**Issue by adreasnow** [squidfunk/mkdocs-material#1404]
#### Feature:
I was wondering if it would be possible to implement a feature to modify the width at which the tabs/primary nav bar are hidden (rather than at 1220px). I've tried modifying the javascript in the theme, but I can't seem to make it change this behaviour.

#### Reason
The width chosen is really quite wide, and removes some really useful navigation functionality (hiding a menu behind a button should be  a last resort for saving real estate).

This is compounded further when implementing the solution from [619](https://github.com/squidfunk/mkdocs-material/issues/619#issuecomment-348610715)

#### Mockup
This could be something like:
```yaml
theme: 
  mobile-width: '900'
```

Thanks,
Adrea

**Comment by Stanzilla** [comment]
We talked about that on Gitter briefly today, a general width setting would be very nice for me as well.

**Comment by squidfunk** [comment]
Making the width configurable via parameter would imply that we have to find some way to pass this parameter to the template:

Passing it as a Jinja template variable is not possible, as we cannot pass Jinja variables to CSS files. We would have to inline a lot of the CSS in `base.html` in order to set it, i.e. every Media Query that references this value (as you want to move the breakpoint further down) and all rules that work with this or a deduced value of it.

This may be partially solved with CSS variables, but all Media Queries would still have to be inlined, because CSS variables cannot be used in preludes of Media Queries, so it’s not feasible either.

However, the CSS is actually generated from SCSS which defines the breakpoints as variables! You can change those values in the original source and recompile the theme to achieve what you want.

https://github.com/squidfunk/mkdocs-material/blob/0c2c0da5b4beede97b4b135458a48a31de62cdd4/src/assets/stylesheets/_config.scss#L38-L52

**Comment by adreasnow** [comment]
Thank you @squidfunk, I'll give this a go and see how it works for me :)
