### ISSUE TITLE
Vertical alignment glitch with code blocks and linenums

### ISSUE THREAD

**Issue by michaudg** [squidfunk/mkdocs-material#1454]
There is a vertical alignment glitch using code blocks and `linenums` with 4.6.2. There is no problem without using `linenums`.

![image](https://user-images.githubusercontent.com/674170/74185949-aede8980-4c17-11ea-8113-7968fe027cb1.png)

Markdown:
```
\``` linenums="1"
parted -s /dev/[vdb|vdc] mklabel gpt
parted -s /dev/[vdb|vdc] mkpart primary 0% 100%
mkfs.ext4 /dev/[vdb|vdc]1
\```
```

Thank you.

**Comment by facelessuser** [comment]
What does your extension setup look like? I cannot reproduce this.

**Comment by squidfunk** [comment]
Please post your `mkdocs.yml` and a reproducible test case. The issue template gives guidance on what we need to help you, so its always beneficial to stick to it. 

Furthermore we just discussed a similar problem on the Gitter channel. What helped was to reinstall all dependencies, as it may be an incompatibility between Markdown, MkDocs and Material caused by stale versions. You can try that with:

```
pip install --upgrade --force-reinstall
```

**Comment by michaudg** [comment]
> The issue template gives guidance on what we need to help you, so its always beneficial to stick to it.
I don't know how I manage to do it but I didn't see any template when I created the issue. Sorry.

`pip install --upgrade --force-reinstall mkdocs-material` worked. All dependencies were reinstalled and the problem is solved.

Thank you.
