### ISSUE TITLE
Allow configuration of default search query pre-processing function

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1518]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Just a reminder that you mentioned [here](https://github.com/squidfunk/mkdocs-material/issues/1483#issuecomment-596746706) that you want to make the following function overridable in Material 5.0 or 5.1:

https://github.com/squidfunk/mkdocs-material/blob/11901049bc0a0907c1cfe96091a4ca9647b2cf64/src/assets/javascripts/components/search/query/react/index.ts#L60-L64

### Use Cases

Overriding defaultTransform() is useful to modify the search behavior, e.g., to disable the addition of a wildcard (*) to each search query.

**Comment by squidfunk** [comment]
Thanks for reporting! This is the only thing I'll try to change before the final release which may impact the configuration structure. Other than that the latest RC should be pretty stable.

**Comment by squidfunk** [comment]
64caf628 adds support for custom search transforms via theme extension, e.g. a query transform that non-sensical lowercases all characters before sending it to the index:

``` jinja
{% block config %}
  <script>
    var search = {
      transform: function(query) { 
        return query.toLowerCase()
      }
    }
  </script>
{% endblock %}
```

If no custom transform is given, the default transform is applied:

https://github.com/squidfunk/mkdocs-material/blob/64caf628354931b87662b36fd6bb3132a2dfe521/src/assets/javascripts/integrations/search/transform/index.ts#L50-L55

The default transform now allows for quantifiers (`+`, `-` etc.) and automatically adds a wildcard at the end, which is the default behavior of Material for MkDocs since version 1:

```
foo bar       => foo* bar*
foo -bar      => foo* -bar*
foo +bar      => foo* +bar*
```

**Comment by squidfunk** [comment]
The fix was just released as part of RC 4. See #1498 for details.
