### ISSUE TITLE
Move logo into partial for easier overriding

### ISSUE THREAD

**Issue by boileaum** [squidfunk/mkdocs-material#1544]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

The block

```html
          {% if config.theme.logo.icon %}
            <i class="md-icon">{{ config.theme.logo.icon }}</i>
          {% else %}
            <img alt="logo" src="{{ config.theme.logo | url }}" width="24" height="24">
          {% endif %}
```

is repeated in `material/partial/header.html` and `material/partial/nav.html` and could be factorized into a `material/partial/logo.html` file using an `include` statement.

### Use Cases

It would make easier to customize the logo area (actually, I spent some time before realizing it was double located...).

**Comment by squidfunk** [comment]
This is a great idea but only became possible because of the refactoring we're currently undertaking. If you look closely, you'll see that the `width` and `height` values are different, but those shouldn't be necessary anymore for the refactoring branch. For this reason, I just moved the logo into `partials/logo.html` as you suggested in c9b2c1ea

**Comment by boileaum** [comment]
Thanks for the quick correction.
And thanks also for this nice project!

**Comment by squidfunk** [comment]
The fix was just released as part of RC 4. See #1498 for details.
