### ISSUE TITLE
5.0.0rc4 ToC menu not rendered under specific circumstance

### ISSUE THREAD

**Issue by blakadder** [squidfunk/mkdocs-material#1563]
__I checked that...__

- [x ] ... the documentation does not mention anything about my problem
- [ x] ... the problem doesn't occur with the default MkDocs template
- [x ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x ] ... there are no open or closed issues that are related to my problem

## Description
ToC Sidebar Navigation not rendering at all with this specific layout https://github.com/tasmota/docs/blob/master/docs/Scipting-bug.md line 1528-1531

link: https://tasmota.github.io/docs/Scipting-bug/

### Expected behavior

Render ToC menu

### Actual behavior

Does not render ToC menu

### Fixing the bug

If I remove the list formatting ToC renders as it should

### Package versions

* Python: Python 3.7.4
* MkDocs: mkdocs, version 1.1
* Material: Version: 5.0.0rc4

**Comment by squidfunk** [comment]
I pulled your repository and reproduced the error locally. Indeed, removing those lines made the table of contents reappear. Unfortunately, the docs are so big that rebuilding them takes a lot of time, of which I'm currently very short.

1. Could you narrow the case down and try to reproduce the error on a mint Material for MkDocs installation? Fixing it then would be much easier, because the development cycle would be much shorter.

2. As you checked that mark, did you really try to reproduce the error with the default MkDocs theme? When I switch to `theme: mkdocs` I see no table of contents whatsoever, even when removing those lines.

My assumption would be that the error is very probably not with Material for MkDocs, but either with Python Markdown or MkDocs, but I may be wrong. A smaller reproducible case would be a great starting point.

**Comment by blakadder** [comment]
Apologies. Indeed it seems its one of the extensions but the culprit is Admonition extension. Don't know whether to keep this open considering it is included in the theme by default but is not a part of the project

**Comment by squidfunk** [comment]
The best idea would be to report the error with the extension that's causing it. Material for MkDocs only adds styling to Admonitions but doesn't interfere with parsing. If you manage to provide a reproducible test case and can narrow it down to Admonitions, it's [Python Markdown](https://github.com/Python-Markdown/markdown) where this should be reported.

**Comment by facelessuser** [comment]
Yes, and please create a minimal example that shows the error. That was a very large page of syntax which makes it hard to debug.
