### ISSUE TITLE
Q: Why are there so many dependencies?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [squidfunk/mkdocs-material#178]
Just a noobs's question: After doing `npm install` there are > 800 folders with aprox 20000 (20 thousand!) files in the `nodes_modules` folder. Are they all really neccesarry to build the site? Is this typical for JavaScript development?

**Comment by squidfunk** [comment]
Well, the build pipeline ist pretty exhaustive and build with webpack and gulp. most of the dependencies are gulp-plugins. I could either write it myself or use something that ist Estes and established. The fact that everything is built this way makes it very modular and pluggable.

**Comment by Tset-Noitamotua** [comment]
Oh hell :O 
I pray that Python becomes better in web frontend development one day. Every time I come in touch with JavaScript I am kind of *want to commit suicide*

**Comment by squidfunk** [comment]
JavaScript is actually pretty awesome these days with ES6 and Babel. The tooling is also really great. I nearly finished including a static type checker (flow from Facebook) based on JSDoc comments. It's become a mature language and it's actually (one of) the most widespread language around. I don't think Python can ever keep up in regards to tooling for web projects. Python has another focus. Let's JavaScript do the build pipeline and browser stuff.

Closing this, as it's now a discussion and not related to a feature or an error.

**Comment by facelessuser** [comment]
I think JS will always be ahead with tooling for frontend stuff since web developers use JavaScript.  I don't mean this in a bad way, but when you're a hammer, everything looks like a nail, and people like what they are good at.

JavaScript users like using JavaScript, so they write tools in JavaScript, so the ecosystem for frontend tools is more rich for JavaScript, and probably always will be since node.js exists. It makes sense. I personally prefer Python to JavaScript, and I spend a lot of time writing in Python, but I do very little front end coding. If I spent all my time writing frontend JavaScript, it would be a sharper tool for me, so it is likely I'd default to that.

**Comment by Tset-Noitamotua** [comment]
Any recommendation where to start if thinking about to learn JS? As a beginnner to programming looking at all the JS alternatives just confuses me - TypeScript? CoffeeScript? NativeScript? Angular? JQuery? Node.js? React.js? Seems like one life is not enough  to learnt all that.

**Comment by facelessuser** [comment]
JavaScript is not my expertise, as I am not a web developer.  But I've taught myself a lot of languages (even JavaScript, though I am far from a JavaScript expert).  The way I learn best is to try  and do something with the language I want to learn.  Come up with an idea and follow it through to completion.  Find some simple examples to get your self started, and then Google concepts on that you are struggling with.  Also, I personally would learn the core, stripped down JavaScript first, *then* extend it with things like JQuery.  JQuery makes JavaScript easier, but it hides a lot of learning.

Some people learn a framework first, and don't understand how it works under the hood.  I think learning stripped down JavaScript first gives you a better foundation.  I think my first hobby project with JavaScript I refused to use JQuery and wrote my own crappy framework.  Not because I thought I could do it better, but because I wanted to learn how it works.  I'm not recommending you to write your own framework, but learning how to do things without JQuery first will give you a deeper understanding.  It may also make me a masochist as I was also the only idiot college student in my class to write one of his entire projects in assembly to "learn more"; everyone else did theirs in C.  I learned a lot.  I also learned I hate writing assembly...so there's that :slightly_smiling_face:.

Oh course, I'll gladly use a framework like JQuery now as I've already learned what I wanted from doing it long hand and now picking something up like JQuery is much easier for me now.  I also understand when I should use it, and that I can get along if it doesn't make sense to use it.

Anyways, I'm not a web developer, so I am sure someone like @squidfunk  can give you probably better advise.  But as someone who has taught themselves numerous languages (at least enough to become functional with), that is my approach.

**Comment by Tset-Noitamotua** [comment]
Does this one teaches the core JS: http://javascript-roadtrip.codeschool.com/levels/1?utm_source=javascript&utm_medium=referral&utm_campaign=js ?

**Comment by facelessuser** [comment]
It sounds like it from the little I read (don't blame me later if I'm wrong :smile:).  If you are new to programming in general, maybe a structured course like this will help you get the basics.

**Comment by Tset-Noitamotua** [comment]
Ok, let's see if me and JS still can become friends ;-)

**Comment by squidfunk** [comment]
Material is built without a framework to keep it simple and lean. Maybe start by reading the code.

**Comment by facelessuser** [comment]
I like JavaScript alright.  It really has matured. The way it works makes sense in a browser.  It's asynchronous nature makes less sense to me as general purpose command line scripts, but once you get used to it, it isn't bad.  And there are applications that lend themselves well to its asynchronous nature.

If nothing, maybe you can have a working relationship. That is how I am with Perl. Sometimes we have to work together, but I don't go seeking to spend time with Perl :).
