### ISSUE TITLE
Search Enhancement: Exposing the Indexing elements predicate/filter

### ISSUE THREAD

**Issue by dgomesbr** [squidfunk/mkdocs-material#1785]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

ref: https://github.com/mkdocs/mkdocs/issues/2133
As a user I'd like to extend to have an option to control what's indexed by `Lunr`. In this particular scenario, when using awesome-pages and content that only have a title (`H2`) and content that are a list of links ( `ul > li > a`), the search look-up works like this:

0. eg: using my own mkdocs example at http://awesome-aws-workshops.com/
1. User searches for `SAP`, gets the section anchor as result `#enterprise-customers`
2. Once clicked, page scrolls to Enterprise Customers `H2`.

What I would like to see is:

0. eg: using my own mkdocs example at http://awesome-aws-workshops.com/
1. User searches for `SAP`, gets two results, both `li` texts under Enterprise Customers `H2`
2. Once clicked, we scroll to the actual element clicked from the result
3. As an extended benefit, if we could actually highlight the element found in the search
  3.1 blinking, highlight, add data-attrib? I don't know, maybe expand this further

### Use Cases

1. This would enable users to customize the content that they want to be indexed
 1.1. By default, everything remains the same, up until user provide an array/list that differs of the default, eg: `h2, h2 > ul > li`, if using CSS Selectors is possible, that would be great
 

### Screenshots / Mockups

No mockups just yet.

**Comment by squidfunk** [comment]
Thanks for the detailed description.

> - User searches for SAP, gets two results, both li texts under Enterprise Customers H2
> - Once clicked, we scroll to the actual element clicked from the result

The search is built using the `search_index.json` which is generated by MkDocs' built-in search plugin. The plugin will cut each document into sections starting with `h1`... `h6`. What you could do, in theory, is to preprocess the `search_index.json` and expand the sections. However, the `search_index.json` doesn't contain any HTML tags, only the raw text. This means that some serious hacking would be necessary to get this to work because you would have to somehow know where to split the documents. Furthermore, you would have to generate anchors in the HTML, which is a problem of its own. My best guess is that you would have to patch or extend MkDocs' search plugin. Unfortunately, we can't do anything about it at the stage of rendering the template.

> - As an extended benefit, if we could actually highlight the element found in the search
> - blinking, highlight, add data-attrib? I don't know, maybe expand this further

This, maybe, could be done, but it's also not trivial. When clicking on a search result, we would need to determine all HTML content of the respective section and just before the next section, and search for the terms to be highlighted. They could just be wrapped in `<mark>...</mark>`.

All in all, I'd rather recommend you to restructure your document.

**Comment by dgomesbr** [comment]
Thanks for taking the time on looking at it. I'm probably going that way.
