### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by pawamoy** [squidfunk/mkdocs-material#1802]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

The `mkdocs-material` currently weighs 32.42MB on my disk. Using [`duviz`](https://github.com/soxofaan/duviz), I see it is the heaviest dependency installed in my poetry env.

```
[______________________________________________________________272.76MB_____________________________________________________________]
[   material  ][ pydantic ][ mypy][nltk][mkd][jed][pip][lun][p][I]|[][]|||[]||||||||||||||||||||||                                   
[___32.42MB___][_24.83MB__][14.18][11.1][11.][10.][10.][9.0][6][5]|[][]|||[]||||||||||||||||||||||                                   
[   .icons   ]             [t]|   ||||| [th] [th] [_]|      [] ||  | |                                                               
[__30.46MB___]             [6]|   ||||| [9.] [8.] [7]|      [] ||  | |                                                               
[material][f]              ||           [r]  []|  ||                                                                                 
[22.14MB_][6]              ||           [7]  []|  ||                                                                                 
          ||                            []   |                                                                                       
          ||                            []   |                                                                                       
                                        |                                                                                            
                                        | 
```

As you can see, the icons are the culprits 🙂 

I'm usually *not* using any icon, though I know I will be happy to use some in the future. However it really feels like a waste of disk space or bandwidth considering I'll ever only use a very small fraction of the icon set Material for MkDocs provides, especially when it is installed in dozens of poetry env on a machine with limited disk/bandwidth resources.

Would there be a way to reduce the package size? Maybe make the icons a separate, optional `mkdocs-material` package?

### Use Cases

Reduce disk/bandwidth usage and installation time when installing `mkdocs-material` in several venv on resources-limited machines.

**Comment by squidfunk** [comment]
Thanks for the suggestion. I understand that the icons blow up the package, but the `tar.gz` is currently 1.8MB packed, so I don't know whether it's worth the extra effort. However, I'll think about how we could maybe restructure things a little so that we can make some things optional, but I'd consider it a rather low priority.

**Comment by pawamoy** [comment]
I didn't think about the fact that it is tar-gzipped, so the bandwidth point indeed doesn't stand. I noticed that it takes a bit more time than other packages to uncompress, but it happens rarely enough (size is more problematic).

Thank you for your consideration, I agree on the low priority 🙂

**Comment by squidfunk** [comment]
I thought about this thoroughly and I don't think we can build a slim version, because __icons are configurable via `mkdocs.yml`__. This means we would need to include all icons that are used by the theme and exclude everything else, but as soon as somebody will reference an icon (e.g. for the logo), it won't work. It will almost certainly confuse users than help. Furthermore, most people use at least some of the FontAwesome icons to include social links, so we would have to include all of them. Unfortunately, it's too fragile and has the potential to produce more work (in the form of issues) than it solves.

For this reason, I'm closing this issue. I hope you understand!

**Comment by pawamoy** [comment]
I do :slightly_smiling_face:

I guess I can manually delete the icons to free some space if needed!
