### ISSUE TITLE
Unable to create Search Page 

### ISSUE THREAD

**Issue by allanbowe** [squidfunk/mkdocs-material#1832]
I'm trying to create a search page as described here:  https://stackoverflow.com/questions/63106842/how-do-i-implement-a-search-page-on-a-mkdocs-site

My expectation was that I could do this with:

```yaml
theme:
  name: material
  include_search_page: true
```

However this throws:
```bash
WARNING -  Template skipped: 'search.html' not found in theme directories.
```

I'm looking to achieve the ability to search via url params similar to this example: http://readthedocs.sheets.ch/search?q=test

My yaml file is here:  https://github.com/sasjs/sasjs.io/blob/master/mkdocs.yml

__I checked that...__

- [ x] ... the documentation does not mention anything about my problem
- [ x] ... the problem doesn't occur with the default MkDocs template
- [ x] ... the problem is not in any of my customizations (CSS, JS, template)
- [ x] ... there are no open or closed issues that are related to my problem

### Expected behavior

setting `  include_search_page: true` would give me a SITENAME/search page that will accept url params.

### Actual behavior
error in console, no search.html generated

### Package versions

* Python: `3.8`
* MkDocs: `1.1.2`
* Material: `5.5.0`

### Project configuration

```yaml
theme:
  name: material
  include_search_page: true
```

### System information

OS:  mac

Browser - any

**Comment by squidfunk** [comment]
The `include_search_page`option is specific to the `mkdocs` and `readthedocs` themes and not supported by Material for MkDocs. Search will always be rendered as part of the interactive modal.

> I'm looking to achieve the ability to search via url params similar to this example: http://readthedocs.sheets.ch/search?q=test

[Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) is expected to support query parameters in the coming weeks.

**Comment by squidfunk** [comment]
Housekeeping. Closing as answered.

**Comment by ms-lolo** [comment]
Was about to file a ticket requesting a dedicated search page but then found this issue so figured I would just leave a comment instead. It would be nice to have a dedicated search page so I can link people with general questions to a search result that has multiple relevant items in it. Right now, I have to tell them to load any of the docs pages and search for "x" instead of being able to just have them click a link :)

Linking to an unrelated page that happens to have the search form filled out and expanded would work but sounds a bit awkward. Either would be appreciated though!

**Comment by squidfunk** [comment]
Thanks for your input on this. Yes, we can consider adding a dedicated search page to Insiders if more people need it.

**Comment by squidfunk** [comment]
[Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) supports deep linking of search results, which should make a dedicated `search.html` obsolete, i.e., [display all results relate to the search query `"code block"`](https://squidfunk.github.io/mkdocs-material-insiders/?q=code+block). This means you can also link from your documentation.

**Comment by ms-lolo** [comment]
it's not clear to me how I get a link I can share to a page with the search filled out. am I expected to build the URL myself with the `q` query string?

**Comment by squidfunk** [comment]
Theres currently no button, so you must build it manually. Where would you expect such a button? I yet haven't decided where to put it.

**Comment by ms-lolo** [comment]
I suppose next to the X on the right side of the field is where my eyes would gravitate. I'm not really sure. I always find the modal dialog for search results to be really awkward to use

**Comment by squidfunk** [comment]
Thanks! Could you elaborate on what you’d prefer to a search modal? A full page? Does the mobile view (full screen search) work better for you?

**Comment by ms-lolo** [comment]
yeah the full search page for results is what I always prefer. I don't want to link to an unrelated page just to trigger the search dialog. the search results are a resource that I sometimes want to link to. my expectation is that hitting enter after typing something in the search field will take me to a search results page. if I want to skip the results page, I would use the arrows or cursor to select one of the modal results.

**Comment by squidfunk** [comment]
@ms-lolo this theme is clearly opinionated and personally, I think that providing search as an interactive UI element, and not as part of a separate page is great UX because it doesn't require the user to step out of the current context. However, linking search results to a result page may be a valid use case, I agree, and to some users, it may appear kind of odd if a deep link expands the search bar and displays the results within.

If that doesn't work for you, no problem. There are other themes that provide a dedicated search page, like for example the stock `readthedocs` and `mkdocs` themes. I don't know whether it makes sense to add a dedicated search page to this theme in the future, as only a few users seem to want it.

Nonetheless, I'll implement your suggestion with the "share" button next to the delete button in the coming weeks, so it's easier to create deep links! That's a great idea after all.

**Comment by ms-lolo** [comment]
that sounds great and thanks again for the work! none of this is really a deal breaker for us, I'm just arguing because I enjoy discussing UX :P feel free to ignore me!

> I think that providing search as an interactive UI element, and not as part of a separate page is great UX because it doesn't require the user to step out of the current context.

If the user is typing into the search field, aren't they **trying** to leave the current context? Their goal is to find information that is not in front of them. My ideal would be to show them the results as a modal exactly how you are showing them now, but if the result isn't in that first or second item, I would take some action to go to a larger search result page that has proper pagination and can be shared normally. That could be hitting enter, or maybe a link at the top or bottom of the results modal titled something like "More Results" or something along those lines. The infinite scroll on the model right now is more difficult to use, because if there are many results and I need to click on some to see if they are what I am looking for, hitting the back button to try a new link is going to send me back to the top of your results. You can see this behavior in your example link above.

- scroll down through your results here: https://squidfunk.github.io/mkdocs-material-insiders/?q=code+block
- that changelog link looks interesting! click it
- this isn't what I was looking for, hit back
- what was the next result in the search? I need to scroll back down to the changelog result to continue my exploration

This isn't common on small sites because the search will usually give me exactly what I want right away. But on very large sites, users might need to really explore the search results. The infinite scrolling of search results is a very painful interface for this activity but a dedicated search page will have fully functional back/forward button that takes me to the exact place I left off.

**Comment by squidfunk** [comment]
@ms-lolo some very good points. The problem is that the search is entirely JavaScript-based, which makes it hard to take the user back to the exact position especially when pagination was used. All this would need to be written to the URL or some other store (i.e. local storage) and would need to be reconstructed.

Search is implemented as a list of links (= semantic HTML), so as a user you could hold the <kbd>cmd</kbd> or <kbd>ctrl</kbd> key to open the result in a new window. That's exactly what I'm doing when using Google.

__Idea__: What we could do is improve [instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading) to retain the entered search when following a search result, so that following a search result doesn't clear the search result list. Instant loading will already keep the content of the search modal when navigating pages – even the scroll state:

![Ohne Titel](https://user-images.githubusercontent.com/932156/103085448-02648680-45e2-11eb-83b1-53f615a3d27b.gif)

IMHO, this could be even better than a dedicated search page, as you'd always keep the state of your search results when navigating the site. This behavior (keeping the result) could be made opt-in by a feature flag, so authors could decide whether they want the search results to persist. Also, very large sites are the primary use case for instant loading, as the search index will not be built in every page load, so this could be a great addition/improvement.

**Comment by ms-lolo** [comment]
that does look pretty cool :) thanks for brainstorming! I haven't enabled instant loading yet  but I'll give it a shot next time I'm iterating on some of the documentation tooling.

Cheers!

**Comment by squidfunk** [comment]
Insiders 1.14.0 adds support for [search sharing](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing), which will render a _share_ button next to the _reset_ button. The button itself is a link, which will always link to the current search result, can be bookmarked, and will copy itself to the clipboard when clicked:

![screenshot-squidfunk-github-io-mkdocs-material-insiders-setup-setting-up-si-1609350745408](https://user-images.githubusercontent.com/932156/103372463-68657800-4ad2-11eb-9d13-4838f677e9a0.png)

@ms-lolo was that what you had in mind?

**Comment by ms-lolo** [comment]
yeah this looks great!
