### ISSUE TITLE
issue with "previous" text

### ISSUE THREAD

**Issue by dhifender** [squidfunk/mkdocs-material#1834]
i got issue which "previous" text not available (only "next" text showed up) in navigation when using mobile browser. how to fix it??? i attached screen capture for this issue
![IMG_3249](https://user-images.githubusercontent.com/61076468/88610402-be139f80-d0b0-11ea-9a54-5912853647b3.jpeg)

**Comment by squidfunk** [comment]
This is actually by design and was implemented exactly like Google implemented it as part of their Material Deign documentation. It makes sense to hide the previous label, because of the narrow width on mobile. Otherwise both labels will mostly be shortened and dotted `...`. It’s done with CSS, so you may override it with some additional CSS.

**Comment by dhifender** [comment]
oh..i see. thank for your explaination
