### ISSUE TITLE
Add make command on Docker image

### ISSUE THREAD

**Issue by roipoussiere** [squidfunk/mkdocs-material#1838]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Add the make command to the mkdocs-material Docker image. The make command is used on many projects as a build tool, and the related package is light.

This can be done with `apk add --update make` on the Alpine image you use.

### Use Cases

I build docs during Contiuous Integration (using GitLab-CI) using the mkdocs-material Docker image.
I set up a handy `make doc` command that runs `mkdocs build`, among many various things like copy files, apply substitutions, etc.
So the possibility to execute this `make doc` command during the CI build would be appreciated, instead of copying all the commands executed by `make doc` in my CI file.

**Comment by squidfunk** [comment]
Could you elaborate how you'd use this as part of a Docker image? You would have to override the entrypoint, as `mkdocs` is the standard entrypoint and note that it's not possible to pass command line arguments to `make`.

You can also override the official image and build your own - it's actually very easy:

``` docker
FROM squidfunk/mkdocs-material
RUN apk add --update make
```

**Comment by squidfunk** [comment]
So I thought about this some more and came to the conclusion that we shouldn’t add it. If we do, the next request would be for build essentials or CMake, and then the next and the next. The Docker image is already large enough because of the plugins and I’m thinking of providing a slim image without any plugins, so quite the contrary.

Extending is really easy and gives you the ability to cater it precisely to your use case. IMHO, a solid base image is better than one that tries to do too much.
