### ISSUE TITLE
Native Lazy Loading of Images

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#1867]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Native lazy loading of images is a awesome feature which can help reduce bandwidth consumed. It is now[ widely supported by browsers](https://caniuse.com/#feat=loading-lazy-attr) and will likely come to Safari soon too (it's currently merged in WebKit already and is available via Experimental features menu). The great thing is that it requires no JavaScript and falls back gracefully everywhere. There's really no downside to using it.

More info: https://web.dev/native-lazy-loading/

**Comment by squidfunk** [comment]
I think we already discussed this in some issue. The problem is that Material itself does not process Markdown/HTML, so the moment the template is rendered is already too late. Two options:

- Attribute lists, as with image alignment (manual)
- some Markdown extension that adds the attribute automatically

**Comment by squidfunk** [comment]
I'll add something to the documentation. I guess deciding on a case-by-case basis whether images are lazy loaded makes sense. If somebody wants to jump in and implement an extension for that, we can also add it to the docs.

**Comment by squidfunk** [comment]
Added in fe9cfb52.
