### ISSUE TITLE
Allow dark code background but with the default light theme.

### ISSUE THREAD

**Issue by STEELBADGE** [squidfunk/mkdocs-material#1904]
It would be nice to have the option to have a dark code background while using the light theme. Currently the only way to get the dark code background is to use the "slate" param in the config.

I

**Comment by squidfunk** [comment]
Already on the roadmap for Insiders 😊
https://squidfunk.github.io/mkdocs-material/insiders/#black-pearl

**Comment by squidfunk** [comment]
A slight change of plans – I've put quite some time into investigating adding a toggle similar to the general color palette toggle to support multiple color schemes for code blocks, but I couldn't come up with a satisfying solution, yet. I'm also investigating whether we can just leverage Pygment's themes, but that would need some more work.

Given that this feature was scheduled for the [next funding goal](https://squidfunk.github.io/mkdocs-material/insiders/#2000-black-pearl) which we're expected to reach in the coming weeks, I moved the back-to-top button implementation down from the [Ghost Pepper](https://squidfunk.github.io/mkdocs-material/insiders/#4000-ghost-pepper) funding goal and moved the code block toggle out of the roadmap. I'm very sorry if there were expectations regarding this feature, but it turned out to be more complex than expected.

**Comment by squidfunk** [comment]
Closing for housekeeping, as it's not to ready for implementation. It's still on the [roadmap](https://squidfunk.github.io/mkdocs-material/insiders/#future) for future evaluation, though.
