### ISSUE TITLE
Allow to hide left-hand navigation

### ISSUE THREAD

**Issue by fkorotkov** [squidfunk/mkdocs-material#1930]
- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Similar to #1815 but a bit different. Right now there might be a case when there is only one item in the left navigation panel (see a screenshot below). Looks like it can be safely removed to allow for a wider contents.

### Use Cases

Useful for sites with small sections.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/989066/93338283-2dc42200-f7f8-11ea-87b4-7fa4a722e74a.png)

**Comment by squidfunk** [comment]
Sounds reasonable! Personally, I'm not a fan of stretching the content area, but we can implement this behavior as an option. I'll think about this when tackling the TOC features as part of Insiders. Great to know in advance.

**Comment by fkorotkov** [comment]
Thank you! 

Yes, I'm also not a fan of stretching but in this case it looks a bit weird. I've fixed that particular issue without stretching with a custom `nav-item.html` partial](https://github.com/cirruslabs/cirrus-ci-docs/blob/master/theme/partials/nav-item.html#L5) but it still leaves an empty column which takes space. And an extra space might be handy for pages with tables.

Anyways, since you are going to tackle it as part of еру TOC feature feel free to close this issue. I thought that since TOC feature is still in design/thinking phase this little enhancement can be tackled separately.

**Comment by squidfunk** [comment]
I'd leave it open, so we can collect dedicated feedback ☺️

**Comment by squidfunk** [comment]
I've thought about it and I think we should solve it with a template which just doesn't include the navigation. Would that work for you? You would have to specify the following for the respective page, but it's more flexible as you can even do it if there is more than one page:

```
template: ...
---

... Further Markdown...
```

**Comment by fkorotkov** [comment]
Definitely will work! 👌

**Comment by squidfunk** [comment]
In the end, I decided to implement it via metadata 😊 This allows for using custom templates without further ado. Now, the table of contents and navigation can be hidden for an individual page. It doesn't make sense to hide it for all pages, which is why there's no global option, except for the table of contents maybe, and that can already be done using [toc_depth](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#toc_depth).

The `master` of Insiders now allows us to do the following:

__Hide table of contents__:

``` markdown
---
hide:
  - toc
---

# ...
```

![screenshot-localhost-8000-setup-changing-the-language-1604764164815](https://user-images.githubusercontent.com/932156/98445681-37dc1000-2119-11eb-9f74-7db93dfe9e70.png)

__Hide navigation__:

``` markdown
---
hide:
  - navigation
---

# ...
```

![screenshot-localhost-8000-setup-changing-the-language-1604764212513](https://user-images.githubusercontent.com/932156/98445695-517d5780-2119-11eb-9a8d-e0893822e173.png)

__Stretch to full width__ (= hide both):

``` markdown
---
hide:
  - navigation
  - toc
---

# ...
```

![screenshot-localhost-8000-setup-changing-the-language-1604764277189](https://user-images.githubusercontent.com/932156/98445715-796cbb00-2119-11eb-9eae-d58592265c9d.png)

A release will follow, I'm trying to fix 1-2 bugs before issuing a new release. I'm also sorry this took so long, but I haven't decided on an implementation. However, I believe the new solution is far superior to anything we had before, as we can now easily hide more elements, if needed. I also made sure that the spacing of the content area is correct, i.e. aligns with the header and tabs navigation. I'm super happy with the outcome!

I'm also preparing documentation.

**Comment by squidfunk** [comment]
Oh, and I made sure that mobile navigation still works. Removing the element from the DOM would lead to broken mobile navigation. It should all work as expected.

**Comment by squidfunk** [comment]
6.1.4+insiders-1.9.0 was just released and [the documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hide-the-sidebars) explains how to get it to work 😊

**Comment by YevheniiPokhvalii** [comment]
@ squidfunk It would be cool to have a button to hide/show table of contents, to hide/show the menu.

**Comment by hasansezertasan** [comment]
Is there a way to accomplish this without modifying the "*.md" files, maybe some configuration inside the "mkdocs.yml"?

**Comment by alexvoss** [comment]
@hasansezertasan if you needed this for a particular subsection of your site/documentation then you could use the [Meta plugin](https://squidfunk.github.io/mkdocs-material/plugins/meta/) available in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) to apply the necessary metadata to the pages. Just put a `.meta.yml` file into the directory containing the files where you want to hide navigation and/or toc. Would save you from having to put the settings into each of them.

**Comment by hasansezertasan** [comment]
> @hasansezertasan if you needed this for a particular subsection of your site/documentation then you could use the [Meta plugin](https://squidfunk.github.io/mkdocs-material/plugins/meta/) available in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) to apply the necessary metadata to the pages. Just put a `.meta.yml` file into the directory containing the files where you want to hide navigation and/or toc. Would save you from having to put the settings into each of them.

Thank you @alexvoss for the great information 🙏.
