### ISSUE TITLE
Improve accessibility on the theme

### ISSUE THREAD

**Issue by fabianpiau** [squidfunk/mkdocs-material#1953]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

It probably depends on the palette accent/primary color used, but we have this kind of accessibility issue at least with the red and blue variation.

I was running a Lighthouse check on our website and realize this accessibility issue:

```
Background and foreground colors do not have a sufficient contrast ratio.
```

![image](https://user-images.githubusercontent.com/6502229/94462378-57475b00-01b3-11eb-9b48-7c50c4958f3c.png)

This is valid for the title and links in the header, the links in the main content and the links in the footer.

### Expected behavior

Lighhouse do not report any contrast issue.

### Actual behavior

Lighhouse reports some contrast issues with various elements of the page.

### Steps to reproduce the bug

1. Open a website using mkdown material on Chrome
2. Click on the Lighthouse tab and click on generate report
3. Check the issues related to Accessibility

**Comment by squidfunk** [comment]
Thanks for reporting! Unfortunately, we cannot optimize for all color combinations, so there will always be problems when picking out colors, [as mentioned in the documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color):

<img width="724" alt="Bildschirmfoto 2020-09-28 um 20 10 18" src="https://user-images.githubusercontent.com/932156/94469590-a8ad1580-01c6-11eb-8de8-76b565795676.png">

However, we can try to improve the contrast for the default colors.

**Comment by squidfunk** [comment]
On a side note, with [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) you can [pick custom colors per palette](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle), so you can pick better-suited colors for the dark mode.

**Comment by fabianpiau** [comment]
Yes this is understandable, I did not know about the custom color palette available via Insiders.
It will be nice to make this extra feature available for the standard version so people can make it more accessible.
Thanks for the feedback!

**Comment by squidfunk** [comment]
Sure! It will be merged back into `master` as soon as the [funding goal](https://squidfunk.github.io/mkdocs-material/insiders/#black-pearl) is hit 😊 You'll have immediate access if [you become a sponsor](https://squidfunk.github.io/mkdocs-material-insiders/insiders/#how-to-become-a-sponsor) of this project, which goes from $10/m.

If you don't want to become a sponsor, note that you can already also tweak [colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors) and [color schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes) easily with some CSS.

**Comment by squidfunk** [comment]
I investigated this issue and found the following issues with the original theme on the "Getting started" page:

<img width="718" alt="Bildschirmfoto 2020-10-04 um 13 57 49" src="https://user-images.githubusercontent.com/932156/95014800-9d843a80-0649-11eb-9167-353fb03f0c46.png">

- Active tab labels (the blue used for the [first tab](https://squidfunk.github.io/mkdocs-material/getting-started/#with-pip) titling "Material for MkDocs"). The tab label color is entirely configurable through the [accent color configuration](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color), and also customizable via [3-4 lines of extra CSS](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors). While I agree that we should try to meet AA standards, the tab label color has a contrast ratio of 4.24 which is almost 4.5 which would pass the test, meaning we're not far off. We would need to deviate from Google's official Material color palette, which I would rather not do, as this will be an entire rabbit hole I don't have the time to go down.

- The non-link footer text, i.e. the "Made with". I agree that this color is more off, but the problem here lies in the way links are styled in the footer. The accent color is not used on hover, to better separate the footer from the rest of the content. Also, darker accent colors will not work with the footer, thus we can only transpose the problem. For this reason we need three shades of grey: white is the hovered state, grey the unhovered state of a link, and a dark grey is the normal text color. To change the color, you can use the following [extra CSS](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors):

``` css
.md-footer-copyright {
  color: white;
}
```

I hope you understand this decision. While we try to make this theme as accessible as possible, some things have to be compromises, because of the many ways this theme can be configured. In the end, it's a combinatorial problem.
