### ISSUE TITLE
One-click documentation for python from source code

### ISSUE THREAD

**Issue by rakesh4real** [squidfunk/mkdocs-material#1976]
Hi, Does mkdocs produce same documentation website using python docstrings from source code (for for any other language) ?

**Comment by squidfunk** [comment]
Closing, as it doesn't conform to the issue guideline. This is not an issue with this project, but a [question](https://github.com/squidfunk/mkdocs-material/blob/master/.github/ISSUE_TEMPLATE/config.yml). Please ask it on the [official Gitter channel](https://gitter.im/squidfunk/mkdocs-material) or on [StackOverflow](https://stackoverflow.com).

**Comment by shaypal5** [comment]
I'd like to chime in and say I think having an answer here could be nice, since GitHub issues are often a place where people ask and look for answers for such feature-related questions (many projects even have a dedicated `question` issues label, including a couple of very small ones I run).

This is doubly true since its very hard to find `mkdocs-material`-specific questions and answers on the internet, in part because `mkdocs`-related stuff - that might not be relevant to an `mkdocs-material`-specific question - keep popping up.

Also, concretely, [searching "mkdocs-material docstring" on stackoverflow](https://stackoverflow.com/search?q=mkdocs-material+docstring) yields nothing, and [searching "mkdocs docstring" on stackoverflow](https://stackoverflow.com/search?q=mkdocs-material+docstring) yields 3 questions that do not provide any concrete answer.

Regardless, I want to thank you for this amazing open source project and the evident effort you put into answering people's questions and providing assistance to users.

**Comment by facelessuser** [comment]
I think this issue was answered this way prior to GitHub Discussions being enabled on the project and I think that would be a suitable place for such a question.

With that said, the real answer is that this should be done either with Python Markdown extensions or MkDocs plugins, neither of which are really directly related to the Material theme. It may be nice if someone who was aware of such extensions/plugins posted a link to a tutorial on how to do so (assuming a solution already exists).

I feel this is more a question that can/should be answered by members of the community that have already gone down this road, not specifically the maintainer of Material (unless he happens to have gone down this road before 🙂).

**Comment by shaypal5** [comment]
I see your point. Very valid. I understand.

However, having gotten an answer on the project's gitter, I'll point any future seekers at the same direction, a specific mkdocs plugin called `mkdocstrings`:
https://github.com/mkdocstrings/mkdocstrings

**Comment by facelessuser** [comment]
Perfect. The official MkDocs project has a wiki with all sorts of links to plugins, including the one you linked. I probably should have linked such resources. That is usually a good place to start in the future for questions like this or others: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#mkdocstrings.

Glad you figured something out!
