### ISSUE TITLE
Search highlight interprets code blocks as JavaScript

### ISSUE THREAD

**Issue by michael-nok** [squidfunk/mkdocs-material#2068]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When perform a search query with search.highlight enabled, code blocks may get interpreted as JavaScript functions, causing the code block to partially render.

### Steps to reproduce the bug

1. Create a page that contains a code block and a <script name> section:

# Code block testing
```
   This is a <script name> testing
   Can anyone read me?
```
2. Do a search for "anyone" or anything else on the page, and when it displays, the code block will be cut off.
mywebsite.com/test.html?h=testing

## Expected output
![Expected output](https://user-images.githubusercontent.com/67281799/99990647-15d1c700-2d82-11eb-8c17-993aa8fbaff7.png)

## Actual output
![Actual output](https://user-images.githubusercontent.com/67281799/99990649-166a5d80-2d82-11eb-93a6-a66e16942f00.png)

### Package versions
Python 2.7.18
mkdocs, version 1.1.2 from /home/ec2-user/.local/lib/python3.7/site-packages/mkdocs (Python 3.7)
Version: 6.1.0+insiders.1.7.0

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by facelessuser** [comment]
This issue is not a theme issue. Most likely it is a Markdown parsing issue. I can't tell what version of Python you are actually using as you've mentioned both 2.7.18 and Python 3.7.

Most likely, I'm guessing you are using Python Markdown 3.3+ which uses a new HTML parser. There are still some bugs being worked out of it as I think it was a bit prematurely released (there just weren't tests in place to catch the kind of edge cases that were discovered after release). You most likely won't have an issue if you use Python Markdown 3.2.2 IIRC.

**Comment by squidfunk** [comment]
It could be a theme issue, I already have an idea what's probably causing it - I'll investigate it asap!

**Comment by squidfunk** [comment]
Fixed and released as part of Insiders 1.11.2! Text nodes are now properly escaped when using search highlighting.
