### ISSUE TITLE
Repository information facelift (Stars, Forks, Latest Release...)

### ISSUE THREAD

**Issue by hellt** [squidfunk/mkdocs-material#2082]
## Description

Allow a user to configure mkdocs-material to display the latest github release version for a linked repo.

### Use Cases

Github releases are used more and more to distribute source code or pre-built artifacts. Since mkdocs-material doc site is often a front of the underlying repo (effectively being a home page of a project in lots of cases) it seems very valuable to display the latest available release of the project.

### Screenshots / Mockups

I leave it to the contributors/authots to decided what is the best way to display that information, a very simple mockup can look like that:

![image](https://user-images.githubusercontent.com/5679861/100717566-826c4780-33ba-11eb-8874-4c30abcc9878.png)

The assumption here is that clicking on the release `<li>` element will forward a user to the gh releases page directly, instead of the repo main page

**Comment by squidfunk** [comment]
Thanks for the suggestion. Unfortunately, we cannot link the version `li` to the release - that would be a link inside a link, as the whole repo section is clickable. Futhermore, Lighthouse will complain that links are too small. If you'd like to link the GitHub section to the latest release, just add the following to `mkdocs.yml`:

``` yaml
repo_url: https://github.com/<user>/<repo>/releases/latest
```

**Comment by hellt** [comment]
I'm ok without the release number having a link to the release specific URL
It's good just to display the latest release version

**Comment by squidfunk** [comment]
<img width="784" alt="Bildschirmfoto 2020-12-22 um 17 03 32" src="https://user-images.githubusercontent.com/932156/102908628-096f8580-4478-11eb-9389-1affd9a11bf2.png">

So I think I'm all for pulling off a slight facelift of the repository container, as it hasn't received any love since version 1. We could replace the titles with GitHub's own icons (it's more international anyway), and maybe allow for some customization via `mkdocs.yml`, i.e. the author can provide a list which is composed of allowed keywords to denote the order he wishes:

``` yaml
extra:
  repo:
    facts:
      - latest
      - stars
      - forks
```

**Comment by hellt** [comment]
Oh that looks lovely!

**Comment by squidfunk** [comment]
The repository info facelift is now part of Insiders and can be seen in-action on the [official docs](https://squidfunk.github.io/mkdocs-material-insiders)! It also includes the __latest release tag__ (non-draft, non-prerelease). Now configuration change is necessary, it's completely automatic. This means it's currently also not configurable, let's see if that is necessary.

![screenshot-squidfunk-github-io-mkdocs-material-insiders-getting-started-1610877274394](https://user-images.githubusercontent.com/932156/104837058-7c6eef00-58b2-11eb-8464-ae26ec872c45.png)

<details>

<summary>What it looks like on mobile</summary>

![screenshot-squidfunk-github-io-mkdocs-material-insiders-getting-started-1610877338087](https://user-images.githubusercontent.com/932156/104837071-914b8280-58b2-11eb-875a-9e92f4965ae3.png)

</details>

**Comment by maxschulz-COL** [comment]
> The repository info facelift is now part of Insiders and can be seen in-action on the [official docs](https://squidfunk.github.io/mkdocs-material-insiders)! It also includes the **latest release tag** (non-draft, non-prerelease). Now configuration change is necessary, it's completely automatic. This means it's currently also not configurable, let's see if that is necessary.


Hey @squidfunk ! First of all thanks for the amazing tool, I really love it ❤️ 

Stumbled on this issue, and noticed the information was not configurable as suggested in a post above

```yaml
extra:
  repo:
    facts:
      - latest
      - stars
      - forks
 ```

Our use-case, and I think potentially very relevant for other users too, is to operate from a monorepo that has different releases for different packages. Now I get that it's probably out of scope to have the release tag information by linked to specific package releases, BUT the above proposed configuration would be amazing because:
- it would allow us to turn off the release tag
- BUT keep the stars and forks, which is non-release specific information

What do you think?

**Comment by squidfunk** [comment]
Thanks for suggesting and for sharing the love! We did not implement this, because it would require too much logic for something that most users don't need to configure. For this reason, the easiest way is to just hide the release info with CSS:

``` css
.md-source__fact--version {
    display: none;
}
```

Just add this to an [additional style sheet](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) and you're all set.
