### ISSUE TITLE
Banner for old doc versions

### ISSUE THREAD

**Issue by JulioV** [squidfunk/mkdocs-material#2084]
- [ x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [ x] ... to my best knowledge, my idea wouldn't break something for other users
- [ x] ... the documentation does not mention anything about my idea
- [ x] ... there are no open or closed issues that are related to my idea

## Description
Create a banner at the top of each page on old versions of the docs (when managed by `mike`) that point to the latest (most recent) version

### Use Cases

Whenever a user lands on an old docs page, they can be redirected to the most recent version like `readthedocs`

### Screenshots / Mockups

There are some suggestions in this issue https://github.com/jimporter/mike/issues/26 (see screenshot below)

There could be a flag to activate this feature  on every version (and its aliases) except for the most recent one based on `mike`'s `versions.json` indexes:

```
[
  {"version": "1.0", "title": "1.0.1", "aliases": ["latest"]},
  {"version": "0.9", "title": "0.9", "aliases": []}
]
```

The actual content and look and feel could be customizable like the announcement section of the theme

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/5264981/101108655-02ed9c80-35a3-11eb-99c1-ee5823c254f6.png">

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting! I agree that this is a good idea which we should investigate. However, from the top of my head, there may be problems with content shift due to the fact that the `mike` integration is all-JavaScript, which means that the version selector is rendered after the initial load. Thus, the notice will be displayed _after_ the initial render, shifting the content downwards, which is penalized by reports like Lighthouse and in general not a good idea. Material for MkDocs painstakingly tries to minimize content shift and it does a very good job at that, so a possible solution for displaying a banner should not introduce this problem.
