### ISSUE TITLE
Accent current section in integrated ToC

### ISSUE THREAD

**Issue by danierutu** [squidfunk/mkdocs-material#2152]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Using the regular Table of Contents (right sidebar), as you scroll through the page, the current section in the viewport is highlighted with the accent color, and the sections you leave behind are greyed out. However, using the integrated ToC (from Prairie Fire), it's just static. It'd be cool if it behaved like the regular one.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, the labels should definitely be blurred/highlighted like when the table of contents is on the right.

**Comment by squidfunk** [comment]
So fixing this is quite tricky, as currently there can only be one component with the same name due to the way the observable architecture is designed. I want to fix this in its entirety, but that may take some time. I'm preparing a refactoring of how components are detected and mounted which is necessary to attach the same behavior to multiple components. Once this is done, fixing this issue is a no-brainer.

**Comment by squidfunk** [comment]
I started with the refactoring and solved the issue with the table of contents:

https://user-images.githubusercontent.com/932156/105685510-70a8ab80-5ef6-11eb-87fc-9b8fe3d9e97d.mp4

It's still on a branch and not ready for merge yet because it's a pretty serious refactoring I'm currently undertaking that will simplify the observable architecture _a lot_. I expect it to be ready in the coming weeks. The refactoring is necessary as I've seen some downsides of the current architecture when iterating on new features. The new, simpler, architecture will allow us to achieve a higher velocity iterating on new features.

**Comment by danierutu** [comment]
Wow, that's fantastic. I didn't expect that such an apparently simple fix would actually take that amount of work in the backend. You never stop impressing me! Keep it up, and don't rush.

**Comment by squidfunk** [comment]
7.0.0b1 was just released, which includes the fixes. What's even better is that now, on mobile, the anchors are also blurred:

<img width="521" alt="Bildschirmfoto 2021-02-12 um 18 01 17" src="https://user-images.githubusercontent.com/932156/107798389-56772600-6d5c-11eb-858f-15aa218e4510.png">

**Comment by facelessuser** [comment]
Oh, this is nice, it makes it much more usable. I'll probably try this out this weekend.

**Comment by squidfunk** [comment]
Released as part of 7.0.0.
