### ISSUE TITLE
[Refactor] Option to disable search box individually from search feature

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#2274]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Allow disabling search while leaving searchbox intact.

### Use Cases

For use with 3rd party search engines like Algolia etc

### Screenshots / Mockups

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Have you tried removing `data-md-component=search` on the title? That should keep the search. Could you elaborate on how you would imagine this feature to be from a user perspective?

**Comment by Stanzilla** [comment]
I have not, that was mostly my question on Gitter, what the best way would be to do this.

**Comment by squidfunk** [comment]
Yeah, so I thought about this a little and am leaning towards not adding an option in `mkdocs.yml` for this, because it would break out of the regular search configuration (which is part of the search plugin). I'd consider your request more or less as a customization, as you would need custom JS anyway when integrating a third-party search provider. Thus, the easiest way to achieve this is to remove the `data-md-component` attribute here:

https://github.com/squidfunk/mkdocs-material/blob/7ede86eba197be55e31ef8c017daa3112c856c38/src/partials/search.html#L26

I just tested it. When you do this, Material for MkDocs will just ignore the search box.

**Comment by Stanzilla** [comment]
Ah interesting, losing the animation was fine but that also gets rid of the keybind to toggle it, I guess if I can add that back, it should fit my needs!

**Comment by squidfunk** [comment]
Have you checked https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts ?

**Comment by Stanzilla** [comment]
not yet, thank you!

**Comment by squidfunk** [comment]
Closing 😉
