### ISSUE TITLE
Allow manual overriding of footer navigation on a per-page level

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#2357]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description
The idea is to have a way to set the target page for the footer's "Next" and "Previous" section on a per-page level, with the option to also disable it.

This could be done by having frontmatter f.e. to then define the next page relative to the current one. or with an absolute path.

Example:
```yaml
---
next: "" # Empty String disables the option
previous: "../previous-post.md" # Post of same folder
---
```

### Use Cases
This is useful to have an easy way to customize the footer navigation for things such as tutorials or blog-posts that you want to go through in order.
It also allows you to prevent the page from linking to another page in a different section.

As an example, with the below structure
```
- docs/
   |- index.md
   |- blog/
   |   |- post1.md
   |   |- post2.md
   |   |- post3.md
   |- archive/
       |- post4.md
       |- post5.md
```
can I now disable the "previous" and "next" option for post4.md and post3.md respectively to prevent the footer showing these two posts from the other page.

### Screenshots / Mockups

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting! I understand the use case, but I'm not yet convinced that this is a feature many users would want. We can let it sit here for a while and check if there's a significant interest 😊

**Comment by squidfunk** [comment]
Thanks again for suggesting this feature. 

In general, we can't link Markdown files from front-matter as your proposal suggests, we would have to link the actual pages (= resulting URLs). AFAIK there's no template helper to transform a `.md` file into an actual link. This makes it challenging, because when MkDocs is built with `use_directory_url: false`, we would need to link to actual HTML files, as MkDocs now produces `* .html` URLs, so they can be served via `file://`. Furthermore, besides the actual links, we would also need to add the respective titles that appear below "Prev" and "Next".

So, to sum up: it's all solvable, but I'm currently not considering it for implementation due to the complications with directory URLs. My advice would be to define the canonical ordering of pages via the `nav` entry or use one of the many navigation plugins that are listed in the MkDocs wiki to find a structure that works for you. You can also override the `footer.html` yourself and support for the `page.meta.*` keys – it's quite simple. Here's an example that shows how `page.meta.*` can be used:

https://github.com/squidfunk/mkdocs-material/blob/73602b23e158c42021d41a31e254d8448f924aa6/src/base.html#L34-L39

To hide the footer nav entirely, you can use CSS:

``` css
.md-footer__inner {
  display: none;
}
```
