### ISSUE TITLE
The logo link points to site_url if it's set; this can sometimes conflict with mike

### ISSUE THREAD

**Issue by jimporter** [squidfunk/mkdocs-material#2388]
This is a bit of a weird issue, so I'll do my best to explain it. I recently landed a fix for https://github.com/jimporter/mike/issues/40 which, among other things, allows you to set a `canonical_version` in the `mike` MkDocs plugin; this is there to allow for SEO so that the `<link rel="canonical">` tag always points to the `latest` version alias. That way, when search engines index your site, they'll link to the `/latest/` version, rather than showing results for some random old doc version that was current when they indexed the site.

However, this causes an odd behavior with the Material theme. Suppose I have 2 versions: `1.0` and `2.0` (aliased with `latest`), with `canonical_version` set to `latest`. If I go to the 1.0 docs and click the top left logo, I'll be taken to the homepage for the 2.0 docs because the `site_url` is `https://example.com/latest/`. I think that's the wrong behavior, and a user would expect to stay on the 1.0 docs. This is only an issue when `canonical_version` is explicitly set though; when it's unset, things should work fine.

Note: since https://squidfunk.github.io/mkdocs-material-example-versioning/ was built with mike 0.5, the canonical URL is set incorrectly there; that'll be fixed in mike 1.0 via [this commit](https://github.com/jimporter/mike/commit/bf4f54f9e8d5a2ff70bf7d071e659e725e85866a).

**Comment by squidfunk** [comment]
Thanks for reporting. I agree, that the user should stay on the current version– only the version selector should change the version, not internal navigation. The `site_url` is determined here:

https://github.com/squidfunk/mkdocs-material/blob/73602b23e158c42021d41a31e254d8448f924aa6/src/partials/header.html#L23-L27

And then used here:

https://github.com/squidfunk/mkdocs-material/blob/73602b23e158c42021d41a31e254d8448f924aa6/src/partials/header.html#L37-L44

Do you have an idea what we need to change to support `mike`?

**Comment by jimporter** [comment]
I think what we'd need to do is *only* use `config.site_url` for setting the canonical URL. Then we'd change line 24 to something like this:

```
{% set base_url = d(nav.homepage.url, true) | url %}
```

(And update uses of `site_url`, of course.) Since `config.site_url` can point to a different version of the docs (really, it can point *anywhere at all*), I think it's safer to avoid using it for links that humans will click on. This is what the default MkDocs theme does for its link in the top left: https://github.com/mkdocs/mkdocs/blob/dd903d3092a9288f6c1ab2291b0a176a48351611/mkdocs/themes/mkdocs/base.html#L66

**Comment by squidfunk** [comment]
Aaaah, now it clicked. I just remembered why we did it like that - because some users wanted to set a `site_url` that is different from the base URL of the hosted docs so the user is taken back to the main website, i.e. when docs are hosted in a subfolder. This clearly interferes with versioning, thus we should consider removing (or replacing) this functionality. We could add something like `extra.homepage` that would override the behavior of the button, if desired, but we should use `nav.homepage.url` in general to keep versioning working.

Regarding the 404.html - yeah, it would be perfect if we could somehow ensure that there's a `404.html` on the top-level, but I assume there's no canonical way with `mike` to do this.

**Comment by jbms** [comment]
I also agree it makes sense to change the logo to link to the base URL of the docs, in case `site_url` isn't correct (including local development).  However, if you change it to a relative link, there is an issue when instant navigation is enabled:

Instant navigation doesn't currently replace the logo link when loading a new page, but the relative link may become incorrect after navigating.  One solution is to replace the logo link as well, e.g. with ".md-header__button.md-logo", but more generally the issue applies to every link outside the content area that may be relative.  It seems like it would be wise to find a general solution to the problem rather than fixing each individual occurrence.

**Comment by squidfunk** [comment]
@jimporter I've followed your proposal and removed `site_url` from the home button in 5037094b. I added a new config option called `extra.homepage` (currently undocumented) which allows for setting a dedicated URL, to achieve the old behavior with `site_url`. Could you try the latest `master` and check whether the issue persists? If this is fixed, I'll add documentation on the new ways of configuration and issue a new release.

**Comment by squidfunk** [comment]
The fixes have been released together with 7.0.6. I also added documentation for the new `extra.homepage` option, which is located after the logo configuration settings.

**Comment by jimporter** [comment]
I finally had a chance to test this, and everything looks good to me. Thanks for the fix!

**Comment by squidfunk** [comment]
Perfect!
