### ISSUE TITLE
Hide/Show Table of Contents Sidebar

### ISSUE THREAD

**Issue by omento** [squidfunk/mkdocs-material#242]
Is it possible to add the ability to hide and show the sidebar? Having all of the permalinks showing up is a nice touch for certain occasions, but I also believe that the central column may to a bit too narrow with the size of the text currently. It may just be I'm used to reading smaller text than `1.6rem`.

I know I could modify the theme itself, but my JS skills are non-existant nor would I want to completely remove the sidebar. I think an option to collapse that sidebar into the right side of the screen would provide the main columns more space and remove clutter from those who don't need it.

**Comment by squidfunk** [comment]
This wouldn't really work well with the physics of the Material theme. Scientifically, the optimal line length for reading is around [50-75 characters](https://baymard.com/blog/line-length-readability). The width of the container even exceeds this and contains 80-90 characters, on tablet landscape more, because of the liquid layout. Making the container even wider will degrade the reading experience. This is the metric the Material theme is designed around (and yes, it's opinionated), so there's no plan on making the container wider by hiding the sidebar or other elements.

**Comment by omento** [comment]
Thanks for the explanation! I should read more into the Material spec, I've dealt with opinionated frameworks in the past (Foundation). I guess what's throwing me off is the font increase at 1600px. Once the container reaches that size the increase in font due to the usage of `rem` knocks off a couple of lines from being read, but that must be due to maintaining the ideal line length.

**Comment by squidfunk** [comment]
The font-size increase at 1600px is easily avoidable by resetting the property on the `html` element:

``` css
@media only screen and (min-width: 100em) {
  html {
    font-size: 68.75%;
  }
}
```

Closing this issue for now.
