### ISSUE TITLE
bug(css): Admonition collapsible block (Details extension) renders incorrectly

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2432]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Only verified via Firefox on Linux. Rendering bug as shown below. Upstream example for the extension does not have this visual discrepancy.

I tried looking through prior issue history and didn't have luck finding it reported before. I've looked at `git blame` history, but the commit that introduced the error doesn't provide enough context to why the CSS property was added, perhaps you know the reason (if it was to fix an actual bug elsewhere).

https://github.com/squidfunk/mkdocs-material/blob/dbad6491819e8a7ef67fb3a83b1a13c605ae0a82/src/assets/stylesheets/main/extensions/pymdownx/_details.scss#L43

`.md-typeset details` sets `overflow: visible;` which introduces the rendering issue. It overrides the `.md-typeset .admonition, .md-typeset details` admonition selector that sets `overflow: hidden;`:

https://github.com/squidfunk/mkdocs-material/blob/dbad6491819e8a7ef67fb3a83b1a13c605ae0a82/src/assets/stylesheets/main/extensions/markdown/_admonition.scss#L64

If this override is not required, it resolves the rendering bug and has no noticeable effect on the behavior (collapsed/expanded), at least on the browser where this issue was noticed.

### Expected behavior

![Screenshot_20210313_152938](https://user-images.githubusercontent.com/5098581/111016119-ef0ecd80-8410-11eb-8cad-d8ca0b601e8e.png)

### Actual behavior

![Screenshot_20210313_152832](https://user-images.githubusercontent.com/5098581/111016088-c981c400-8410-11eb-802b-93ad951484ed.png)

### Steps to reproduce the bug

1. Visit https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks
2. Expand the *Details* block, or scroll further down and look at the expanded by default variant.
3. Notice the left side vertical bar colour is not of consistent width across the expanded and collapsed boundary.
4. View upstream example where this is not an issue: https://facelessuser.github.io/pymdown-extensions/extensions/details/#syntax

### Package versions / Project configuration / System information

Active release used for project demo site: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks

**Comment by squidfunk** [comment]
Thanks for reporting and investigating possible solutions.

I agree that at a first glance, `overflow: visible` doesn't seem to be necessary (anymore?), so we can remove it. If you wish to propose a PR, I'm happy to merge it. Note, however, that in Insiders, I've started to remove `overflow: hidden` to support the new code block annotations feature inside containers like admonitions, details, and tabs, as it was primarily used to prevent margin collapse, which is also achieved by `display: flow-root` with fewer side-effects. Keeping `overflow: hidden` would cut off those tooltips.

In general, I'd consider this as a very minor rendering bug, because so far it was only verified to exist on Firefox, Linux (GTK, IIRC from your other issues). Linux [currently accounts for 2% of OSes in global browser market share](https://gs.statcounter.com/os-market-share/desktop/worldwide), with [Firefox accounting for roughly 20%](https://www.netmarketshare.com/?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%2C%7B%22platform%22%3A%7B%22%24in%22%3A%5B%22Linux%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browser%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktop%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222019-11%22%2C%22dateEnd%22%3A%222020-10%22%2C%22segments%22%3A%22-1000%22%7D) (with not all of them using GTK). Thus, it shouldn't affect more than 0,4% of users, which is 5x less than the [current IE share](https://gs.statcounter.com/browser-market-share/desktop/worldwide) (currently at 2%) which we don't support at all.

**Comment by polarathene** [comment]
> Thus, it shouldn't affect more than 0,4% of users, which is 5x less than the [current IE share](https://gs.statcounter.com/browser-market-share/desktop/worldwide) (currently at 2%) which we don't support at all.

That would be inaccurate metrics to base this off of. At least when writing technical documentation for software (which is presumably a common case for mkdocs, but I could be wrong).

On Linux Firefox is a common browser choice, it's often the default web browser provided with installs. In the docs deployment case I'm supporting, it's for a Dockerized mail server, it's not unlikely for contributors to be on Linux. At the very least 0.4% is going to be way off base for users on some deployments like the one I'm working with.

From your own support perspective as a whole to the user base, granted that will still be a low metric, but it's unlikely to be that low for majority of intended audiences viewing docs, especially technical docs for software development.

As for the GTK part, that's a given with Firefox on Linux, it's the UI toolkit it uses.

---

I had a mess around with the related styles again. If `overflow` is in fact a problem that can't be changed from how it is, the rendering issue appears to be due to having two border lines rendered with some overlap going on. I was able to adjust the padding to resolve that:

```
.md-typeset .admonition, .md-typeset details {
    padding: 0 .65rem;
```

That may not be appropriate for you still? (unclear if `+0.05rem` of padding will affect anything on other browsers)

I applied the same change to [PyMdown Extensions equivalent demo page](https://facelessuser.github.io/pymdown-extensions/extensions/details/) and this introduces the same rendering glitch, but shifts it to the overlap excess to the right instead of left (which disabling `overflow: visible` doesn't fix since it's not overflowing from that direction).

The thing is that page is using your `mkdocs-material` AFAIK, the CSS for the component seems to be the same, including `overflow: visible`, but has `display: block` instead of `display: flow-root`, changing this made no difference. Thus whatever is causing it appears to be caused from another layer (it isn't resolved via `z-index`).

I understand that it's not something you can afford to debug and put time into. As I can't reproduce it easily on PyMdown Extensions, I have no idea what CSS difference your site has that creates this bug on a niche user base. The scrollbar bleeding `z-index` bug does affect PyMdown Extensions however.

I'll close this, it's presumably a rendering fault of Firefox on Linux, Android browsers are unaffected.
