### ISSUE TITLE
Code block annotations are misaligned on mobile

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#2475]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

The examples about code block annotations on the [material insider page](https://squidfunk.github.io/mkdocs-material-insiders/reference/code-blocks/#adding-annotations) is misaligned (see image).

![SmartSelect_20210320-072440_Chrome.jpg](https://user-images.githubusercontent.com/11576465/111861559-89aa6780-894f-11eb-9f13-706c5f910b59.jpg)

### Expected behavior

Text should be aligned properly.

### Actual behavior

The text shows up on the right cut off

### Steps to reproduce the bug

1. Go to https://squidfunk.github.io/mkdocs-material-insiders/reference/code-blocks/#adding-annotations
2. Tab on one of the annotations
3. See issue

### Package versions

Since this happens on the live version of the insiders example can I not provide the info.

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: Android 10
* Browser: Google Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! There're still some issues to work out in regards to sizing and alignment on mobile, that's correct. The currently known bugs are:

1. Annotations may sometimes run out-of-screen on mobile (this is the issue reported in the OP)
2. Annotations may be rendered too narrow
3. When scrolling a code block, annotations stay in place and don't follow

I've already implemented an alignment logic, but it seems to still suffer from some issues. Nothing that isn't fixable, but it definitely needs some work on mobile. I'm actually working on a general tooltip alignment solution because I want to expand those annotations/tooltips beyond code blocks, to be peaceable anywhere inside body copy.

Screenshots for issue 2 and 3:

<img width="382" alt="Bildschirmfoto 2021-03-20 um 09 58 14" src="https://user-images.githubusercontent.com/932156/111864750-1dd1fa00-8963-11eb-9d7b-5c61005ecfc9.png">
<img width="382" alt="Bildschirmfoto 2021-03-20 um 09 58 21" src="https://user-images.githubusercontent.com/932156/111864751-20345400-8963-11eb-8072-31f551d46e31.png">

**Comment by squidfunk** [comment]
I've finally tackled the reported issues with code annotations – they now work quite well on mobile:

https://user-images.githubusercontent.com/932156/142776319-9cbfdd0d-69ca-47c9-abf1-231baf0e8578.mp4

The fixes were just released as part of 8.0.0b2. See #3219 for update instructions.

**Comment by squidfunk** [comment]
The fix is now in `master` and will be released shortly.
