### ISSUE TITLE
Advertise keyboard shortcut for search in text box

### ISSUE THREAD

**Issue by weitzman** [squidfunk/mkdocs-material#2574]
## Description

Add a `/` to right hand side of search text input element. 

### Screenshots / Mockups

I got the idea from Stripe docs who style this nicely IMO https://stripe.com/docs/stripe-cli/webhooks

<img width="673" alt="image" src="https://user-images.githubusercontent.com/7740/115113591-21a06e80-9f59-11eb-8add-18688bc5c810.png">

**Comment by weitzman** [comment]
Hey, Github does it too. See this very page!

**Comment by squidfunk** [comment]
Thank for suggesting! Are there patterns out there for shortcuts like prev/next page, i.e. for the [other shortcuts](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts) supported by Material for MkDocs?

**Comment by Stanzilla** [comment]
This is pretty neat, I had done it a bit differently in my fork, I replaced the placeholder text with `Press S to Search`.

**Comment by weitzman** [comment]
The only other pattern I'm aware of is `?` to pull up a modal that lists all available shortcuts. See Github or Gitlab for examples. This was requested in #798.

**Comment by squidfunk** [comment]
@weitzman Jep, that's the one. I'd favor a modal listing all keyboard shortcuts, because it would include all, and not only the search shortcut, but up to now, I haven't found a good way of how to integrate this with user-level [custom keyboard shortcuts](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts) which some people use, as those wouldn't show up in the modal, as described in https://github.com/squidfunk/mkdocs-material/issues/798#issuecomment-599211072. Also, other users like @Stanzilla might favor another canonical key to be displayed as the keyboard shortcut, e.g. `s`of `f`, which both work.

Other than that, what you're aiming for is trivial with some extra CSS, i.e. you could add an `::after` pseudo on the input which contains the slash, for example like this:

```
```

**Comment by weitzman** [comment]
Thanks for that CSS snippet. Alas its not quite working at https://www.drush.org/. Its definitely added to the page via https://www.drush.org/latest/css/extra.drush.css

**Comment by squidfunk** [comment]
Works on my machine:

![screenshot-www-drush-org-latest-1618749348867](https://user-images.githubusercontent.com/932156/115145748-6c061600-a053-11eb-8239-882624321a2e.png)

**Comment by weitzman** [comment]
And now it works on mine. Sorry for the noise.

**Comment by hossain-khan** [comment]
Lovely! Exactly what I needed! 🤩 
Thank you! 🙏🏽
