### ISSUE TITLE
Search displays unrelated links

### ISSUE THREAD

**Issue by ovasquez** [squidfunk/mkdocs-material#262]
## Description

Since the change in the search behavior to highlight the matching words I've noticed a couple of glitches the search:
- Showing all `##` headings in the search results for a document, even if the text is in just one section. 
- Showing documents that don't contain the searched text.

*The image below shows the search showing several `##` headings that don't contain "tabs" (neither in the displayed text or the content).*
![material-mkdocs-1](https://cloud.githubusercontent.com/assets/7527242/24824003/01c180fa-1bc2-11e7-8d00-2fd40bc33cad.png)

*The image below shows a document with no trace of the word "tabs" that is being listed in the search results*
![material-mkdocs-2](https://cloud.githubusercontent.com/assets/7527242/24824029/4726a5b2-1bc2-11e7-9e2f-cc8e02370643.png)

### Expected behavior

The search should show only related subsections of related documents.

### Actual behavior

Search shows all '##' headings for a document in the search results, and sometimes unrelated documents are shown.

### Steps to reproduce the bug

1. Go to the material documentation website
2. Search the word "Tabs"
3. Review the search results

### Package versions

* Python: 3.6.0
* MkDocs: 0.16.3
* Material: 1.5.3

**Comment by squidfunk** [comment]
Two things:

1. lunr.js does stemming by default, so **tabs** is reduced to **tab**, which matches **table** in the Disqus integration section, just as an example. The question is if stemming makes sense here, but this is a general question

2. The highlighting isn't ideal - sometimes the matching word is located later in the text. I would also like to see a summary here like on Google which highlights the matched words, but this gets complex very fast and probably isn't generalizable to all languages. I prototypes something that breaks of the sentence structure and tries to make a summary, but to no extend I think is robust enough. For this reason I decided to do it like this (for now). If you have a good idea or know a library that does summarization in a useful way, feel free to post.

The search functionality is a huge ongoing process. I think it's fairly good now, because the presentation of results is better and results provide more context than for example the readthedocs or mkdocs original theme search. However, I'm happy for input on making it even better.

**Comment by ovasquez** [comment]
I was unaware of the stemming, so that would make the results valid. I understand that showing the chunks of text where the match was found is not currently supported by lunr.js, so it makes sense as it currently is displaying it.

Thanks for the detailed explanation about the search.

**Comment by squidfunk** [comment]
If something better for summarization comes up, I'll definitely include it.
