### ISSUE TITLE
Add support for favicon on iOS Safari

### ISSUE THREAD

**Issue by steam3d** [squidfunk/mkdocs-material#2745]
Favicon is not displayed on IOS (safari), Mac OS (safari).  In chrome it is displayed correctly.

**Comment by squidfunk** [comment]
Thanks for reporting. Could you please add screenshots and provide more information (please follow the issue template) what you mean exactly?

**Comment by steam3d** [comment]
mkdocs.yml
```
...
  logo: media/favicon.svg 
...
```

Chrome (Windows) display favicon
<img src="https://user-images.githubusercontent.com/30986874/121242290-0c82f480-c8a5-11eb-846f-9184fe1b455d.png" width="320">

Safari IOS does not display favicon
<img src="https://user-images.githubusercontent.com/30986874/121242348-1efd2e00-c8a5-11eb-8ca1-57a7705553b0.png" width="320">

**Comment by squidfunk** [comment]
I'm quite amazed that iOS Safari doesn't pick up the favicon. Would you like to work on this in the form of a PR?

**Comment by steam3d** [comment]
I am not sure what is "PR", but i want to help fix this issue

**Comment by martinbira** [comment]
> I am not sure what is "PR", but i want to help fix this issue
It's a "Pull Request".

**Comment by khakers** [comment]
This seems like an issue with iOS SVG Favicon support

https://caniuse.com/link-icon-svg

**Comment by squidfunk** [comment]
@khakers Thanks for clarifying! Partial support doesn't sound like something we should add support for, because favicons are something user-provided and if the requirements are that it "only works for all-black icons on pinned tabs", I think we rather shouldn't go through the troubles and add support for it.

I verified whether non-SVG icons are shown. This installation works on my iPhone, i.e. it shows the favicon:
https://aws.github.io/copilot-cli/

Closing as not fixable.
