### ISSUE TITLE
FontAwesome icons

### ISSUE THREAD

**Issue by brianjking** [squidfunk/mkdocs-material#29]
@squidfunk Do you have a suggested method of using FontAwesome icons with this theme?

I know when I use the ReadTheDocs theme I can use them, however, when I've attempted to implement these using the material theme you've built they simply do not display.

Thanks!

**Comment by squidfunk** [comment]
@brianjking Have you tried adding it via `extra_css`
http://www.mkdocs.org/user-guide/configuration/#extra_css

As FontAwesome is basically just `@font-face` definitions, adding it as an additional stylesheet should do the trick. From then on you should be able to use it the regular way:
https://fortawesome.github.io/Font-Awesome/examples/

I'm actually thinking about including the whole Material Icon set for the next build, because I like it better than FontAwesome, but maybe that's another option for the `mkdocs.yml`. I hope I have some more time to work on it soon. I'm closing this issue for now, as I have this topic on my internal list anyway.
