### ISSUE TITLE
Feature suggestion: Docker image for linux/arm64 

### ISSUE THREAD

**Issue by afritzler** [squidfunk/mkdocs-material#2945]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

### Description

I see in the Github workflows (https://github.com/squidfunk/mkdocs-material/blob/master/.github/workflows/publish.yml#L89) that the `linux/arm64` image build is commented out. Are there any plans to release `arm64` anytime in the future?

### Use Cases

I would like to use the `mkdocs-material` Docker images as a baseimage in my local development environment on an Apple Silicon.

**Comment by squidfunk** [comment]
Thanks for suggesting. With Apple's new M1 chip gaining more widespread adoption, `arm64` is definitely something to consider supporting.

> I see in the Github workflows [...] that the linux/arm64 image build is commented out

I tried to make the build work with `arm64`, but I wasn't successful, yet. It's currently not a priority for me, but if you wish to add support, I'll appreciate a fully functional PR, which adds the necessary steps to the GitHub Action. You could fork the repository and debug the GitHub Action.

Note that this is something I cannot maintain in the future, since I'm not a consumer (I don't have an M1 MacBook), so it would be necessary that you would be available for maintenance, i.e. when the build breaks. For compatibility, I'd suggest moving the `arm64` build into a separate GitHub action which is triggered on release, because it shouldn't break the `x86_64` build.

**Comment by afritzler** [comment]
Let me block some time to see if I can get this working end-to-end. 

As a workaround for the moment (in case anybody is facing the same problem) build a local image on your Macbook M1:
```
git clone https://github.com/squidfunk/mkdocs-material.git
cd mkdocs-material
docker build -t squidfunk/mkdocs-material:7.2.4 .
```

**Comment by squidfunk** [comment]
https://github.com/valkmit/aws-graviton2-on-intel

This is trending on HN right now. My testing with QEMU showed that it was painfully slow, so maybe this can be leveraged to build ARM Docker images faster.

**Comment by squidfunk** [comment]
I‘m closing this issue for housekeeping. There haven’t been any reactions by others which somehow suggests that currently there’s no need to prioritize this. If somebody wants to craft a PR which adds support, I’m happy to discuss.

**Comment by squidfunk** [comment]
Thanks! This answers the question in https://github.com/squidfunk/mkdocs-material/pull/3034#issuecomment-921908053. Actually, it's not feasible to wait for 8 minutes for the ARM image to build, as this will make the build cycle much much longer, eating up more of my time. Can we somehow factor this out into a separate GitHub action that runs independently of the `x86_64` build?

**Comment by afritzler** [comment]
That would be an option. Let me try this out on my fork first.

**Comment by afritzler** [comment]
Ok, having a separat build and push action just for the ARM images has a nasty side effect: https://github.com/afritzler/mkdocs-material/pkgs/container/mkdocs-material 

It seems to overwrite the `linux/amd64` arch image 🙈

**Comment by squidfunk** [comment]
Thanks for investigating! And ... meh. Under these circumstances, I'm not considering moving this build action into this repository, because a time increase of 800% ([usual Docker build takes 1m +. a few seconds](https://github.com/squidfunk/mkdocs-material/runs/3488531186?check_suite_focus=true)) is kind of a deal-breaker here. Any other options? From the top of my head:

1. A separate repository + registry (maintained by you?)
2. We add a note to the docs on how to build the ARM image from source

Additionally, I can't maintain it (currently don't have an ARM machine at my disposal), so any errors would have to be community contributions. For this reason option 1 is definitely a better choice than me being the gatekeeper here. We could add a note to the docs that the ARM image is hosted under a separate registry.
