### ISSUE TITLE
Feature suggestion: allow font-size adjustments to social card titles

### ISSUE THREAD

**Issue by zhyatt** [squidfunk/mkdocs-material#2974]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When the length of a title on a page results in 3 lines of text on the card needed (ex. "Block confirmation tracking"), the last line of text gets partially cut off. This change feels more like the exception than the rule so a single site-wide change doesn't feel appropriate to me. Perhaps allowing the use of meta data on pages to change the title size as needed is an option.

### Use Cases

This would allow more flexibility for adjusting social card presentation in order to fit different size titles.

### Screenshots / Mockups

<img width="1195" alt="Screen Shot 2021-08-25 at 8 30 45 AM" src="https://user-images.githubusercontent.com/2311564/130820029-ac8667a4-bbf2-4ad8-870b-1b03afde3ebe.png">

**Comment by squidfunk** [comment]
Thanks for reporting. There are still some cases to consider for the social cards preview images, as some fonts have larger heights than Roboto (which seems to be the case here). I'd say that the height should be self-adjusting so that the user doesn't have to do anything, but I have to invest some time to see whether this is possible with a reasonable amount of effort.

I'll try to come up with a solution when I manage to find the time to work on this feature again.

**Comment by squidfunk** [comment]
Fixed in [`8fb42f306`](https://github.com/squidfunk/mkdocs-material-insiders/commit/8fb42f306eb4b41e7f752b63f01d136f28812be3).

Before introducing more options for font-sizes etc, I've decided to make the default more consistent. Social cards will receive more configuration options, maybe even custom layouts in the future. However, for this to work, I need to rethink how to handle text boxes more elastically. The problem reported was originating from different ascent and descent values of fonts. I've done my best to normalize the spacing for now, which should now lead to more consistent rendering across different fonts. Noto Sans (which you used) and Roboto are good to compare, as they are pretty different:

__Noto Sans__

![index](https://user-images.githubusercontent.com/932156/137632944-9735b97a-634d-48b8-9903-3ddd1ebb1306.png)

__Roboto__

![index-6](https://user-images.githubusercontent.com/932156/137632945-679a97ea-b724-4162-98af-6bbeaa2e2de4.png)

If you overlay both images, you'll see that lines are now evenly spaced, i.e. they start at the same vertical offsets. This ensures that nothing gets cut off vertically. For now, font sizes cannot be set explicitly, but I'll consider this in the future. Other things to be addressed in the future:

- Better handling of long titles: either handle with ellipsis, or shrink-to-fit font size
- Custom positioning, spacing, etc.

**Comment by squidfunk** [comment]
Released as part of 7.3.4+insiders-3.1.4

**Comment by yrashk** [comment]
It feels like I need dynamic font sizing as it just tends to cut off the title, sometimes changing its meaning:

![image](https://user-images.githubusercontent.com/452/230809875-a0848fb2-3a80-44e8-bdbf-9b35ca3e5704.png)

Where the title is actually this:

# [Avoiding Postgres Extensions Limitations](https://yrashk.com/blog/2023/04/10/avoiding-postgres-extensions-limitations/#avoiding-postgres-extensions-limitations)

**Comment by squidfunk** [comment]
Thanks! I have a working prototype with automatic font sizing, just need to finish it 😀 Social cards will get an update soon.

**Comment by yrashk** [comment]
I am super eager to try it out, as people have already noticed the problem! https://twitter.com/diggya/status/1645280932557905920

**Comment by squidfunk** [comment]
Awesome! I expect it to hit the shelves later this year, as I'm currently focusing on [re-architecting the search](https://twitter.com/squidfunk/status/1645023533724991489) – there are so many open change requests regarding search that need to be handled first 😅
