### ISSUE TITLE
extra.css color guide

### ISSUE THREAD

**Issue by GL513** [squidfunk/mkdocs-material#2987]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The extra.css' current "guide" is very vague. It tells you very little about what variable is for which thing.
Making a guide that quickly and easily describes which variables go where would make things much easier for people who want custom colors.
I ran into a problem where I am frantically typing in every variable. I am currently still in the process of doing that. 
Really all that would need to be done is add a comment that is above every variable in the [Color Definitions Guide](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss) that is descriptive of the locations of the item so users know what that color is assigned to.

### Use Cases

This would help with the problem of unknowledgeable mkdocs Material users so we can make our sites quickly and easily, and help other users feel less intimidated to use the extra.css, so they can use the extra.css.

### Screenshots / Mockups

//  Primary Header (largest header) color. 
  --md-default-fg-color--light: #000;

**Comment by squidfunk** [comment]
Thanks for suggesting. A PR is appreciated!

**Comment by squidfunk** [comment]
To expand on my brevity (was on my mobile): listing all usages of each color variable is probably not a very good idea, because we would have to remember to update it whenever we use a CSS color variable – two entirely unrelated places. The [color customization guide](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors) gives an example with a custom primary color and already links to the SCSS file containing all definitions. A better place  than the documentation would be to expand on the comments in the definitions file, i.e. here:

https://github.com/squidfunk/mkdocs-material/blob/6b5035f5580f97532d664e3d1babf5f320e88ee9/src/assets/stylesheets/main/_colors.scss#L27-L107

IMHO, we should definitely keep the block structure and not describe each and every variable on its own, because when you change a color in one of those blocks, you might need to changes others as well. As those definitions are co-located, it's easier to not forget related definitions.

I would be curious if the custom color guide I linked above actually already solves your problem.

**Comment by GL513** [comment]
Hey. I completely understand not wanting to change blocks. After doing a few of my own small projects, I had to basically rename everything, along with their values, so I get it.
Unfortunately, the document you linked wasn't very helpful. That was actually the one I hyperlinked in the description! 
Thanks for your acknowledgement. 
If you want any more feedback, I could point you to a small community I know. They have their sites hosted with your Material theme, so they would know what they think should be done a lot more than I would, since I haven't even finished my site yet.
If you happen to know off of the top of your head, which variables are for the background, in general, and for the text color, if there are any?

**Comment by squidfunk** [comment]
Thanks for getting back.

> If you want any more feedback, I could point you to a small community I know. They have their sites hosted with your Material theme, so they would know what they think should be done a lot more than I would, since I haven't even finished my site yet.

Thanks for the offer. However, I currently have too much on my plate to make room for working on customization documentation, so I'd appreciate a PR as already mentioned. The PR could extend the inline code comments to include an excerpt of the elements it is used for. However, I'm not a fan of adding too much prose, because it will become outdated, so keep it concise and short is key.

> If you happen to know off of the top of your head, which variables are for the background, in general, and for the text color, if there are any?

- `*-default-*` variables are used as foreground and background colors (dark mode is inverted)
- `*-primary-*` variables are used for everything that receives the [primary color](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color), including but not limited to the header, sidebar, and content tabs.
- `*-accent-*` variables are used for everything that receives the [accent color|(https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color), including but not limited to hovered links and other elements

Most of the other variables derive from those values. For a more concise listing, I'd recommend searching the code and understanding how those variables are used.

**Comment by remipregh** [comment]
Hi @squidfunk,
I'm also trying to get customed colors and have modified the _colors.scss file as you mentioned.
However, when I compile the scss file, I've got an error because the compiler cannot find the following dependencies:

``` css
@import "material-color";
@import "material-shadows";
```

These .scsss file are not in the repo. Is it normal?
If I comment them out, I've got another error on https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/utilities/_convert.scss#L33 as `$number`  isn’t defined.

Am I doing something wrong? It is Monday morning after all :)

Thanks!

**Comment by squidfunk** [comment]
@remipregh sounds like you're missing an `npm install`. You don't need to change the actual source of the theme, you can just use [extra CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css). If you do use the source, make sure to follow the [theme development setup guide](https://squidfunk.github.io/mkdocs-material/customization/#theme-development).

**Comment by GL513** [comment]
hey, wanted to respond sooner, but i was wrapped up with my own stuff.

> Thanks for the offer. However, I currently have too much on my plate to make room for working on customization documentation, so I'd appreciate a PR as already mentioned.

not quite sure what you mean by PR. Im sure i could get it to you whatever it is lol.

**Comment by facelessuser** [comment]
He means [Pull Request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) (PR). He is suggesting that you'd fork the repository, make the changes, commit them to your fork, and then issue a PR that would request him to merge those changes into his repository.

I'm not how sure how familiar you are with using git and such tasks, but that is what he was requesting.

**Comment by GL513** [comment]
Ah yeah, I know what a pull request is, I just never heard it said as PR.
Thanks.

**Comment by squidfunk** [comment]
I'm closing this, as there's no further actionable here. If somebody wishes to improve the documentation, a PR is appreciated and we can discuss concrete improvements over in the respective PR.
