### ISSUE TITLE
Suggestion: outlined ToC

### ISSUE THREAD

**Issue by CAFxX** [squidfunk/mkdocs-material#3059]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I would like to suggest providing an option (off by default to maintain current behavior) that replaces the ToC that is currently embedded in each page with a client-side embedding, e.g. via an iframe or content injection via js.

Basically, when the option is turned on, instead of having:

```
<html>
  <head>...</head>
  <body>
    <header>...</header>
    <main>
      <div id=site_toc>...</div>
      <div id=page_toc>...</div>
	  <div id=page_content>...</div>
    </main>
  </body>
</html>
```

we could have something like:

```
<html>
  <head>...</head>
  <body>
    <header>...</header>
    <main>
      <iframe id=site_toc src="/site_toc.html#<pageid>"></iframe>
      <div id=page_toc>...</div>
	  <div id=page_content>...</div>
    </main>
  </body>
</html>
```

where `site_toc.html` is the outlined site ToC, and `pageid` is the id of the current page in the toc, so that a bit of JS in the iframe can expand the tree and focus the appropriate page

### Use Cases

When a mkdocs site starts to have a sizable number of pages, the site ToC that is embedded in every page can start to significantly outweigh the content of each page. In our internal doc site most of our pages are now in the 100KB+ uncompressed range (15-20KB compressed), with the site ToC itself using 90KB+ on each page.

In addition to being wasteful in terms of bandwidth per page transmitted, having the ToC statically embedded in every page also causes invalidation of every cached version of the page every time a page is added, removed, renamed or moved anywhere on the site.

If the ToC was not statically embedded in each page, pages would significantly shrink in size and caching would be more effective.

**Comment by squidfunk** [comment]
Thanks for suggesting. The problem with moving navigation into an `iframe` is that we would now have to render a single navigation structure for all pages, which means we must somehow replicate the different renderings (e.g. "active" state) in JavaScript. This would be a significant deviation from the current theme implementation, and since the navigation partial is pretty complex, I really don't want to go down that path. Thus, I'm not considering this proposal for implementation.

There is a similar discussion in #1887, and a proposed solution in https://github.com/squidfunk/mkdocs-material/issues/1887#issuecomment-904455585, which I find to be a better approach, as it's easier to implement. This might find its way into the theme at some point in the future, but for the time being, you can extend the theme and adopt the proposed solution.

**Comment by CAFxX** [comment]
Just to clarify, this means that even if someone sent in a change implementing this it would not be considered/reviewed at all?

**Comment by squidfunk** [comment]
> Just to clarify, this means that even if someone sent in a change implementing what is proposed above, the PR would not be considered/reviewed at all?

That's correct. The reason for this decision is that after the change has been merged and the PR's author has moved on, it's me who has to maintain it. Material for MkDocs has so many features for which I need to make sure that they work with this proposed change, that I'm not able to take the responsibility for this. Furthermore, this change might hinder future developments in a way I cannot foresee. It's too risky.

__Recommended read: #2399__

Nonetheless, this project always aims to be hackable and extensible, so adding it yourself, or implementing a plugin that adds this functionality is a good option. This way, maintenance could be outsourced to somebody willing to do the work and maintenance. There are several examples of plugins that extend the functionality of MkDocs in general or Material for MkDocs in particular. Furthermore, from my understanding, this would need to be implemented as a plugin, because a new file that is outside of the documentation tree, but dependent on the navigation hierarchy needs to be generated.

**Comment by CAFxX** [comment]
OK, got it. I'm a bit surprised at the "too risky" since the PR and its impact can't actually be assessed right now, but I certainly respect maintainers' decisions on such matters. Just wanted to make sure to avoid wasting time contributing something that wouldn't even be looked at.
