### ISSUE TITLE
Make social cards a valid configuration for non-Insiders

### ISSUE THREAD

**Issue by PEZ** [squidfunk/mkdocs-material#3178]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Right now [social cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/) are an Insiders only feature and it makes the site build crash if referenced in the MkDocs config. I'd like it to be a valid configuration, even if it doesn't do the actual work when used with regular mkdocs-material.

### Use Cases

Social cards are mostly only relevant for public sites. So to build it in CI makes perfect sense. And there the github-token can stay secret. But we don't want to spread insiders around and certainly not access tokens, just for the contributors to a project to be able to work with its documentation.

**Comment by squidfunk** [comment]
So I thought about this a little, and the problem lies within the fact that there might be plugins with the same name that we want to keep installable. There currently is no third-party `social` plugin, but there's a third-party `tags` plugin. This means that we cannot simply provide dummy plugins (= hulls), because we would make other plugins non-installable 😐 I guess the best option is to use [configuration inheritance](https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance), putting all common settings in a base configuration and add the `plugins` section in two separate configurations, one for CI, and one for the common clone.

**Comment by squidfunk** [comment]
[Configuration inheritance](https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance) is definitely the way to go. While Insiders strives to be downward-compatible, it's not possible with custom plugins. As stated, we can't provide empty hulls, as this would make installing third-party plugins with the same name more difficult (e.g. the [tags](https://github.com/jldiaz/mkdocs-plugin-tags) plugin). For this reason, a second YAML file should introduce plugin options for Insiders:

`mkdocs.yml`

``` yaml
site_name: My docs
theme:
  name: material
plugins:
  - search
```

`mkdocs.insiders.yml`

``` yaml
INHERIT: mkdocs.yml
plugins:
  - search
  - social
  - tags
```

Then, in CI or when Insiders is available, you can use `mkdocs build -f mkdocs.insiders.yml`. I'm working on the Insiders documentation today, so I'll add the same to the documentation.

**Comment by squidfunk** [comment]
This is now documented here:
https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins

**Comment by PEZ** [comment]
Awesome. I'll try the instructions.
