### ISSUE TITLE
[FR] Use section name as the title of index page

### ISSUE THREAD

**Issue by jaklan** [squidfunk/mkdocs-material#3181]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Section index pages are named simply `Index`:
![image](https://user-images.githubusercontent.com/24907857/140257928-ae2b49d5-9379-4241-a85d-94f6ade8c68b.png)

When using e.g. [mkdocs-section-index](https://github.com/oprypin/mkdocs-section-index) plugin, the title is taken from the section name:
![image](https://user-images.githubusercontent.com/24907857/140257944-fbc82121-586d-41fe-a016-e3a18944fa70.png)

Imho the latter approach is much more intuitive.

### Use Cases

As described above. Such auto-generated title should be still possible to overwrite with H1 header in given `index.md` / `README.md` file.

**Comment by squidfunk** [comment]
Thanks for suggesting. As you didn't provide any Markdown, I assume you're not having the main headlines in your Markdown files. Material for MkDocs will add them automatically, which is why the title of the page is used. Since you didn't specify one, the name of the file is used and title-cased. The section index plugin post-processes the navigation tree and automatically adds the title of the section to the page. Since Material for MkDocs doesn't do any post-processing on the navigation tree, there's no way we can set the title automatically.

I encourage you to use the section index plugin if this is your use case.

**Comment by luchaoqi** [comment]
@jaklan Same problem here, have you solved this problem? I was using mkdocs-section-index before but seems they have some problems too in recent releases.

**Comment by alexvoss** [comment]
If I understand the comment by squidfunk correctly, there is nothing to fix from the side of Material for MkDocs. Can you be specific about what problems there are with the section-index plugin? I set up a small test project and it seems to work as intended.

**Comment by alexvoss** [comment]
I do note there seems to be a [bad interaction between Material for MkDocs, the i18n-static plugin and section-index](https://github.com/oprypin/mkdocs-section-index/issues/15). Is that the issue you are referring to?

**Comment by luchaoqi** [comment]
nvm, seems they fixed it in the recent versions. mkdocs-section-index updates pretty frequently in recent weeks.
