### ISSUE TITLE
Enhanced 404-Not-Found Page

### ISSUE THREAD

**Issue by jhendricks123** [squidfunk/mkdocs-material#3234]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

As documentation sites age, sometimes they get restructured and URL's once shared on external sites, social media, or in emails may end up leading users to a "404 not found" page.

The URL path can offer hints about what the user was hoping to find, so instead of a plain 404 page, you could inform the user the page no longer exists, and then use the built-in search feature to present the user with links to matching pages.

### Use Cases

Dead links and custom 404 pages are very common. I think nearly everyone running the material theme with the search feature enabled could benefit from a dynamic 404 page.

### Screenshots / Mockups

![2021-11-18 16_12_01-Window](https://user-images.githubusercontent.com/7669972/142516950-87df7d40-9d8c-4cb8-bdf2-861bd2e8c7fb.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. It's a pretty nifty idea I haven't seen anywhere yet. However, it would mean substantial effort, because we somehow would have to detach the search result functionality. It's certainly possible, but it's currently not a priority because I believe the impact of this is rather low – at least lower than other features on the list. In order to avoid 404 pages, I recommend using the [mkdocs-redirects](https://github.com/datarobot/mkdocs-redirects) plugin – it's what I'm using on the documentation as well when I rename pages.

**Comment by squidfunk** [comment]
Closing for housekeeping for the reasons stated. The `redirects` plugin is the way to go.

**Comment by squidfunk** [comment]
Addendum: this could actually be implemented **within the search** with the help of the search deep linking functionality and some additional JavaScript. I believe it might be rather weird with the search opening immediately, but it's at least achievable. On the 404 page, you just would need to grab the URL, split it and then put that into the search, e.g.:

``` js
const query = location.pathname.split(/[/-]|%20/g)
location.href = "?q=" + query.join("+")
```
