### ISSUE TITLE
wordcut, a 662kb Thai hyphenation file is automatically included

### ISSUE THREAD

**Issue by matthewdeanmartin** [squidfunk/mkdocs-material#3259]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

wordcut.js, a 662kb Thai is automatically included. This trips the "large file checks" on my org's pre-commit policies. Including files to support every language is already bloat, but including entire dictionaries is bad bloat. If this were good, then why not include dictionaries for all languages in the world.

### Use Cases

I want to be able to commit my site folder to github w/o changing my maximum file size policy (the policy is good, we don't want jr devs checking in TB file into git, since git makes it hard to remove large files)

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, all files of [this folder](https://github.com/squidfunk/mkdocs-material/tree/master/material/assets/javascripts/lunr) are part of the theme, and thus always copied to the `site` directory. However, the files are only loaded when necessary, i.e. only when `th` is set as a language, so there is _no runtime penalty_:

https://github.com/squidfunk/mkdocs-material/blob/05440550509097f81cec8274c461fe29b0c12a95/src/assets/javascripts/integrations/search/worker/main/index.ts#L101-L105

It's not ideal that those files are copied anyway, yes, but from a theme standpoint we can't do anything about it without losing the ease of use that we currently have. The only option would be for the author to explicitly provide the file, which would mean more problems for authors as many of the users of this project are non-technical.

Material for MkDocs strives to be easy to use, which is why we do a lot of stuff automatically. You're calling it "bloated", but the entirety of the `assets` folder weighs 1,1MB, which is very reasonable. Thus, I have no intention to change this behavior.

**Comment by squidfunk** [comment]
On a side note: https://twitter.com/squidfunk/status/1421395401928843274
