### ISSUE TITLE
8.0.0 regression: no pdf link

### ISSUE THREAD

**Issue by fottsia** [squidfunk/mkdocs-material#3264]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After updating ltsp.org to mkdocs-material 8.0.0, the download pdf link isn't there, even though the ltsp.org/ltsp.pdf is.

### Expected behaviour

The link should be there.

### Actual behaviour

The link isn't.

### Steps to reproduce

Build a site with 8.0.0.

### Package versions

- Material: 8.0.0

### Configuration

```yaml
...
```

### System information

- Operating system: github pages.

**Comment by squidfunk** [comment]
Thanks for reporting. As already said on Gitter – Material for MkDocs includes no PDF functionality, so you're likely using either a plugin or theme extension. Please check with both. Since this functionality is external, I'm not able to reproduce it.

Please see the upgrade guide for further information, as the templates have changed a little: 
https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-7x-to-8x
