### ISSUE TITLE
Feature suggestion: Text annotations (outside code blocks)

### ISSUE THREAD

**Issue by aborruso** [squidfunk/mkdocs-material#3282]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The 8.0 [code annotation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=anno#code-annotations) feature is really great.

I think it would be useful to have it also in "normal" text.

### Use Cases

Sometimes I need something more that foot annotations or abbreviations to explode a concept, remaining in the part of the text I am reading.

Code annotations works really great, and it would work well for text too.

**Comment by cirospat** [comment]
I think that a "`text annotation`" feature is of great value for documentation projects.

**My needs**
For example, ... sometimes I have to provide the definition of an acronym in a text or in a table.
Or I have to give a short definition that I want to keep out of the text I am writing.
For this reason I think a text & table annotation could be useful within my documentation project.

Thanks for reading

**Comment by cirospat** [comment]
I tryed the `Adding abbreviation` feature.

I noticed that the `Adding abbreviations` function on mobile devices is a little bit inconvenient because it is all on one line unlike `Code annotation` which goes on several lines adapting perfectly to the display size.

I attach 2 screenshot of my smartphone

**`Adding abbreviation`** 
↓
![image](https://user-images.githubusercontent.com/3757525/144209374-b5089f61-7426-4d25-ab00-1687b7251251.png)

**`Code annotation`** 
↓
![image](https://user-images.githubusercontent.com/3757525/144210022-814346e7-fa4e-4e6d-b5a8-923f8c1fa37a.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm exploring several ways to add further information to normal text, so it's definitely something I'm working on right now. The main problem is to think of a Markdown syntax that also works when JavaScript is not available. For code annotations, the contents are just rendered below in a numbered list, which means it degrades gracefully. I've no idea yet how this could work from a Markdown perspective. Maybe use the footnotes plugin, but then you would also want to have footnotes, so it would be kind of mixed.

I'm leaving this open with need for further investigation.

**Comment by squidfunk** [comment]
I've got a working prototype:

- Annotations use the footnotes syntax, as it feels quite natural to use
- Annotations are rendered as regular footnotes when printing
- Annotations can have custom labels
- Annotations can be rendered anywhere where Markdown is allowed
- Annotations use the same positioning techniques as code annotations
- Annotations can be freely combined with code annotations

https://user-images.githubusercontent.com/932156/144750473-7b3188ff-b525-4843-8496-c82ed8147dfd.mp4

Code used in the demo:

```` markdown
Admonitions, also known as _call-outs_, are an excellent choice for including
side content without significantly interrupting the document flow. Material for
MkDocs provides [^1] several different types of admonitions and allows for the
inclusion and nesting of arbitrary content.[^show graph]

  [^1]: small annotation

  [^show graph]:
    Here's a graph:

    ``` mermaid
    graph LR
      A[Start] --> B{Error?};
      B -->|Yes| C[Hmm...];
      C --> D[Debug];
      D --> B;
      B ---->|No| E[Yay!];
    ```
````

**Comment by aborruso** [comment]
wow, really wonderful @squidfunk 

thank you very much

**Comment by cirospat** [comment]
amazing @squidfunk !
I'm so happy about your prototype.
I'm looking forward to use it...!
And thank very much for your precious time spent on it

**Comment by Stephen-Gates** [comment]
This is a great feature. As a stretch, could this be applied to images to improve captions, e.g. 

- provide a caption 
- link to the source
- show attribution and licence

<img width="280" alt="image-with-annotation" src="https://user-images.githubusercontent.com/9379524/145101515-08cb8713-1450-4104-b3c8-43666df28dec.png">

**Comment by squidfunk** [comment]
Not in the first instance, maybe later. They can be positioned anywhere in plain text. I'm not sure images are a good fit. You can open a discussion if you like, so we can collect some opinions and ideas on whether annotating images is a thing that users would need. If this is the case, I could investigate it.

**Comment by squidfunk** [comment]
So I'm thinking of ditching the footnotes syntax for something simpler, because it's pretty impossible to reliably use footnotes together with code annotations then. Another idea would be to just use the same syntax as for code blocks, namely adding the `.annotate` class to a paragraph that should be annotated, or enabling it globally. The syntax could be:

``` markdown
This is a paragraph with some (1) annotations (2)
{ .annotate }

1. Hey, I'm a text annotation!
2. Me too!
```

__Pros__:

- Syntax is identical to code annotations
- Printing is still possible, as behavior is identical to code annotations – markers are just kept untouched and the list is rendered below the paragraph as a normal ordered list.
- Footnotes are not impacted and can be used as usual

__Cons__:

- As with code annotations, only numeric markers are allowed, no markers (like in the demo `show graph`)
- Annotations are defined per-block, so numbering would restart each block

I'm actually thinking of ditching the number scheme altogether and switch to a `+` sign which shows how to expand an annotation. When an annotation is open, the `+` sign could be rotated by 45deg to signal to the user that it can be closed with another click on the marker (which is a new feature since 8.0.0). That's kind of nice. I'm also working on making annotations targettable via anchor links, so if followed, the annotation is opened immediately. This would mean that you can share annotations right away, and don't have to explain to your user to "go to code block X and open annotation Y"

Note that this is heavily work in progress, so things are subject to change.

**Comment by cirospat** [comment]
Hi @squidfunk 
> _Note that this is heavily work in progress, so things are subject to change_.

I just have to thank you so much for the work you have undertaken to achieve this goal.
I read your replies here with a mix of curiosity and hunger for knowledge.

Your proposal  `{ .annotate }`
```
This is a paragraph with some (1) annotations (2)
{ .annotate }

1. Hey, I'm a text annotation!
2. Me too!

```
could be easy to manage for editors.


But switch to a `+` sign could be also a solution easy to manage.

When I write text in a block, if the reader finds a  **`+`**  sign or a  **`number`** , both methods help the reader better understand the meaning of the text. 
I think that one of the most important thing is to find a solution easy to manage for editor during text editing.

My 2 cents opinion

**Comment by squidfunk** [comment]
Thanks for your input! The `+` was meant only for the rendering of the code annotations. The syntax would still be numbers, but the code annotation would not render as a number but with a `+`:

__Closed__

![Bildschirmfoto 2021-12-09 um 13 38 16](https://user-images.githubusercontent.com/932156/145398182-1da9fea3-85fb-419c-ba63-efc33d9a8523.jpg)

__Open__

![Bildschirmfoto 2021-12-09 um 13 38 00](https://user-images.githubusercontent.com/932156/145398213-1315cbf9-32d5-40f7-bd44-8db89a9aa14f.jpg)

**Comment by squidfunk** [comment]
__Insiders 4.6.0 brings support for adding annotations outside of code blocks__, so basically everywhere. They work exactly as code annotations and can be mixed with each other, nested, and so on. Check out the new reference manual on annotations here: https://squidfunk.github.io/mkdocs-material/reference/annotations/

**Comment by aborruso** [comment]
@squidfunk  glad I contributed to an insider idea

**Comment by squidfunk** [comment]
Yeah, thanks for the inspiration! I think it turned out pretty great 😊

**Comment by cirospat** [comment]
@squidfunk I'm happy that the feature of **text annotation** is available, even if only for insiders.
I ask if you have already planned to release this feature also for non insiders in the near future.
Thank you very much

**Comment by squidfunk** [comment]
@cirospat of course! When the [funding goal](https://squidfunk.github.io/mkdocs-material/insiders/#12000-piri-piri) is reached, annotations will be available in the non-Insiders edition, exactly like the other [23 features](https://squidfunk.github.io/mkdocs-material/insiders/#goals-completed) that were previously exclusively available in Insiders.

**Comment by cirospat** [comment]
ok @squidfunk 
thank you for the details
