### ISSUE TITLE
Feature suggestion: Blog

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#3353]
I've been thinking on and off about blog support and think it is ready to be tackled. I want to provide native blog support for Material for MkDocs, which can be used just as easily as the overall project. Before I start implementing, I want to collect some ideas and requirements, so that we can gravitate towards a solution that ticks as many boxes as possible.

__Collected ideas__ (checked means implemented)

- [x] Auto-generate blog index page and article pages @squidfunk
- [x] Auto-generate archive index pages with chronologically sorted posts @hellt
- [x] Auto-generate final URL from date (format can be changed) + title @squidfunk
- [x] Provide a pagination of the index page @squidfunk
- [x] Integrate with the [built-in tags plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/) @squidfunk, @hellt
- [x] Allow to provide author information that is automatically rendered @squidfunk, @hellt, @ben519
- [x] Allow to provide static pages alongside articles @squidfunk
- [x] Allow authors to easily override/extend templates @squidfunk
- [x] Allow for completely flexible structuring of blog posts @Andre601, @timvink
- [x] Allow to disable prev/next (use [front matter](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#custom-copyright) + [built-in meta plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin)) @Andre601 
- [x] Allow for lightbox/gallery integration (use [lightbox integration](https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox)) @Andre601 
- [x] Allow to broadcast notifications (use [RSS plugin](https://guts.github.io/mkdocs-rss-plugin/)) @mfridman, @sheldonhull, @Andre601 
- [x] Allow for multiple authors per post @shokinn
- [x] Allow to mark posts as drafts @dcode
- [x] Allow to automatically mark posts as drafts if they have a future date @dcode
- [x] Allow for automatically estimated reading time @hellt
- [x] Allow for standalone blog @sheldonhull
- [x] Allow for defining custom slug schemes @sheldonhull
- [x] Allow for overriding slugs per post @sheldonhull
- [x] Allow blog posts to be assigned to categories @Andre601 
- [x] Allow default settings per category (use [built-in meta plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin)) @Andre601 
- [x] Auto-generated category index pages @Andre601
- [x] Allow to disable table of content in blog post (use [front matter](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars) + [built-in meta plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin)) @birdybro
- [x] Allow flexible naming for source files @SilentGlasses
- [x] Allow to easily migrate from other blog solutions @Realvincentyuan

__Possibly implementable__

- [ ] Add share-out links to share a post on social media @mfridman, @eyllanesc, @ben519
- [ ] Allow for combining blog posts into series @eyllanesc
- [ ] Allow to generate a post overview per author @shokinn
- [ ] Expose latest posts via template variables @timvink, @kcgthb 

__Possibly not going to be implemented__

- [ ] Allow to upvote blog posts – unclear how this should be persisted @LuciferUchiha
- [ ] Allow for sourcing blog posts from GitHub issues @sheldonhull
- [ ] Allow for configurable prev/next buttons in the footer @ben519
- [ ] Allow to segregate blog search results from documentation @birdybro 
- [ ] Faster builds (this is an upstream MkDocs issue) @Realvincentyuan

__Feel free to leave further input in the comments__

- What navigation and directory structure would you expect from a blog?
- What pages besides the index page do you need? Archive? Tags?
- How would you write a new blog article, i.e., what's the expected DX?
- ... anything else that's on your mind

**Comment by Andre601** [comment]
When it comes down to structure would I prefer a way to define one or even multiple sources for where your articles are located (with or without recursive lookup), but if a more firm, rigid structure is wanted, then I would go with `/:year/:month/:article.html` rather than `/:year/:month/:day/:article.html` as not everyone writes 10 different articles a day.

Also, one thing I feel like would be good is to perhaps override the nav in the footer to show other blog articles a la "You may be interested in those..." rather than a simple "previous post, next post" solution.
I saw this a lot on other blogs, and I kinda like the idea of it, especially when the recommended articles would be based on factors such as tags shared with the main article.

Also, native lightbox support (Enlarging images) would for sure be a must-have for any proper blog setup, as the images are sometimes really small and the current solution of including the [Lightgallery Markdown](https://github.com/g-provost/lightgallery-markdown) is imo a rather hacky aproach.

**Comment by timvink** [comment]
This would be awesome and make the MkDocs system even more powerful. I use MkDocs quite a lot for documentation, but my personal blog is jekyll-based.

The main reason I haven't switched yet is because I want to embed my blog into my personal website, which is more than just a blog. Basically it's this functionality (copied from [their docs](https://jekyllrb.com/docs/posts/#displaying-an-index-of-posts)):

```jinja2
<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
```

That way I can insert, for example, the 3 latest posts somewhere on my homepage. We might be able to do something similar, where you include an HTML file with some jinja2 syntax in your MkDocs site, and have a plugin add the extra context to the mkdocs jinja2 environment. I haven't explored this before, it might already be possible (in which case it isn't obvious enough for users).

**Structure**

I like jekyll's convention of putting posts in `_posts` ([link to docs](https://jekyllrb.com/docs/posts/#the-posts-folder)), but any directory structure could work. Having a look at [jekyll-import](https://import.jekyllrb.com/docs/home/) might be interesting, and perhaps something similar for mkdocs would help increase adoption. 

Using frontmatter for things like tags, categories, permalinks, dates, authors etc works great ([docs](https://jekyllrb.com/docs/front-matter/))

**Documentation**

There are already quite some mkdocs components out there that combined work well for a blog. Properly documenting and demonstrating the use case for blogging is going to be important for adoption. While we're at it, we can document other use cases as well (technical report, python package, personal site, git-based wiki, etc). And yes, that could be a great way to showcase a whole range most-used of plugins ;)

**Comment by kcgthb** [comment]
It would be awesome to have some sort of widget to give readers a visual clue that a new blog entry has been posted.
Ideally that could be embedded on third-party sites, although I fully realize that would be out of scope. But I'm thinking about widgets like [this](https://headwayapp.co/#widget-and-page), or [that](https://announcekit.app/widgets). 

The ability to broadcast new posts and send notifications via RSS, Twitter, or Slack would be the cherry on top. :)

**Comment by LuciferUchiha** [comment]
It would be cool if blog posts, could be liked, or upvoted, to then allow a sorting by most popular.

**Comment by squidfunk** [comment]
@LuciferUchiha thanks for your suggestion! Any idea where we could store the data? Remember that Material for MkDocs will generate a static site, so without third-party services, there's no dynamicity.

**Comment by hellt** [comment]
@squidfunk integration via github issue could be a very easy/viable option. Same emojis can be used.

**Comment by hellt** [comment]
Things I wanted mkdocs-material-blog to have above the mentioned ones:

1. searchable tags
2. archive page will all posts chronologically ordered
3. support for an author profile that can be linked via meta tags. An author summary is then presented on a post page in the header/footer.
4. read time estimation

**Comment by Andre601** [comment]
> @squidfunk integration via github issue could be a very easy/viable option. Same emojis can be used.

I feel like using issues for that would be bad, mainly because issues serve different purposes.
But perhaps a system similar to what [giscus](https://giscus.app/) is providing (Maybe even use it for that? Idk) could be an idea. So instead of issues, use discussions for it... But then again, I feel like this could be a bit weird and would also require stuff like managing GitHub OAuth flow and stuff.

**Comment by gaoliang** [comment]
I found that [Docusaurus](https://docusaurus.io/docs/blog)  has a nice built-in blog plugin

**Comment by mfridman** [comment]
> Things I wanted mkdocs-material-blog to have above the mentioned ones:
> 
> 1. searchable tags
> 2. archive page will all posts chronologically ordered
> 3. support for an author profile that can be linked via meta tags. An author summary is then presented on a post page in the header/footer.
> 4. read time estimation

Much of what I was going to propose is captured by @hellt 

> The ability to broadcast new posts and send notifications via RSS, Twitter, or Slack would be the cherry on top. :)

I think this would probably be out-of-scope, but one idea without getting too fancy would be to offer simple "share out" links, similar to this https://fly.io/blog/

![CleanShot 2021-12-20 at 21 38 57@2x](https://user-images.githubusercontent.com/6278244/146861612-c5eeebf0-4e6b-4660-8c3f-d7b65ae1d24a.png)

I've recently taken some inspiration from [this blog: https://fly.io/blog/](https://fly.io/blog/) .. the one thing I don't like is having to manually page through to discover blog content. IMO this should be configurable whereby the default is to show _all_ post summaries, and if your blog has A LOT of content then flip a bit to render a paginated chronological ordering of post summaries.

Either way, really looking forward to whatever blog support will be included with Material for MkDocs ✌️

**Comment by dhirschfeld** [comment]
For me, some sort of integration with Jupyter notebooks would be useful.

The simplest way to incorporate notebooks would be using [`nbconvert`](https://github.com/jupyter/nbconvert) to convert to markdown and then processing with `mkdocs` as normal but there might be some added value in e.g. being able to reference individual cells/outputs to include rather than whole notebooks. I'm not sure if that exists elsewhere.

Mathjax is also important for me, but since that works in `mkdocs-material` I assume that's a given.

**Comment by timvink** [comment]
@dhirschfeld Good news! See https://github.com/greenape/mknotebooks

**Comment by squidfunk** [comment]
@dhirschfeld – all features and specimen that are available in Material for MkDocs will also work with the blog: content tabs, code blocks, code annotations, instant loading, etc.

**Comment by dcode** [comment]
Another feature that would be handy for blog content is support for `draft` status in the meta header. Hugo supports this, for example, and will omit rendering the page altogether. This is probably more of a mkdocs plugin than a theme feature though. Similar logic applies for `publishDate`: only render the page if the current date is equal to or greater than the date shown.

[Hugo front matter vars](https://gohugo.io/content-management/front-matter/)

**Comment by gkapfham** [comment]
Hello @timvink, thanks for pointing out the https://github.com/greenape/mknotebooks plugin, that looks interesting! I've not yet had time to try that plugin, but I did read its documentation. If I understand it correctly, it seems as though it can execute the Jupyter notebook with a plugin and then display the results of executing the notebook in the rendered version of the site.

Following on from this suggestion, I have a question: Is there a way to run the Python source code in a code block in an interactive fashion directly inside of the web site and then display the result? There are several examples of this type of approach available online but I have not seen something that implements this workflow and integrates into Material for Mkdocs. Here are some references/examples that I have found:

- https://course.spacy.io/en/: Runs the Python source code segments in MyBinder, no export to Binder needed
- https://www.debuggingbook.org/: Also runs the Python source code in MyBinder, requires export of notebook first
- https://jupyterbook.org/interactive/interactive.html: Uses the Thebe package to make interactive source code (reference for details about Thebe and how it integrates into the Jupyter Book project: https://thebe.readthedocs.io/en/latest/index.html)
- https://d2l.ai/index.html: Exports the source code to platforms like Colab and then allows notebook execution
- https://rahul.gopinath.org/post/2021/11/13/regular-grammar-to-regular-expression/: Uses Pyodide to run the Python source code directly in the browser (reference for the Pyodide project: https://pyodide.org/en/stable/index.html)

Thanks in advance for reading this note and, as your schedule permits, suggesting some ways to make the Python source code in a code block. If you can point me in the right direction for a site that has executable code or a package that would be a good place to start, then I would greatly appreciate it! If this feature already exists and I have overlooked it, please let me know as well! Overall, my view is that it would be really awesome if the code blocks in a Material for Mkdocs site were executable!

**Comment by squidfunk** [comment]
@timvink @gkapfham could you move this to a separate discussion? It’s not related to the issue at hand but has great value for other users, so a dedicated discussion would be perfect 😊

**Comment by sheldonhull** [comment]
A few things to bring up having been a huge fan of mkdocs material, and having used jekyll, hugo, ghost, and a plethora of tooling around this. 

## What navigation and directory structure would you expect from a blog?

I'd like to be able to have a flat doc hiearchy. I think there's a good case for this, so right now I've got my posts as `mysite.com/title-name/` without the need to have sub paths. It keeps things nice and simple even if you change structure. Only requirement is that you have unique page titles.



## How would you write a new blog article, i.e., what's the expected DX?

I created some Go cli commands so I run: `mage post` and then select the type of post and it creates a templated markdown file. I mark as a draft or not, and then commit and push. Netlify builds and in roughly 3-4 mins the site is updated. Having some easy tasks to create the right file in the right location help using "archetypes". When I created docs with Mkdocs, I just manually created the files. 

Something similar would be good for mkdocs. Allow simple templated types to be called and simple invocation via mkdocs to create. I can post a gif of how this works for me currently if it helps. 

## What pages besides the index page do you need? Archive? Tags?

In Hugo, I've got a couple types of taxonmy/archive style pages. 

- [Archive](https://www.sheldonhull.com/archive/) - Filtered to exclude microblog style posts
- [Posts](https://www.sheldonhull.com/posts/) - More of a excerpt view of recent content, so microblog + long-form all show up in the same place.
- [Tags](https://www.sheldonhull.com/tags) - Nice to have, primarily to filter RSS output for distribution.


## ... anything else that's on your mind

### Slugs

The slug/naming is critical to allowing folks to migrate to the toolchain. I'd looked at mkdocs before since I really love this material theme for a knowledge base + wanted to blog. As it stands, Hugo provides some nice flexibility in setting the slug scheme, so I can do `slug` as the primary key, rather than dates being involved.  https://github.com/sheldonhull/sheldonhull.hugo/blob/32362c2bd6676910538776118cc4396580a147e2/config.yml#L434
    - Note: The front-matter allows override with "slug" so I've had great control regardless of theme migration keeping things from breaking as I typically include the slug explicitly so I have 100% control of my url. For example [here](https://github.com/sheldonhull/sheldonhull.hugo/blob/32362c2bd6676910538776118cc4396580a147e2/content/posts/2020/2020-04-20-improved-windows-terminal-setup.md?plain=1#L4) I have a title for a Microblog post, but I control the actual page permalink to ensure title can change without breaking in this situation.

### Authoring Via Markdown

Source for the blog posts as the "lowest common denominator", is markdown files created via whatever command like `mkdocs new post "foo"`. That said, leveraging GitHub issues for sourcing posts would be pretty cool to consider, but I'd throw out there that anything like this is non-critical to a blogging feature, more like an extension/option that might work for some. I don't consider this a core blogging feature. Also, [Forestry](https://forestry.io/) might be worth checking out. I've used it for a bit with Hugo and might offer a good partnership if someone really wants a UI integration with this.

### RSS 

RSS. This feature seems to be a last thought in many of the new "notion to static site" style tooling and other things I've reviewed. It's really important to have control of the RSS produced for blogging if you have any desire to distribute or syndicate your posts, so please consider that a core part of successful blogging implementation. I've had to do a bit of customization in my Hugo blog to get RSS working like I wanted, and breaking subscription links/publishing links is one of those major barriers to migration I've observed. 



I'll follow for more detail/discussion threads, as I'm excited to see where this goes. Thank you for such an incredible project! 👍

**Comment by squidfunk** [comment]
Thanks to all of you for the great input! It helps a lot to distill a draft for a first iteration 😊

**Comment by eyllanesc** [comment]
It should also implement the concept of "Series", that is, a set of related articles. An example is https://kubasejdak.com/techniques-of-variadic-templates:

![Screenshot_20211017_170724](https://user-images.githubusercontent.com/4896200/137646660-5ffe65de-b417-4aa7-99fb-29f4e11fb825.png)

**Comment by eyllanesc** [comment]
Maybe it is not a visible feature but if something similar to [HUGO Shortcodes](https://gohugo.io/content-management/shortcodes/) is implemented but through plugins, new functionalities could be added easily.

**Comment by squidfunk** [comment]
@eyllanesc the [`macros`](https://mkdocs-macros-plugin.readthedocs.io/en/latest/) plugin might be what you're looking for.

**Comment by eyllanesc** [comment]
To implement the "shared out" links you could use the  [sharer.js](https://github.com/ellisonleao/sharer.js) library.

**Comment by Andre601** [comment]
Not sure how possible or useful this could be to have, but maybe have some way to send updates for newly made posts?

Like a way to detect a new blog post and in such a case do something like a webhook POST request or similar. Could be useful for people to get informed about new posts outside of methods such as RSS or similar...

**Comment by ben519** [comment]
I'm stoked for this! Here's what I'd love to see..

1. Social share buttons
2. The ability to declare author(s) in yaml front matter and have them displayed in the post, similar to how you did it [here](https://squidfunk.github.io/mkdocs-material/blog/2021/the-past-present-and-future/)
3. Configurable "previous" and "next" buttons in the footer. It's weird if an article about "dogs" has a _next_ link to an article about finance, just because they're siblings in the `nav`.

**Comment by Andre601** [comment]
A sort of way to have multiple blogs under different categories (And maybe even allow to have different default settings per category) would be a nice feature to have.

See https://github.com/liang2kl/mkdocs-blogging-plugin/issues/17 for more details.

**Comment by shokinn** [comment]
## What pages besides the index page do you need? Archive? Tags?
I would love to see an option to have multiple article authors with an "Authors overview" (All blog authors with, e.g. social media, website links and a short description) and "John Doe's articles" page (where all articles of that author are listed) and the possibility to assign articles to an author.

**Comment by birdybro** [comment]
## What navigation and directory structure would you expect from a blog?

Directory structure:

`/blog/article.md` or `/blog/yyyy-mm-dd/article.md`

On the site it would look like this:

`mysite.com/blog/article/` or `mysite.com/blog/yyyy-mm-dd/article/`

This should be an option that is toggleable in mkdocs.yml ideally when blog is enabled.

## What pages besides the index page do you need? Archive? Tags?

As little as possible. The simpler the better is my view. Tags are unnecessary because we have the search function. I would like the blog search results to be segregated from the docs so there isn't noise for the user. The user has to go to the blog site, and then using the search function there is for blog content only. When in the docs side of things, then it only searches the docs. If that makes sense. Tags seem like an old affectation of earlier blogs that no one really should be focusing on in my opinion. People read blogs for updates from a certain site or they find them through search engines online. Whatever optimizes SEO for the blogs is preferred, as is already done with Docs.

I would like to see the ToC from docs disabled by default in blogs and navigation sidebar on the left have the blog articles in order from newest to oldest by title, with a cutoff to restrict them to one line. Basically, using blogs would entail using the top bar I think for primary site navigation, similar to how the Material for MkDocs page is already setup.

## How would you write a new blog article, i.e., what's the expected DX?

Identical to the docs pages to be quite honest. Blogs to me should be simple to write so content creators don't have to be technically minded, just like the Docs. 

## ...anything else that's on your mind

Thanks for your work on your project, it's helped me create a new proposed documentation site for the MiSTer FPGA project and it's been a lot of fun learning the ins and outs of it all. https://birdybro.github.io/MkDocs_MiSTer/

That being said, I'm excited about the blogs feature as we want to allow our developers and other contributors an opportunity to submit articles when new updates come out or to show off new features, and would love it all to be on the same site. So this is right up my alley. :)

**Comment by Realvincentyuan** [comment]
This is a great proposal and I believe many people expect this feature!  Here are some of my thoughts.

## Limited migration effort

By far for tenured users of mkdocs, there might be quite a lot of docs already, some of them can be put in a blog format, so it is very important to ensure that the blog features can empower the existing posts with minimal modifications, say adding some necessary keywords in the header.

## Faster deployment and loading speed

A good example is `HUGO` which is noticeably faster.

## A good example

This is a [sample framework](https://doks-child-theme.netlify.app/blog/) built with HUGO, the navigations, table of contents and content are mostly similar to mkdocs, but it has a few things I like:
- Posts linked to authors and users can click the author name to see all posts written by the author
- A list view of posts, in fact it is better if the `tags` can be put on top for filtering

---

Other features mentioned by users above this thread can be addressed with mkdocs plug-ins already, such as:
- like/dislike buttons
- share to social media buttons
- RSS

so I do not think they are dedicated features that will be very beneficial to blogs. Besides, this proposal was brought up five months ago, wonder where it is by far. Again, thank you for the great proposal! @squidfunk

**Comment by squidfunk** [comment]
So, just a little heads up: I'm actively working on the blogging feature. I'll need some more time, as it's a pretty big thing to get out the door given the functionality we'd at least need for an MVP, but it'll be worth the wait and just as easy to use as the rest of Material for MkDocs. Furthermore, it will also be possible to build a blog as the main thing, not just as a sidecar, making Material for MkDocs an excellent choice for building a technical blog.

What's time-consuming is all the stuff I need to do besides, like bug fixes, issue triage, etc, so that is the main limiting factor for getting this out the door. I expect many of the requirements that were collected here to be possible, many of them in the first version. Additional functionality will be added gradually, once I could give the blogging feature into your hands!

**Comment by FelipoAntonoff** [comment]
@squidfunk Very nice, looking forward to this new feature.
Today I use MkDocs + Material for websites and documentation, Blog I made few posts using date in a document to try to separate, looking forward to using Material for basically every use case we need.

Congratulations for the excellent work.

**Comment by SilentGlasses** [comment]
Would something like this be feasible?

Pagination by year would be a nice to have, or at least to make the year in the sidebar [as it is now](https://squidfunk.github.io/mkdocs-material/blog/) to be collapsible. 

https://github.com/fmaida/mkdocs-blog-plugin

**Comment by squidfunk** [comment]
I've already implemented dates and they are completely flexible and configurable by the author.

You will be able to specify how blog overview pages and archive pages group articles by dates, either only by year or year and month, or whatever format you like including no date for evergreen content. It's completely up to the author. As always, Material for MkDocs' philosophy is to allow for maximum flexibility with sane defaults.

**Comment by dhirschfeld** [comment]
> I've already implemented dates and they are completely flexible and configurable by the author.

That sounds great! Is this available to try on insiders, or is it still incubating?

**Comment by squidfunk** [comment]
Still incubating.

**Comment by squidfunk** [comment]
Still incubating.

**Comment by shirooo39** [comment]
> Furthermore, it will also be possible to build a blog as the main thing

This made my day.

So, uhm... is there an... ETA for this?

**Comment by squidfunk** [comment]
@shirooo39 I'm currently on vacation, but as soon as I'm back I'm going to continue working on the blog. [As I already said](https://github.com/squidfunk/mkdocs-material/issues/3353#issuecomment-1166504915), it's a pretty big thing to get out of the door, effectively almost entirely re-implementing something as Jekyll. But I'm absolutely certain it'll be worth the wait.

**Comment by squidfunk** [comment]
Good news – the blog plugin is almost done! I just need to polish it a little and write the documentation, which is probably the next task taking the most time, given its millions of options. I plan to release it in mid-September. Here's how it looks:

![screenshot-localhost-8000-mkdocs-material-blog-1662294496801](https://user-images.githubusercontent.com/932156/188334761-6dc5158e-d85e-432a-9128-5c611dc0ae90.png)

![screenshot-localhost-8000-mkdocs-material-blog-2021-09-13-search-better-fas-1662327290478](https://user-images.githubusercontent.com/932156/188334748-f679a1c5-93e1-4638-a08c-580784c5e3af.png)

There are tons of hidden niceties that will make the writing experience feel almost marvelous and you can configure and customize the hell out of it. Really love how it turned out and excited to give it in your hands 🚀

**Comment by Andre601** [comment]
Let me be the one that askes the obvious question: Will this be a Insiders feature when it releases and if yes, are the alternatives for people that don't have the funds (like me) to still get it?

**Comment by squidfunk** [comment]
Yes. I already announced it several months ago (it's been part of the [Piri Piri](https://squidfunk.github.io/mkdocs-material/insiders/#12000-piri-piri) goal for some time). The blog will definitely be an Insiders feature. I've invested a lot of hours into it, and I expect many more hours are yet to come when we iterate on it.

What do you mean regarding the alternatives? There are several MkDocs blogging plugins out there which you can use as a replacement. If that's not an option, you have to wait until the $12,000 goal is reached, which at the current growth rate I'd expect to be at the end of 2023.

**Comment by Andre601** [comment]
Okay. I expected as much.

And yes, blogging plugins do exist, but I doubt they do have all the features Material for MkDocs will probs offer.
Not to mention is at least one of those plugins in maintenance-only mode as the dev lost general interest (And that's sadly the more usable blogging plugin of the bunch)

Guess I'll have to wait for that 12k goal to be reached.

**Comment by kcgthb** [comment]
This looks very awesome!

We're currently maintaining a separate "news" site just for this kind of blog/updates usage, so integrating it all together with our main docs site would be a huge streamlining step.

Will there be any mechanism to alert or notify users about the publication of new entries? Like a widget, RSS feed or similar?

**Comment by squidfunk** [comment]
> Will there be any mechanism to alert or notify users about the publication of new entries? Like a widget, RSS feed or similar?

@kcgthb RSS can be implemented with the [mkdocs-rss-plugin](https://guts.github.io/mkdocs-rss-plugin/). I think the plugin should provide all necessary functionality, so it doesn't currently make sense to integrate RSS into the blog plugin. Other than that I'm not sure what you mean by widget? Like an iframe that can be integrated into another site? There's currently no such functionality, no. My aim was to first get proper blogging support out the door. When we've done that, we can check what makes sense to add to the plugin.

**Comment by kcgthb** [comment]
Thanks @squidfunk !
Yes, by widget I meant something that could be embedded somewhere and give readers a visual indicator that a new entry had been posted. Something like that: https://announcekit.app/widgets

But it totally makes sense to start with base functionality first, and then add more features afterwards.

**Comment by jooola** [comment]
Thanks for the hard work !

I was wondering how this would play with regards to versioning and deployments using `mike` ? I would expect the blog not to be versioned (say `/blog/my-post-slug/`), while being able to browse a versioned documentation using `/docs/3.0/setup/`.

**Comment by squidfunk** [comment]
Yes, that's still a problem since `mike` will treat your entire site as one and thus also version the blog, which is not desirable. A solution could be to build two MkDocs sites and combine them into one, one versioned, the other not. I'd expect that there will be some users having this problem, so I'd be happy to add any functionality to Material for MkDocs to support this use case, but first, `mike` would need to support it. I'm not sure if it already does.

Other than that, there're several multi- or mono-repo plugins that allow to combine multiple sites into one. Maybe those are of any help. I think if `mike` would add the ability to deploy itself on a subdirectory, or to exempt certain directories from versioning, that might be all there's needed. All in all, I recommend taking this upstream to `mike`. Related:

- https://github.com/jimporter/mike/issues/109
- https://github.com/jimporter/mike/issues/97
- https://github.com/jimporter/mike/issues/73 (__particularly interesting__)
- https://github.com/jimporter/mike/issues/61

**Comment by squidfunk** [comment]
Insiders 4.23.0 was just released, and it contains the built-in blog plugin:
https://twitter.com/squidfunk/status/1569241893791203328

I want to thank all of my awesome sponsors at this point, who funded my efforts on this plugin and made the development possible in the first place. Without you, this plugin wouldn't exist. Let's iterate on it and make it even better!

I'm closing this issue, since everything is done here. Please open new issues for bug reports and feature requests.
