### ISSUE TITLE
From partials/source.html to partials/source-item

### ISSUE THREAD

**Issue by alanlivio** [squidfunk/mkdocs-material#3502]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Hi,

The current [partial/source.html](https://github.com/squidfunk/mkdocs-material/blob/master/material/partials/source.html) is great and useful for the current project.
I am trying to create my personal page and I would like to reuse such partial to list start/fork for my personal projects.
So, I suggest the support aka source-item.html partial enable be reused.
Today the source.html is fixed for the main repo [here](https://github.com/squidfunk/mkdocs-material/blob/9655c3a92471f261533d48b8611a8d24dbfebb13/src/assets/javascripts/components/source/facts/gitlab/index.ts).
What do you think?

Best regards.

### Use Cases

- personal webpages
- list start/forks for multiple github repos

**Comment by squidfunk** [comment]
Thanks for suggesting. This is definitely something that should be implemented as customization by the author, as I don't see how we should integrate this into this project. You can copy the source from the `source.html` partial and adapt it to your needs, i.e. set other repository URLs, as the URL is what is used to query GitHub or GitLab. You may however need to adjust the caching mechanism in session storage, because it currently only caches a single value:

https://github.com/squidfunk/mkdocs-material/blob/b2ecd717bdebc71b514d3eb0ace10efc497fcf98/src/assets/javascripts/components/source/_/index.ts#L80-L99

Closing as customization request.

**Comment by alanlivio** [comment]
Thank you @squidfunk.
I know how to make customization using mkdcos html overrides. But I do know how exactly how to reuse such intex.ts code.
May you give some guidance?

**Comment by squidfunk** [comment]
Of course. You can fork the theme, make your changes, and then rebuild it. See the [theme development guide](https://squidfunk.github.io/mkdocs-material/customization/#theme-development) for precise instructions how to set up a development environment and how to rebuild the theme.
