### ISSUE TITLE
Feature suggestion and debate: Demo videos as code with asciicast

### ISSUE THREAD

**Issue by sean-freeman** [squidfunk/mkdocs-material#3625]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Demo videos. This is always a sensitive topic for technical content and sensitive topic for Markdown content (with [no Markdown-approved solutions](https://about.gitlab.com/handbook/markdown-guide/#display-local-videos-html5)).

While this is not (and should not) ever be a [Python-Markdown extension](https://python-markdown.github.io/extensions/), there is an opportunity for mkdocs-material to source [asciinema-player](https://github.com/asciinema/asciinema-player) and allow `<script>` blocks within a Markdown page to display [asciicast file format `.cast`](https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md) files stored within the same repo as the content.

Thereby keeping all technical content and demo video recordings of code execution, within the same documentation repository.

It's not good Markdown content, but it would make mkdocs-material more powerful for it's intended purpose.

### Use Cases

Demo videos as code = Happy technical content writers.

**Comment by squidfunk** [comment]
Thanks for suggesting. What is it that Material for MkDocs would need to support that could not be added with extra CSS or JavaScript? Should we integrate the player or what is it exactly you're asking for?

**Comment by squidfunk** [comment]
I've taken a look at [asciinema-player](https://github.com/asciinema/asciinema-player):

> asciinema player is an open-source terminal session player written in Javascript and Rust/WASM. Unlike other video players asciinema player doesn't play heavy-weight video files (.mp4, .webm etc) and instead plays light-weight terminal session files called [asciicasts](https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md).

I don't see anything we need to add to Material for MkDocs in order to get up and running with this player. You can just add the files with [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) and [additional style sheets](https://github.com/asciinema/asciinema-player#use-the-standalone-player-bundle-in-your-html-page) – it's actually super easy. The README of the player tells you [which files you need to add](https://github.com/asciinema/asciinema-player#use-the-standalone-player-bundle-in-your-html-page). This should be achievable in a few minutes 🚀

**Comment by sean-freeman** [comment]
For anyone who refers to this, see example setup below.

`mkdocs.yaml`
```
extra_css:
  - stylesheets/asciinema-player.css

extra_javascript:
  - javascripts/asciinema-player.min.js
```

`index.md`
```
## Demo

Optional text here

<div id="unique-id-not-same-as-markdown-title" style="z-index: 1; position: relative; max-width: 80%;"></div>
<script>
  window.onload = function(){
    AsciinemaPlayer.create('/path/file.cast', document.getElementById('unique-id-not-same-as-markdown-title'));
}
</script>
```

**Comment by chipsenkbeil** [comment]
An old issue, but I was curious about the same thing. Looks like someone wrote a mkdocs plugin for this purpose: https://pypi.org/project/mkdocs-asciinema/.

So I'm assuming you could install the plugin and enable it, and then write like usual:

```markdown
![asciicast](/images/asciinema/tmpzuu_levn-ascii.cast)
```

**Comment by Moulick** [comment]
@chipsenkbeil Thanks, I would also prefer your macro over [mkdocs-asciinema](https://pypi.org/project/mkdocs-asciinema/) 

So in summary, 
1. Include the extra Javascript and CSS
2. Add the `mkdocs-macros` plugin
3. Create a `asciinema.py` with your code to load with `mkdocs-macros`.

The part I don't quite get is how to get `mkdocs-macros` to load `asciinema.py`. I currently have no other python files in my docs.

**Comment by alexvoss** [comment]
It has been a while since I used the macros plugin but it looks like [the path to Python modules is resolved from the directory that contains your `mkdocs.yml`](https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/#local-module). The simplest thing would by to just call the file `main.py` and not specify any options for the macros plugin.

**Comment by chipsenkbeil** [comment]
@Moulick you can see how I use it here: https://github.com/chipsenkbeil/distant.dev

Specifically, I define within `mkdocs.yml` a specific module for macros.

<img width="299" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/2481802/c9652e51-c046-4e6d-982c-4afde8444f74">

And then within `macros.py` at the top level, I have this defined:

https://github.com/chipsenkbeil/distant.dev/blob/8894e68cdb0424e4ed707425ca77dff5458429be/macros.py#L16-L53
