### ISSUE TITLE
Both drawer and tabs are shown at a certain browser widths

### ISSUE THREAD

**Issue by ukkopahis** [squidfunk/mkdocs-material#3656]
### Description

Both tabs and drawer is shown when browser width is just "right".
Reproducible on your home page: https://squidfunk.github.io/mkdocs-material/
![material-width-bug](https://user-images.githubusercontent.com/95980324/156438962-6a70862b-6a78-44dc-a122-ac5105de2a7f.png)

### Expected behaviour

Either tabs or drawer is shown.

### Actual behaviour

Drawer is shown but won't work. 
This happens because css max-width and min-width for showing drawer and hiding tabs are not equal:
![material-width-logo](https://user-images.githubusercontent.com/95980324/156439210-92c5e2d9-3176-4bdd-84c8-28e71e639fad.png)
![material-width-drawer](https://user-images.githubusercontent.com/95980324/156439239-dc871411-c1cb-488d-9b9c-1a1734a44620.png)

### Steps to reproduce

1. open https://squidfunk.github.io/mkdocs-material/
2. adjust browser window width to 76.2em

### Package versions

As used on your home page.

### Configuration

```yaml
As used on your home page.
```

### System information

- Browser: Firefox 94.0.2 (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting. I'm only able to reproduce this when the browser is zoomed, i.e. above 100%. It's related to relative media queries (in `em`) and rounding errors,  and from my knowledge not fixable with reasonable effort.

Essentially, we could do two things:

1. We either switch all media queries to `px`, which _might_ fix the issue (testing required), but then would lose the ability for the theme to adapt to the base font size of the user, as currently everything is defined in relative to the base font size. Moving away from this approach might have severe consequences for accessibility, as this approach is followed by Material for MkDocs since version 1.0.0 (2017).

2. We switch all media queries to `min-` or `max-width` media queries, which would need a significant rewrite to the underlying codebase. I was hoping for the new [syntax improvements](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax_improvements_in_level_4) to catch on quicker, but at the time of writing still only Firefox supports the new range syntax which would fix the issue at hand.

For this reason, I'm currently considering this issue as not fixable. As said, it only happens when you zoom the page and are on that very specific breakpoint. It's just not worth the efforts. Now, what can you do? You could fork the theme and replace the media queries with pixel values. The relevant section is here:

https://github.com/squidfunk/mkdocs-material/blob/cfa64745a22c170ecce768a035ce949c809dd3f9/src/assets/stylesheets/_config.scss#L28-L42
