### ISSUE TITLE
Feature suggestion: page minimap

### ISSUE THREAD

**Issue by tylernguyen** [squidfunk/mkdocs-material#3684]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The concept is similar to Sublime and VSCode’s minimap. The minimap would be a verticals strip on one side showing a scaled version of the page’s content.

### Use Cases

Particularly with pages with long contents, code blocks, images, embedded contents; A visual page minimap would be more useful for navigation than the table of contents.

**Comment by squidfunk** [comment]
Thanks for suggesting. That's a pretty wild idea I've never seen anywhere implemented. The problem is that a minimap would somehow need to replicate all of the page content, thus doubling the number of nodes. When the page is long, this would put even more pressure on the rendering engine. Furthermore, a minimap will likely not work well on mobile.

Material for MkDocs always strives to be fast. I would have serious concerns about the implications of shipping such a feature. Thus, I'm not considering implementing this.
