### ISSUE TITLE
Pass Lighthouse audits

### ISSUE THREAD

**Issue by tuxredux** [squidfunk/mkdocs-material#383]
[Lighthouse](https://github.com/GoogleChrome/lighthouse) is the progressive web app auditing tool by Google, and since this project aims to provide [Material Design](https://material.io/) for `mkdocs` I thought it would be a useful tool to use!

You can even [hook it up with continuous integration](https://github.com/ebidel/lighthouse-ci). Lighthouse currently has four audit categories: *Progressive Web App*, *Performance*, *Accessibility*, and *Best Practices*. The most important audits are *Accessibility* and *Best Practices*. *Performance* is usually reserved for production environments. The *Progressive Web App* category requires service worker support, which I understand may be a little too far reaching at this time. A good place to start though to achieve a *Best Practices* perfect score (100) and a *Progressive Web App* maximum score (73) without a service worker would be a `manifest.json` with appropriate favicon and [short_name](https://developers.google.com/web/tools/lighthouse/audits/manifest-short_name-is-not-truncated) support. You can use [realfavicongenerator](https://realfavicongenerator.net/)!

Here is an [example lighthouse audit](https://webev.org/audits/webev.org_2017-06-18_23-20-02.html) (best viewed in Chrome) outlining the current issues for a `mkdocs-material` website in production. Thanks for your time!

**Comment by squidfunk** [comment]
This sounds like a great idea. I was already thinking about this but haven't had the time. If somebody would like to PR this, I'm happy to merge. The question is, if a `manifest.json` can be included with the theme, as it may depend on the MkDocs build, as the final files depend on the documentation project, not the theme.

**Comment by squidfunk** [comment]
I evaluated the lighthouse audit and come to the following conclusion:

[36] Progressive Webapp

* FAILS Register a Service Worker: in my opinion this makes no sense to integrate into Material in general, as it is targetted at web apps, not documentation sites. A splash screen, push notifications, etc. make no sense
* FAILS Responds with a 200 when offline: no service worker, cannot work
* FAILS Redirect HTTP to HTTPS: depends on deployment, not Material
* FAILS Page load is fast enough on 3G: could be improved, but is not specific to Lighthouse
* FAILS User can be prompted to install web app: makes no sense
* FAILS Configured for a custom splash screen: makes no sense
* FAILS Address bar matches brand colors: dicussed and discarded in #39

[30] Performance

This was benchmarked locally and is heavily dependent on what is loaded with Material. Material itself is super lightweight, the JS is 100kb minified (even smaller gzipped). Webfonts could be converted to SVGs and inlined in theory but this turns out to be complicated with things like Admonition etc. I always keep an eye on performance and it is not tailored to Lighthouse. If somebody has an improvement, feel free to PR.

[94] Accessibility

* FAILS Links have a discernable name: not possible to fix, due to the way links are generated from Markdown. All links within the theme should have proper title/alt set. If not, feel free to PR.

[75] Best Practices

* FAILS Use HTTP2: dependent on deployment
* FAILS Avoid document.write: not used by Material, but other scripts such as Google Analytics
* FAILS Manifest shortname should be defined: not possible, dependent on actual theme usage

For this reason, not much can be done to pass the Lighthouse audit from my side. Everyone using it has to optimize stuff, so it passes. Therefore I'm closing this issue as not fixable.
