### ISSUE TITLE
Enhanced Favicon Support

### ISSUE THREAD

**Issue by SebStange** [squidfunk/mkdocs-material#3834]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The current favicon implementation does not include high resolution images etc. used for modern browsers and other applicable scenarios like shortcuts or tile icons.

I'll probably start an approach to implement this and make a pull request, though I wouldn't mind hearing others thoughts on this beforehand.

### Use Cases

Especially modern browsers may well benefit from this and make sure the mkdocs-material pages will conform with other sites, the favicon for the targeted audience is used on.

### Screenshots / Mockups

Real life testing the project website via [Favicon Generator](https://realfavicongenerator.net/favicon_checker?protocol=https&site=squidfunk.github.io%2Fmkdocs-material%2F).

**Comment by squidfunk** [comment]
Thanks for suggesting. This would need to be implemented by a plugin because it would involve generating different versions of a favicon. Otherwise, the user would have to generate and include all icon versions themselves, which is likely not what you want. It's actually an excellent use case for a third-party plugin since it is not specific to Material for MkDocs, so all themes can benefit from it. Feel free to share your plugin here, if you implement it. We can also link it from the documentation. Closing, as out-of-scope.
