### ISSUE TITLE
Annotations: Redundant space after annotation

### ISSUE THREAD

**Issue by DimanNe** [squidfunk/mkdocs-material#3846]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Let's take this code:
```
    ```bash
    echo 1 && \ #(1)!
    echo 2 && \ #(2)!
    echo 3
    ```

    1. qwer
    2. asdf
```
It gets rendered into this:
![image](https://user-images.githubusercontent.com/279056/165045914-1b05f5f1-95ef-4143-a0b8-72263807c0cb.png)
So far so good.

Let's now try to select/copy it. You will see that there is an additional space at the end (strictly speaking, there is also an additional space before the annotation, but if you paste it somewhere, there is **just a single** redundant space):
![image](https://user-images.githubusercontent.com/279056/165046120-3eaa719f-9f3f-4e8a-8b3b-b69bd66ba65b.png)
which makes it impossible to use in the terminal (there should not be spaces after `\`).

### Expected behaviour

"Copy" is supposed to put in a clipboard text ready for pasting **and execution** (in the terminal).

### Actual behaviour

It cannot be executed in the terminal (without cleaning spaces at the end, first).

### Steps to reproduce

See above.

### Package versions

- Python: `python --version`: `Python 3.9.5`
- MkDocs: `mkdocs --version`: `mkdocs, version 1.3.0 from /usr/local/lib/python3.9/dist-packages/mkdocs (Python 3.9)`
- Material: `pip show mkdocs-material | grep -E ^Version`: `Version: 8.2.8+insiders.4.12.0`


### Configuration

```yaml
site_name: Internal Docs


theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.tabs.link
    - content.code.annotate
  icon:
    admonition:
      # note: octicons/tag-16
      # abstract: octicons/checklist-16
      # info: octicons/info-16
      # tip: octicons/squirrel-16
      # success: octicons/check-16
      # question: octicons/question-16
      # warning: octicons/alert-16
      failure: octicons/x-circle-16
      # danger: octicons/zap-16
      bug: octicons/bug-16
      # example: octicons/beaker-16
      # quote: octicons/quote-16


markdown_extensions:
    - toc:
        permalink: True
    - smarty
    - sane_lists
    - abbr
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true


extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - offline
```

### System information

- Operating system: docker image with based on ubuntu:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```
- Browser: Google Chrome | 101.0.4951.41 (Official Build) beta (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting. The problem is not the trailing whitespace (which is just a line break, but the browser selects it so that it appears that it looks like whitespace), but the whitespace after the `\` and before the starting marker of the comment. Thus, this has nothing to do with annotations, but with comments after `\` characters. I've added whitespace after `\` without a comment, which is also preserved by Pygments. If you inspect the HTML, this is quite clear:

````
```bash
echo 1 && \ #(1)!
echo 2 && \ #(2)!
echo 3 && \ 
echo 4
```
````

Becomes:

``` html
<code><a id="__codelineno-0-1" name="__codelineno-0-1"></a><span class="nb">echo</span> <span class="m">1</span> <span class="o">&amp;&amp;</span> <span class="se">\ </span><span class="c1"><aside class="md-annotation" tabindex="0" style="--md-tooltip-x:126.5px; --md-tooltip-y:20.5px; --md-tooltip-0:-376px;"><a href="#__code_1_annotation_1" class="md-annotation__index" tabindex="-1"><span data-md-annotation-id="1"></span></a></aside></span>
<a id="__codelineno-0-2" name="__codelineno-0-2"></a><span class="nb">echo</span> <span class="m">2</span> <span class="o">&amp;&amp;</span> <span class="se">\ </span><span class="c1"><aside class="md-annotation" tabindex="0" style="--md-tooltip-x:126.5px; --md-tooltip-y:40.5px; --md-tooltip-0:-376px;"><a href="#__code_1_annotation_2" class="md-annotation__index" tabindex="-1"><span data-md-annotation-id="2"></span></a></aside></span>
<a id="__codelineno-0-3" name="__codelineno-0-3"></a><span class="nb">echo</span> <span class="m">3</span> <span class="o">&amp;&amp;</span> <span class="se">\ </span>
<a id="__codelineno-0-4" name="__codelineno-0-4"></a><span class="nb">echo</span> <span class="m">4</span>
</code>
```

The problem are these tags:

``` html
<span class="se">\ </span>
```

For this reason, I don't believe that this can be fixed without adding logic that Material for MkDocs detects that the code block is a bash/sh code block and strips whitespace after `\`. However, adding support for quirks of custom language is a can of worms I really don't want to open. It would be a maintenance hell.

**Comment by squidfunk** [comment]
However, you could kind of implement this yourself. Just add some [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) that goes through the code blocks and searches for `.se` spans to strip trailing whitespace. Maybe something like (untested):

``` js
document$.subscribe(() => {
  const tags = document.querySelectorAll("code .se")
  if (tags.innerText.startsWith("\\"))
    tags.innerText = "\\"
})
```

**Comment by hellt** [comment]
Based on the [suggested](https://github.com/squidfunk/mkdocs-material/issues/3846#issuecomment-1108293135) js code with a few chatgpt modifications I made it work for my bash multiline snippets. 
The PR that adds custom js is https://github.com/srl-labs/learn-srlinux/pull/133

Thanks @squidfunk

**Comment by serious-angel** [comment]
I am sorry, but just to clarify, what's the point of the feature if such common shell code won't work in the first place (invalid syntax), the one you stated as the example?:
```bash
echo 1 && \ #(1)!
echo 2 && \ #(2)!
echo 3
```

**Comment by squidfunk** [comment]
It's an issue with [Pygments](https://pygments.org). We render code annotations in JavaScript, since the code is quite complex, but first, all code blocks are processed by Pygments during the build. Comments are the only way to add annotations reliably for all languages. However, the whitespace after `\` seems to be included inside the `span`, whereas it needs to be outside for code annotations to collapse and ignore it. Otherwise, we can't reliably determine in a general way what whitespace is necessary and what not.

Thus, please take this upstream to Pygments.

Moreover, Material for MkDocs is in [maintenance mode](https://github.com/squidfunk/mkdocs-material/issues/8523), and we don't intend to make any changes to our code base unless absolutely necessary, i.e. to fix security issues. Thank you for your understanding ☺️
