### ISSUE TITLE
Add support for adding tooltips to SVG elements

### ISSUE THREAD

**Issue by chrisdburr** [squidfunk/mkdocs-material#3934]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Tooltips that provide extra information about specific regions of a SVG file, based on `a href` tags that are wrapped around elements of the image. 

Having this supported natively with the tooltip feature would be excellent. At present, it seems to require the full SVG code to be added directly to the relevant page, and the `title` attribute does not work. Instead, as mentioned already in discussion #3932, it seems to require a `title` element instead.

### Use Cases

Allowing users to hover over different regions of a graphic and have information about the graphic appear. This could be useful, for example, in cases where the graphic is a flowchart/decision tree and different elements have short descriptions to help users quickly understand the graphic.

### Screenshots / Mockups

The following screenshot shows a (semi-functional) example, which was achieved by adding the full SVG code to a Markdown file and adding the tooltip using a `title` element.

<img width="783" alt="Screenshot 2022-05-18 at 13 54 14" src="https://user-images.githubusercontent.com/63010234/169043309-3460a95b-fbf9-4538-8215-664f95404066.png">

**Comment by carlskii** [comment]
+ 1 this capability would be great. Even better being able to add annotations to the SVG would be amazing.

**Comment by squidfunk** [comment]
I've taken some time to investigate and think that adding support for tooltips is possible. Annotations however are a totally different beast, as SVG and HTML namespaces have entirely different layout and positioning semantics.

**Comment by squidfunk** [comment]
It turns out that implementation is super tricky, as semantics between HTML and SVG are completely different. We can't share much of the positioning and layout code, as you essentially need to position the tooltip outside of the SVG, which makes the implementation unnecessarily complex. Given the small target group of users that would benefit from this feature (not much reaction on this issue), I'm currently not considering adding it.

Tooltips are currently Insiders-only. When we reach the funding goal, I'm always doing a slight refactoring of the features to be released because it's the best moment before pushing it out for general availability. When tooltips are due, I'll keep this use case in mind and see if we can integrate it, but currently no promises.

I hope for your understanding.
