### ISSUE TITLE
Selectively set `content.tabs.link` feature for specific documents

### ISSUE THREAD

**Issue by zhimsel** [squidfunk/mkdocs-material#4175]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When enabling [linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs)

```yaml
theme:
  features:
    - content.tabs.link
```

it is enabled for _the entire site_.

I'd like to suggest/request that this feature is able to be toggled on or off for a single document.

### Use Cases

It's quite possible (and in my case, true) that some pages on a site would find linked tabs useful while others would not.

For example, a document with 3 different sets of instructions for different programming languages would benefit from linked tabs (just like the example in the documentation).

However, another document may have multiple sets of tags that _happen_ to have the same title (e.g. "the easy way" and "the hard way"), but that shouldn't _all_ be switched at once.

### Screenshots / Mockups

I'm not sure the best ways (or even possible ways) to implement this, but maybe it can be done via YAML front matter (like the `title:` field)?

or maybe via a field in the tab markdown itself?

```markdown
=== "tab one" linked=false

    foo

=== "tab two" linked=true
```

Worst case, maybe `mkdocs.yaml` can have a list of exceptions to the feature?

```yaml
theme:
  features:
    - content.tabs.link:
        exceptions:
          - path/to/file.md
```

**Comment by squidfunk** [comment]
Thanks for reporting. It's not possible to disable linking for entire pages, because instant loading doesn't have metadata or configuration available – it's only available at build time. Thus, it's not a good fit, since we would introduce incompatibilities.

However, we might be able to add support for a `no-link` attribute (or similar) on content tabs, which would allow us to disable linking for a specific tab group. This could be accompanied by a `link` attribute, which would allow to opt a specific tab group into linking without making all content tabs linked.

The problem is that content tabs currently don't support adding attributes ([Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)) so this would need to be implemented first. You may follow up with [Python Markdown Extensions](https://github.com/facelessuser/pymdown-extensions), which implemented content tabs if the functionality described works for you. As soon as this is implemented we can add support in Material for MkDocs.

**Comment by zhimsel** [comment]
I created a feature request for `pymdown-extensions`: https://github.com/facelessuser/pymdown-extensions/issues/1766

**Comment by zhimsel** [comment]
For the future (if/when that feature is implemented), I had an idea for how this could be implemented. I'm not sure exactly what the code looks like for linked tabs, but I wonder if it's possible to set the "link key" for the tabs via an attribute (in addition to or instead of just turning it on or off).

So, instead of linking the tabs by their title (which could remain as the default behavior), you could use an attribute to explicitly link the tabs together:

```markdown
=== "Tab title" link-key=one

    Foo

=== "Tab title" link-key=two

    Bar

<... some text, other sections, etc...>

=== "A different tab title" link-key=one

    Baz
```

With that, even though the first two tabs have the same title, only the first would be selected automatically when selecting the third one.
