### ISSUE TITLE
Search result doesn't show up with Capital letters

### ISSUE THREAD

**Issue by wyaadarsh** [squidfunk/mkdocs-material#424]
## Description

Search result doesn't show up with Capital letters(Any word being capital)

### Expected behavior

Taking example of [https://squidfunk.github.io/mkdocs-material/](https://squidfunk.github.io/mkdocs-material/) and Searching for 'Material' ( M being capital ) doesn't show up anything  where as typing the same thing in small case ' material '  gives proper search results

### Package versions

* Python: 2.7.10
* MkDocs: mkdocs, version 0.16.3
* Material: `pip show mkdocs-material | grep -E ^Version`  (Gives a broken pipe)   but running pip install --upgrade mkdocs-material shows me i am on the latest release

By the way thanx for the improved search with partial word matches matching correctly

Cheers :)

**Comment by squidfunk** [comment]
Thanks for reporting. 1.7.5 did some changes to how the search works. Will fix it asap in the next release.

**Comment by squidfunk** [comment]
Fixed in 1.8.0

**Comment by ok4ib** [comment]
Hi. I think that the problem was fixed for the body of pages only but not for the headings. If a user is looking for a specific heading but the heading starts with a capitalized letter (In the most cases) the title is not indexed. The user can try to use capitalized or uncapitalized letters, but if the heading starts with a capitalized letter it won't be indexed.
