### ISSUE TITLE
Search sorting by date

### ISSUE THREAD

**Issue by ironicbadger** [squidfunk/mkdocs-material#4256]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

We use mkdocs to run [notes.jupiterbroadcasting.com](https://notes.jupiterbroadcasting.com) and would like the option to sort by date.

### Use Cases

There is an issue on our github explaining in more detail if you'd like it.

https://github.com/selfhostedshow/show-notes/issues/16

**Comment by squidfunk** [comment]
Thanks for suggesting. Unfortunately, this is kind of orthogonal to the concept of document search (or at least how lunr.js implements it which we use), which returns result by relevance, based on the query entered by the user. There are several problems that would need to be addressed in order to make this work:

1. The document (or section!?) date would need to be included in `search_index.json`. There's, however, currently no standard way to define a date for a document. One could use front matter and define a `date` key and use that, but that would only impact documents, not sections, which are returned as separate search results.

2. We would need to teach lunr.js to sort by date. However, from what I understand, there's no possibility to apply additional sorting criteria for search results in lunr.js – it's always relevance. You could somehow hack the behavior by indexing the date for each entry (if it would be included in `search_index.json`), and use the distance of the date to a future date (or the current date) as a sorting criterion.

I've never heard of that use case before, so given the age of this project, I would declare this as an edge case which doesn't provide much value for other users of Material for MkDocs. You could achieve this logic with customization, but from what I know about how search works with lunr.js, it'll be a bumpy ride.
