### ISSUE TITLE
Matomo Analytics

### ISSUE THREAD

**Issue by StrangeRanger** [squidfunk/mkdocs-material#4302]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Currently, support for Google Analytics is natively integrated into the project. I was wondering if support for adding Matomo Analytics could be added as well.

### Use Cases

Matomo Analytics is another analytics tool that is [relatively popular](https://www.wappalyzer.com/technologies/analytics/) alternative to Google Analytics, that is more privacy focus. It'd be nice to implement a more privacy centered analytics tool, such as Matomo, instead of Google Analytics.

Here are a few links to their website: https://developer.matomo.org/ and https://matomo.org/

**Comment by squidfunk** [comment]
Thanks for suggesting! I'd consider this out of scope for this project. I'm aware that there are many, many other analytics providers, but Google Analytics is still the most popular option. We can't provide more and more providers, because if we start adding Matomo, other users will request adding other providers as well. This is nothing I can commit to maintaining, as it would eat away too much of my time which is better invested on other features like the blog plugin.

Our documentation already contains a guide on how to add [custom analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-analytics), so it should be easy to implement this yourself.

**Comment by squidfunk** [comment]
If somebody wants to add and maintain support for this provider – it's very simple, please read https://github.com/squidfunk/mkdocs-material/pull/4847#issuecomment-1378467860. We're happy to advertise a third-party extension on our docs, so a PR with a docs change is appreciated.
