### ISSUE TITLE
Insider PDF Support

### ISSUE THREAD

**Issue by mudgen** [squidfunk/mkdocs-material#4316]
### Description

I would happily pay for good PDF support for mkdocs-material.

https://github.com/orzih/mkdocs-with-pdf is not being actively developed and does not work very well with the newest version of mkdocs-material. For example Admonitions don't show correctly with it.

### Use Cases

People could generate PDFs of their documentation that looked nice.

**Comment by squidfunk** [comment]
Thanks for suggesting! I understand that better PDF support would provide good value, but it's a very deep rabbit hole to vanish into. With Material for MkDocs, I'm focusing on the static site part, which means that my efforts for providing print support end at print stylesheets. If you print a single page from the browser, it should look pretty good already.

If you want to get a single PDF from your entire documentation, I'd question whether Material for MkDocs (or even MkDocs) is the right tool, as it's not primarily built for that case. It might be a better idea to process the resulting Markdown or HTML with Pandoc, to convert it to other formats.

Thus, until further notice, PDF support is subject to third-party plugins.

**Comment by mudgen** [comment]
Okay, think about it.  Maybe it is easier than you think, or something that could be done.

**Comment by squidfunk** [comment]
The [print-site plugin](https://github.com/timvink/mkdocs-print-site-plugin) by @timvink is a great and actively maintained third-party solution which you should check out, as it circumvents the need to replicate or fix styles/components for specific headless solutions by using the browser.

**Comment by mudgen** [comment]
This is really helpful, thanks @squidfunk!

**Comment by timvink** [comment]
> but it's a very deep rabbit hole to vanish into

As the author of [print-site-plugin](https://github.com/timvink/mkdocs-print-site-plugin), I can confirm 😄 The best approach I found was combining all mkdocs pages into a single page, fixing all the relative URLs and references, and then using some CSS/JS to do things like remove sidebars, top menu and introduce a new table of contents. You can then use the browser (headless or not) to print a PDF.

I've written a blog about using [mkdocs for technical reporting](https://timvink.nl/mkdocs-for-tech-doc/). But last month [quarto was announced](https://www.rstudio.com/blog/announcing-quarto-a-new-scientific-and-technical-publishing-system/) and for that use case I'm starting to change my mind. It's basically a rewrite of RMarkdown (that has existed for 10y or so) so very stable and mature. You can use it to write blogs, websites, reports and books, and because it uses pandoc it has excellent support for conversion to many formats, incl PDF. So if you're trying to create awesome PDFs and hitting the limits of mkdocs, perhaps mkdocs is not best tool for that specific use case. Mkdocs is epic at documentation however :D

**Comment by mudgen** [comment]
I didn't know about [print-site-plugin](https://github.com/timvink/mkdocs-print-site-plugin) before. It is a great solution for what I need. Thanks again.

**Comment by mudgen** [comment]
@timvink great, thank you!
