### ISSUE TITLE
Code boxes: Allow users to add their own vars on the rendered site

### ISSUE THREAD

**Issue by userbradley** [squidfunk/mkdocs-material#4332]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Allow users to add their own values to code boxes across a page, so they can set values once and all subsequent boxes on that page will have their values filled out 

### Use Cases

I am explaining how to enable IAP on a google cloud project, and it would be nice to have the users simply provide their project and compute engine name once, and all subsequent code boxes have that information updated 

## Example of what it could look like with no input
![image](https://user-images.githubusercontent.com/41597815/188888551-6fdf239b-f3cd-442f-8f8c-1856575a3bb4.png)

## Example of adding user input

![image](https://user-images.githubusercontent.com/41597815/188888748-c8f4a31c-2c41-4571-b167-208b6529d7a4.png)

Google do this well: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing-across-vpc-net

**Comment by squidfunk** [comment]
Thanks for suggesting. Interesting idea. The problem is that we'd need to find a representation for placeholders that works in all programming languages. Material for MkDocs is agnostic, so we need to find a way to generate code snippets that we can easily consume in the frontend after they were passed through Pygments.

Code annotations are related, as they use the comments of a language for placement. For variable placement, a much more sophisticated logic would be needed. Let's let this idea sit for a while and see whether other users would find this useful.

**Comment by squidfunk** [comment]
I've investigated this feature request and think it's currently too big of a problem to be solved for all languages. In general, it might be solvable similarly to code annotations, which use comments (`.c`, `.c1` or `.cm`) in the source language for marker placement, but variables are a much, much harder problem to solve. The reason is that there's no canonical lexeme or pattern that is output by Pygments that can be used to identify variable markers. Thus, marker identification would probably need to implemented as a pre-processor to Pygments, but I personally think that it's a huge task to make this work for all languages and in a simple way with good DX. I might re-evaluate this in the future, but currently I'll consider it out-of-scope.

**Comment by userbradley** [comment]
Appreciate the effort on this one! I feel like this is more of a full fledged CMS type of thing!

**Comment by kvanzuijlen** [comment]
Google has some interesting documentation for their implementation: https://developers.google.com/style/placeholders. Might be handy if/when this functionality gets reconsidered.

**Comment by userbradley** [comment]
Agreed, I once found the python package they use but since can't find it!

I need to have a look again I think 

I'd love for this to be implemented in some sort, it would make my documentation a lot cleaner

**Comment by kvanzuijlen** [comment]
As far as I can tell they're using [Eleventy](https://www.11ty.dev/) with some proprietary (markdown-it) plugin sadly :(

**Comment by squidfunk** [comment]
I currently have no bandwidth to come up with a solution from scratch, but if somebody finds a Markdown extension or plugin that implements this, I'd be happy to look into how they did it and if we can adapt or port it to Material for MkDocs.
