### ISSUE TITLE
Feature Request: Sidebar search filter

### ISSUE THREAD

**Issue by josegonzalez** [squidfunk/mkdocs-material#4382]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

This is something I noticed in the Hashicorp docs. There is a [sidebar filter](https://www.nomadproject.io/docs) (under the version dropdown) that folks can use to filter what is shown in the sidebar. While I don't think it should be the default (especially for smaller doc sites) it can be useful for larger doc sites (or those with many embedded pages).

### Use Cases

The [dokku docs](https://dokku.com/docs/getting-started/installation/) have a very long sidebar, and it would be nice to be able to filter things.

### Screenshots / Mockups

Attached is a screen recording of the usage of the [docs site](https://www.nomadproject.io/docs):

https://user-images.githubusercontent.com/65675/191110606-4af37f0b-81ab-4781-9658-49987455e740.mov

**Comment by squidfunk** [comment]
I've evaluated this feature request and would currently not consider it a good fit, because we already have the unified site-wide search as an entrypoint. While I understand that filtering the navigation might sometimes yield a little more information than using the search which lists pages by relevance, it's probably not generalizable enough to provide good value for all users. It might be too specific for API documentation.

We might re-evaluate in the future, but currently, this feature is considered out-of-scope.

**Comment by squidfunk** [comment]
Also note that this is loosely related to #3787, which IMHO is more generalizable.
