### ISSUE TITLE
Visual Artefacts when using dark themes with Remote Desktop

### ISSUE THREAD

**Issue by Sgtmoustache** [squidfunk/mkdocs-material#4493]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using the "slate" palette scheme, I am getting visual artifacts (lighter gray boxes) when looking at the generated website through Microsoft Remote Desktop (RDP).

I'm not really sure how to fix this unfortunately. Any help would be appreciated!

### Expected behaviour

![Capture2](https://user-images.githubusercontent.com/16720916/195647036-028a163f-abec-47ca-82b5-6b89135c0ff2.PNG)

### Actual behaviour

![Capture](https://user-images.githubusercontent.com/16720916/195646332-9869bb3e-d5f6-4e06-bd9d-629a8ee85bdd.PNG)

### Steps to reproduce

1. Open RDP connection to remote desktop.
2. Look at any Material website with dark theme ON.

### Package versions

- Python: 3.10.6
- MkDocs: 1.3.1
- Material: 8.5.3

### Configuration

```yaml
Any configuration that uses the 'slate' scheme.
```

### System information

- Operating system: Windows 10
- Browser: Edge, Firefox, Chrome

**Comment by facelessuser** [comment]
I don't think there is anything that Material can do about visual artifacts in remote desktop sessions, that's a remote desktop issue. It is known that remote desktops can cause visual artifacts when viewing anything. I would do some research on remote desktops and visual artifacts to learn more and how to mitigate such issues.

**Comment by Sgtmoustache** [comment]
A workaround that might work is to create my own palette scheme for the dark theme (that will not use hsla color functions).
I'm having trouble overwriting the background color into my palette definition in my CSS file. Any idea?

**Comment by squidfunk** [comment]
Thanks for reporting. This issue is entirely unrelated to Material for MkDocs and nothing we optimize for.

**Comment by Sgtmoustache** [comment]
If anybody encounter this issue, my fix was to overwrite these value in CSS. RDP seems to have issues with the way we calculate and render the default dark theme.

```css
[data-md-color-scheme="default"] {
    --md-primary-fg-color: #5a5a5a;
}

[data-md-color-scheme="slate"] {
    --md-primary-fg-color: #5a5a5a;
    --md-default-bg-color : #2c2b2b;
}
```

**Comment by drzbida** [comment]
I am sorry for using this thread, but this is the only place related to this issue you can find on search engines if you have this exact problem. This is indeed related to RDP, as i had this issue in terminals such as alacritty / wezterm. I followed the steps mentioned here https://learn.microsoft.com/en-us/answers/questions/480029/rdp(server)-colors-is-corrupted-with-nvidia-latest by Eleven Yu, although the problems look nothing alike, this fixed OP's screenshots for me. 

Copy pasting the steps, since microsoft links tend to stop working after a few years:

Computer Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Remote Session Environment
Limit maximum color depth
Use hardware graphics adapters for all remote desktop services sessions
Limit maximum display resolution (i did not personally need this)
Prioritize H.264/AVC 444 graphics mode for Remote Desktop Connections
Configure H.264/AVC 444 hardware encoding for Remote Desktop Connections 

@Sgtmoustache tagging you in case it might still help after two years :)

**Comment by AndrewElans** [comment]
Thanks, @drzbida. I had color artifacts in visual studio code which are now gone after your advice.

I have enabled only "Limit max color depth" and "Prioritize H.264..."

For others: run "Edit Group Policy" on your RD and try different setting as advised above.

**Comment by Sgtmoustache** [comment]
Thanks a lot @drzbida! I was still having this issue in a lot of other websites and applications. I will give it a try :)

**Comment by drzbida** [comment]
After some more testing, the Prioritize H.264... option causes some other annoying issues for me, like text blinking or blurry. Instead, I've disabled the option again and on the same settings page maxed out the settings related to compression and image quality for RemoteFX (I've set no compression for RDP and image quality lossless, didn't try anything else) and this one seems to have no drawbacks
