### ISSUE TITLE
Icon for external links

### ISSUE THREAD

**Issue by ojacques** [squidfunk/mkdocs-material#4513]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The [privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#external-links) allows to customize links to external sites, add attributes and the target.  
This feature request is about having an icon to be added next to the link so that the reader can realize that the link is an external link.

An example of an icon is the one from font-awesome: https://fontawesome.com/icons/up-right-from-square.  
![image](https://user-images.githubusercontent.com/5385290/196618439-729dcd9b-5828-4fe3-ae30-bbe747daaf17.png)

**Note**: @squidfunk mentioned that this is already possible with some extra CSS, as documented in [this blog post](https://christianoliff.com/blog/styling-external-links-with-an-icon-in-css/). The ask is to have this natively.

### Use Cases

Before clicking an external link, the reader should be informed that he is leaving the site to consult an external link.

**Comment by squidfunk** [comment]
Thanks for suggesting. As you mentioned, this is trivial to achieve with custom CSS, and some users (including me) might not like styled external links. Providing this as a theme option is overkill, given how simple it is. Closing as out of scope.

**Comment by afoeder** [comment]
ℹ️  For those who found this issue, like me, here's what I did (like @squidfunk suggested, but here's the steps):

- set up [Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css)
- Define this CSS top level:
  ```css
  .md-typeset a[href^="//"]::after,
  .md-typeset a[href^="http://"]::after,
  .md-typeset a[href^="https://"]::after {
      content: "↗";
      font-size: smaller;
      margin-left: .2em;
      vertical-align: top;
  }
  ```

You get the gist; adjust to your personal liking. The arrow is a Unicode North East Arrow U+2197.

**Comment by curry684** [comment]
> Providing this as a theme option is overkill, given how simple it is. Closing as out of scope.

This is no longer simple, as it was broken in a patch release....

See https://omines.github.io/antispam-bundle/, where I used the [blogpost trick](https://christianoliff.com/blog/styling-external-links-with-an-icon-in-css/). Since a trivial bundle update the arrows turned up all over the docs site (and I noticed only yesterday).

Elimination via Docker versions showed this broke between 9.5.4 and 9.5.5, which eventually brought me to [this comment](https://github.com/squidfunk/mkdocs-material/issues/6582#issuecomment-1916014583) explaining how the entire URL system was rebuilt with B/C breaks and without B/C options. Looks like not that many people depended on it luckily   ;)

Now that URL matching doesn't work unless I hardcode the live deployment hostname - can we just get a standards-compliant `rel="external"` on non-internal links?

**Comment by squidfunk** [comment]
> Now that URL matching doesn't work unless I hardcode the live deployment hostname - can we just get a standards-compliant rel="external" on non-internal links?

Sure, that's a great idea. Could I maybe ask you to create an issue / feature request at [MkDocs](https://github.com/mkdocs/mkdocs), since Material for MkDocs only consumes what MkDocs produces – the Markdown to HTML translation, which is the part where this functionality needs to be added is [here](https://github.com/mkdocs/mkdocs/blob/7e4892ab2dd4a52efd95a9de407eee63310e0780/mkdocs/structure/pages.py#L263-L292), and is done entirely as part of MkDocs, not Material for MkDocs.

I'm not a core maintainer of MkDocs, but judging from my knowledge of the internals, I'd guess that this could be very easily added in the [`_RelativePathTreeprocessor`](https://github.com/mkdocs/mkdocs/blob/7e4892ab2dd4a52efd95a9de407eee63310e0780/mkdocs/structure/pages.py#L346), which detects and replaces all links with their target URLs. Adding a check for externals URLs [here](https://github.com/mkdocs/mkdocs/blob/7e4892ab2dd4a52efd95a9de407eee63310e0780/mkdocs/structure/pages.py#L370-L371), where the node is already available, and then adding `rel=external` should be a few lines of code.

**Comment by z-aki** [comment]
Created a plugin for this https://github.com/z-aki/mkdocs-plugin-open-external-links-in-new-tab .
