### ISSUE TITLE
squidfunk.github.io Emoji Search No Results

### ISSUE THREAD

**Issue by bwalchen** [squidfunk/mkdocs-material#4591]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Intro
Hi folks I found an issue with the `squidfunk.github.io` wiki site. I'm assuming this is the best place to file an issue as the code button in the top right redirects to this repo. Feel free to correct me if that's wrong. Absolutely love this project thank you for your hard work! 😊

### The Problem
When browsing to [https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search) and entering a term in the emoji search bar no results are returned.

Tested on multiple machines and networks.

### Expected behaviour

Emoji results would populate.

### Actual behaviour

No emoji results are returned.

### Steps to reproduce

1. Browse to [https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search) 
2. Click on emoji search bar and type the any term such as `arrow`
3. Note that no results are returned.

### Package versions

https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search 

### Configuration

```yaml
https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
```

### System information

- Operating system: MacOS 12.5.1
- Browser: Google Chrome Version 103.0.5060.134 

Tested on multiple machines and networks.

**Comment by perpil** [comment]
I'm seeing the same thing with FF 106.0.3 and 404's on javascript on the same page.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/97474956/199851067-135fb298-6f3a-47ba-9471-481686d8dee3.png">

You might be able to search [this file](https://github.com/squidfunk/mkdocs-material/blob/941d634b781d60929fb5d8c7497e598422576814/docs/schema/assets/icons.json) for the names temporarily.

**Comment by davidbgk** [comment]
I confirm that the bundling is not anymore linked properly.

The path is `https://squidfunk.github.io/mkdocs-material/overrides/assets/javascripts/bundle.d665d539.min.js` and it should be `https://squidfunk.github.io/mkdocs-material/assets/javascripts/bundle.d665d539.min.js` (extra `/overrides/` in the URL path).

It might be because of that line 10 hours ago: https://github.com/squidfunk/mkdocs-material/commit/713bf41403ed56eb1e6290ee52afd2d7a809fa13#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R39 which requires to update that line (and similar ones): https://github.com/squidfunk/mkdocs-material/commit/713bf41403ed56eb1e6290ee52afd2d7a809fa13#diff-92f213419ca62ddab00b346ddb611dad07668aa1ce58949e19a2b5278476a61dR19

**Comment by squidfunk** [comment]
Thanks for reporting – very much unintentional, I'll fix it asap 😅

**Comment by squidfunk** [comment]
Fixed! I've simplified the whole theme development process, but deploying our own docs with Insiders, we have to jump through several hoops due to custom overrides. If you refresh your browser, it should now work again.
