### ISSUE TITLE
C4 Model with Structurizer

### ISSUE THREAD

**Issue by SilentGlasses** [squidfunk/mkdocs-material#4624]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I started reading and plan to put this in place for our internal documentation at work and was wondering if this is supported or if it can be added to expand on the features of this platform.

https://c4model.com/
https://structurizr.com/

### Use Cases

Better charts for visualising software architecture and more.  Mermaid is great but this provides way more abilities.

### Screenshots / Mockups

The sites have examples to reference.

**Comment by squidfunk** [comment]
Thanks for suggesting. Material for MkDocs tries to be as agonistic as possible when choosing what to support. Mermaid.js is one of the most widely used Open Source diagram solutions, which is why we've chosen to support it. Structurizer is too specific for us, but the CLI seems to be able to export to Mermaid:

> A command line utility designed to be used in conjunction with the Structurizr DSL, supporting pull/push via the web API and exports to a number of formats including PlantUML and Mermaid.

As such, we consider it out-of-scope for this project.

**Comment by SilentGlasses** [comment]
Understood, thanks for replying.
