### ISSUE TITLE
SVG display bug in sidebar

### ISSUE THREAD

**Issue by do-me** [squidfunk/mkdocs-material#4677]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

It seems like the sidebar is having issues displaying SVGs correctly. The main homepage is showing the SVG correctly instead. I tried to check the SVG for issues but neither on inkscape nor browsers nor any online SVG displayer appeared to have problems. 

I checked the CSS but as far as I understand it does not interfere with the SVG itself. 

I created a minimal repo for reproduction [here](https://github.com/do-me/mkdocs-svgbug) and a live example [here](https://do-me.github.io/mkdocs-svgbug/).

On the landing page everything looks fine (a normal post box SVG)
![image](https://user-images.githubusercontent.com/47481567/203999955-87fdf713-30a0-4f86-8a17-d5830b04ec8b.png)

However in the sidebar (when width is limited): 
![image](https://user-images.githubusercontent.com/47481567/204000330-7fc0637a-8cff-45c0-8f94-73a7d30bffcd.png)

Why is it rendered differently?

### Expected behaviour

Consistent behavior, correct display

### Actual behaviour

Inconsistent behavior, wrong display in sidebar

### Steps to reproduce

See above, clone repo, run mkdocs.

### Package versions

- Python: `3.7.5`
- MkDocs: `1.4.2`
- Material: `8.5.10`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
  custom_dir: docs/theme_override_home/
  icon:  
    logo: briefkasten  # see linked repo for all files
```

### System information

- Operating system: Windows & Linux
- Browser: Chrome/Edge/Firefox

**Comment by squidfunk** [comment]
Thanks for reporting. That looks super weird. I've never seen something like this. I've invested some time to debug this issue, tried to disable JavaScript, tried to remove CSS rules etc. to no avail. It could be an issue with the positioning of the element, since, when you remove _all_ CSS, the issue is gone (but the site too). My best guess is that it's a rendering bug that is caused by InkScape's output. Thus, I don't think there's much we can do rather than consider this not fixable.

Try to reference the image externally, i.e. don't declare it as an icon, but use it as an [external image](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo):

``` yaml
theme:
  logo: docs/briefkasten.svg
``` 

Other than that, if you come up with a fix, i.e. some lines we can remove from or add to our CSS that keep the site in the same shape, I'm happy to merge a PR. However, we need to make sure that other users are not impacted.

**Comment by do-me** [comment]
The only way I could make it work eventually is by adding the SVG to the root directory and referencing it as external Image, thanks!
  
```
site_name: My Docs
theme:
  name: material
  custom_dir: docs/theme_override_home/
  logo: briefkasten.svg
```

![image](https://user-images.githubusercontent.com/47481567/204025230-f487c4d0-adea-4103-ac4a-005203e93884.png)

Anyway, I think there might be some kind of rendering issue (or simply difference) when referencing through the `.icons` folder.

**Comment by squidfunk** [comment]
When referenced through the `.icons` folder, the SVGs are inlined into the build. This is all we do. Thus, it's still some kind of side effect between Ink Scape's SVG, our CSS, and the browser. Glad it works now, for complex images this is definitely the recommended way.
