### ISSUE TITLE
Sidebar doesn't focus current page with certain resolutions

### ISSUE THREAD

**Issue by guusw** [squidfunk/mkdocs-material#4694]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I've only noticed this issue occurring on Firefox (currently on 107.0), I managed to reproduce it in chromium too although harder to get.
Resizing the window (as small as possible helps)

### Expected behaviour

Correct sidebar scrolling

### Actual behaviour

Sidebar doesn't scroll to current page on some resolution/page combinations

I added some logging and it seems sometimes the scroll function picks the wrong elements, not sure how to fix though.

Correct scrolling:
<img width="1645" alt="ScrollYes" src="https://user-images.githubusercontent.com/16842774/204788604-39d3c1fd-8d90-4f28-82d9-643eb6c894b0.PNG">

Wrong scrolling:
<img width="1652" alt="ScrollNo" src="https://user-images.githubusercontent.com/16842774/204788598-1ee567ed-a73e-4de5-8698-aef6ea1b4009.PNG">

### Steps to reproduce

- Have a long sidebar with lots of items
(- Some items also have a TOC with 1 or 2 items, although it doesn't seem to matter as it happens on those without on firefox)
- Go through the items at different resolutions, small width / height for seems to be consistent on firefox
- 

### Package versions

- Python: Python 3.10.4
- MkDocs: 1.4.2 
- Material: directly from git commit 39124f991 (8.5.10)

### Configuration

Check https://docs.fragcolor.xyz/docs/shards/Math/Scaling/ for an example of a non-working build.
Check https://github.com/guusw/mkdocs-bugs/tree/scroll-bug for source files that should be able to reproduce the issue

### System information

Firefox 107.0 (Windows)
Chromium Version 109.0.5370.0 (Developer Build) (64-bit) (Windows)

**Comment by squidfunk** [comment]
So first of all, thanks for reporting and the excellent reproduction. It made it very simple to find the cause 👏

Now that was an interesting case, as I haven't seen such a large navigation before. Good to have that for testing. I _think_ I have a fix in 26c08f1f3, as I could reproduce the problem in Firefox (and even Chrome!) before, and with the fix applied it's gone. I've pushed it to the v9 branch, so you need to install the v9 beta to check if the issue is gone. More info in #4714, very simple.

With instant loading, repositioning is pretty smooth, but without it's a little jaggy. I'll revisit sidebar positioning at some point, but given that what you have really is an edge case, I currently don't consider it a priority. However, improving smoothness is always something I'm aiming for.

**Comment by squidfunk** [comment]
Hmm. I can't reproduce it anymore. I'm not sure how to proceed, as logically, I don't see how it can happen anymore.

**Comment by guusw** [comment]
I'll check again later, maybe I did something wrong updating/building.
