### ISSUE TITLE
Sidebar subnav disappearance

### ISSUE THREAD

**Issue by davidandgoliath** [squidfunk/mkdocs-material#47]
When a single mkdocs document has two (or more) h1 headers (# in markdown) — any headers beneath the second h1 do not show up in the subnav.

Perhaps it's a hint I should use less h1s (single # in markdown), but, assuming it could also be a bug. Might not be one in the rework, haven't had a chance to verify yet.

**Comment by squidfunk** [comment]
Yeah, this is kind of a hack to get the table of contents working correctly, because the title of the page is already shown in the sidebar and it would be redundant showing it a second time in the table of contents.

It relies on the fact that it's only valid HTML to use one `h1` tag per content section that is the actual page. Multiple `h1` tags must be nested inside `article` tags which are not part of the generated Markdown, so only one `h1` is allowed per page. This `h1` get's parsed in the template and is used within the header.

It might be a bit different with the rework version, I have to check again, but for now it's not possible, I'm sorry. However, it's not valid anyway.

**Comment by davidandgoliath** [comment]
Thanks! I trust your judgement, I'll adjust my workflow.
