### ISSUE TITLE
Blog post do not have a table of contents with toc.integrate enabled.

### ISSUE THREAD

**Issue by tylernguyen** [squidfunk/mkdocs-material#4724]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

With `toc.integrate` enabled, blog posts do not have a table of contents.

### Expected behaviour

Preferably, the table of the contents should appear on the left side of the blog post, above author information and metadata.

### Actual behaviour

Blog posts lack a TOC, appearing neither left or right.

### Steps to reproduce

Enable `toc.integrate` within `mkdocs.yml`

### Package versions

- Python: `3.11`
- MkDocs: `Insiders commit 78de2df`
- Material: `1.4.2`

### Configuration

```yaml
features:
   - toc.integrate
```

### System information

- Operating system: Windows 11
- Browser: Firefox

**Comment by squidfunk** [comment]
Thank for reporting. Yes, that's not currently not supported, because there's no place where the table of contents can live in the navigation. I'm not sure how it should behave. We _could_ exempt the integration logic for blog posts, but that would kind of be inconsistent.

**Comment by tylernguyen** [comment]
Preferably, I would want for the TOC to live above author and metadata info on the left. There is too much white space on the left. Something of this order:

- TOC
- Author
- Metadata
- Related Links

Hopefully, this isn't too hard to integrate. But if it is, I guess the ability to example integration logic for blog posts can be a temporary fix until a better solution is thought of.

**Comment by squidfunk** [comment]
Hmm, it would visually likely deviate from the current integration in the navigation, as there's no top-level navigation item to position it under. I'll evaluate this, but I can't give a guarantee that this will be implemented eventually.

**Comment by squidfunk** [comment]
So turns out – it's not trivial. Adding it to the left sidebar, which is a third sidebar will induce several problems. Thus, I've disabled `toc.integrate` for blog posts, for now in [`1f0c8baec`](https://github.com/squidfunk/mkdocs-material-insiders/commit/1f0c8baecc8ea178abf62cb2d456fe36a99b0d3c). This may change in the future. The blog post templates are definitely going to be revamped at some point, the current version being the first iteration. Your feedback is very valuable and it will be considered when I work on the blog templates again.

**Comment by tylernguyen** [comment]
The latest commit seems to disable `toc.integrate` universally. Can you please double check so that it only disables `toc.integrate` for blog ports? As I still very much love the layout, styling, and spacing that `toc.integrate` gives me.

**Comment by squidfunk** [comment]
Oh, thanks for noting. I'll take a look.

**Comment by squidfunk** [comment]
I've reverted the changes in [`ee12d9f95`](https://github.com/squidfunk/mkdocs-material-insiders/commit/ee12d9f95a67be22f236d27b285fe88ca72663e2), as this needs some more thought. I assumed that MkDocs would create fresh copies of the configuration to pass to the templates, and this configuration is immutable, but it isn't. This also means that you can probably change values from the templates themselves. I may have a better idea how to solve this problem.

**Comment by squidfunk** [comment]
Fixed in [`f5b77bf23`](https://github.com/squidfunk/mkdocs-material-insiders/commit/f5b77bf2302223b92ee3f35b0820e3c55daf021d). The table of contents is now moved to the left when `toc.integrate` is enabled. I'll revisit the blog layout and sidebar later this year, trying to improve the current situation. However, this can be considered fixed for now:

<img width="254" alt="Bildschirmfoto 2023-01-08 um 11 32 27" src="https://user-images.githubusercontent.com/932156/211191478-45f2242f-5584-43c4-ab0c-a63bb66d4c3c.png">

**Comment by squidfunk** [comment]
Released as part of [9.0.3+insiders-4.27.1](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.0.3-insiders-4.27.1).
