### ISSUE TITLE
Feature suggestion: Page-specific toc depth

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#4827]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Using Python-Markdown's built-in [toc](https://python-markdown.github.io/extensions/toc/) extension, you can use the `toc_depth` option to define the range of section levels to include in the table of contents, e.g., only include headings 1-3.

However, this is a global option that applies to all pages in your project. If some of the pages in your project are very complex, while others aren't, this may not be ideal. You may want to define, e.g., a toc depth of 2 for your complex pages (to minimize the length of the toc), and a toc depth of 4 for all other topics.

This isn't possible by default, but it's actually pretty easy to implement in any template.

Simply override the `toc-item.html` partial and add the following if-clause:

```jinja
{% if not page.meta.toc_depth or toc_item.level <= page.meta.toc_depth %}
<li class="md-nav__item">
...
</li>
{% endif %}
```

Now, you can set the page-specific toc depth via front matter:

```markdown
---
toc_depth: 4 
---
```

Note that this only supports integer values setting the bottom section level (`<h1>..<hn>`). The built-in `toc_depth` option is a little more sophisticated, also allowing to define the top and bottom level, e.g., `"2-4"`. I've never used this though, so it's okay for me.

Maybe you want to add this functionality to Material.

### Use Cases

See description.

**Comment by squidfunk** [comment]
Thanks for suggesting. Since MkDocs uses the table of contents extension to extract the sections of a document, it would be a more natural fit, and thus much better idea to add this to MkDocs itself. MkDocs already has the metadata of a document available when determining the title of a document – letting the user override `toc_depth` as part of `meta` would just be a natural extension that doesn't need any adjustments in templates.

I suggest proposing this to MkDocs.

**Comment by wilhelmer** [comment]
I can see that. I don't think it's worth implementing in MkDocs though, especially when it can be done with a oneliner in any template (with the given limitations).

PS: I'm starting to think it would be nice to have some Wiki page for people to showcase their best template "tricks" / "hacks" / whatever you want to call it. Stuff like this that may be useful for more than 1 user, but not useful enough to go into an official template or even MkDocs.

PPS: I never realized that MkDocs directly uses the toc extension. Reminds me of the [curious case of the meta extension](https://github.com/mkdocs/mkdocs/discussions/2939). So the [Material docs](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=toc#table-of-contents) may not be accurate on this extension as well - you don't have to "Enable it via `mkdocs.yml`". If you omit `markdown_extensions: - toc`, Material still renders the toc. You only have to do that if you want to change the settings.

**Comment by squidfunk** [comment]
Well, if this project has told me one thing, it's that if you implement half-baked solutions, it's definitely coming back to you. Thus, my decision. As you said, it can be trivially implemented by overriding the [`toc-item`](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/toc-item.html) partial, if desired.

Regarding PS: hmm yes, but I'm not keen on adding a Wiki here. Wikis degenerate too quickly, which is why many people using Wikis (e.g. Confluence) turn to solutions like Material for MkDocs or Docusaurus.

Regarding PPS: correct, it's one more thing that's not documented (at least I don't know where). I haven't tested it without the `toc` extension, but if that's true, we can change the documentation to reflect that. PR appreciated!

**Comment by axieum** [comment]
I am also looking to reduce the table of contents depth specifically for my 'Changelog' page. As each version has the subheadings "Features", "Bug Fixes", "Breaking Changes", etc. which bloats the already large table of contents.

<details>
<summary>Example of a problematic table of contents</summary>

![image](https://user-images.githubusercontent.com/7577851/216770721-482dec2a-a398-4ea1-bda9-143748d0cf22.png)
</details>

It seems that this issue was raised under mkdocs/mkdocs#1838, to which @waylan commented that it may be easier for the theme to control this feature. This was a while ago, so maybe we could revisit whether it's the theme or MkDocs responsibility to handle this table of contents options per page.

I agree with @squidfunk in that it would make more sense to add this to MkDocs itself, rather than specific themes like this project.

**Comment by ITJamie** [comment]
I wonder would this be possible with https://github.com/aklajnert/mkdocs-simple-hooks
Ive seen it used to change the edit_uri based on metadata in the page https://github.com/renovatebot/renovatebot.github.io/pull/187/files

**Comment by LandonTClipp** [comment]
For posterity, I was able to resolve this with an override. Add a file `overrides/partials/toc-item.html` and write the HTML:

```html
<li class="md-nav__item">
    <a href="{{ toc_item.url }}" class="md-nav__link">
      <span class="md-ellipsis">
        {{ toc_item.title }}
      </span>
    </a>
  
    <!-- Table of contents list -->
    {% if toc_item.children %}
      <nav class="md-nav" aria-label="{{ toc_item.title | striptags }}">
        <ul class="md-nav__list">
          {% for toc_item in toc_item.children %}
          {% if not page.meta.toc_depth or toc_item.level <= page.meta.toc_depth %}
            {% include "partials/toc-item.html" %}
          {% endif %}
          {% endfor %}
        </ul>
      </nav>
    {% endif %}
  </li>
```

Add the front matter to your document:

```
---
toc_depth: 3
---
```

Now it will only render headers up to level 3.

References:

- https://stackoverflow.com/questions/63828084/mkdocs-how-can-i-specify-toc-depth-for-a-single-document
- https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials
- https://github.com/squidfunk/mkdocs-material/blob/9.5.3/src/templates/partials/toc-item.html

Ensure you have the overrides enabled in your config:

```yaml
theme:
  name: material
  custom_dir: overrides
```

**Comment by atk-flywheel** [comment]
> I can see that. I don't think it's worth implementing in MkDocs though, especially when it can be done with a oneliner in any template (with the given limitations).

@wilhelmer Can you share the simple one-line change you referred to for solving this?  I see the post by @LandonTClipp which is helpful but is far more than a simple one-liner.

**Comment by wilhelmer** [comment]
I was referring to my original post:

> Simply override the `toc-item.html` partial and add the following if-clause:
> 
> ```jinja
> {% if not page.meta.toc_depth or toc_item.level <= page.meta.toc_depth %}
> <li class="md-nav__item">
> ...
> </li>
> {% endif %}
> ```

It's a two-line change 😄 Essentially, you wrap the entire file in these two lines:

`{% if not page.meta.toc_depth or toc_item.level <= page.meta.toc_depth %}`

and 

`{% endif %}`

Hope that helps!

**Comment by zobweyt** [comment]
Here's the rewritten version of @LandonTClipp with a cleaner markup:

```jinja
<!-- Table of contents item -->
<li class="md-nav__item">
  <a class="md-nav__link" href="{{ toc_item.url }}">
    <span class="md-ellipsis">
      {{ toc_item.title }}
    </span>
  </a>

  <!-- Table of contents list -->
  {% if toc_item.children and (not page.meta.toc_depth or toc_item.level <= page.meta.toc_depth) %}
  <nav class="md-nav" aria-label="{{ toc_item.title | striptags | e }}">
    <ul class="md-nav__list">
      {% for toc_item in toc_item.children %}
        {% include "partials/toc-item.html" %}
      {% endfor %}
    </ul>
  </nav>
  {% endif %}
</li>
```

In this version, the table of contents list is included only when necessary, ensuring cleaner markup.
