### ISSUE TITLE
Feature suggestion: Filter page TOC to show headers in active content tab only

### ISSUE THREAD

**Issue by jseldess** [squidfunk/mkdocs-material#4828]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Content tabs are wonderful. However, when you nest headings under tabs, the page TOC doesn't filter based on the active tab. For example:

```
=== "Tab 1"

    ## Step 1

    ## Step 2

=== "Tab 2"

   ## Step 1

   ## Step 2
```

This results in a TOC like:

```
Step 1
Step 2
Step 1
Step 2
```

Instead, it would be wonderful if the TOC could filter based on the active tab. 

### Use Cases

This would make content tabs significantly more useful and flexible in that you add toggle options for larger portions of tutorials.

**Comment by squidfunk** [comment]
Thanks for suggesting. This was already requested in #3376, but since this would not work without JavaScript, as we don't know in the table of contents which headline is rendered in an (in)active tab, I'm not considering adding this functionality to Material for MkDocs. Also, the page would likely flicker on load when we detect which tab is active.

See https://github.com/squidfunk/mkdocs-material/issues/3376#issuecomment-998561286 for how to add headlines without letting them shop up in the table of contents.

**Comment by jseldess** [comment]
Sorry for the duplicate request, @squidfunk. And thanks for the quick response.
