### ISSUE TITLE
Nested Tags

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [squidfunk/mkdocs-material#4839]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

A simple idea- Nested tags.

``` yaml
tags:
    - subtopic 1
    - subtopic 2
```

In the above case, the ["tags" page](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#adding-a-tags-index), would show something such as...

``` markdown
## subtopic 1
* Link to page 1
* Link to another page
## subtopic 2
* more links
```

But, lets say- you have a ton of tags, and would like to better organize them for your audience.

``` yaml
tags:
    - parent_topic/subtopic 1
    - parent_topic/subtopic 2
```

Now, instead of seeing

``` markdown
## subtopic 1
## subtopic 2
```

We will see:

``` markdown
## parent_topic
### subtopic 1
* Link to page 1
* Link to another page
### subtopic 2
* Link to more pages
```

I would propose the display have a configuration option to determine if the parent_tag should be displayed on the actual post itself. So, users can have the options if they would like to see "parent\child", or just "child"

### Use Cases

better organization of tags, for sites which may have large numbers of distinctly different sets of tags.

For my personal site/blog- I have a wide range of topics ranging from software development, home automation, automotive performance, machining/welding/etc.

This would allow me to say, better group these tags together, so, viewers interested in a specific genre, can more quickly browse to it.

**Comment by squidfunk** [comment]
Thanks for suggesting! This was already asked a few times, but nobody has yet crafted up a solid proposal. Could you please provide an example in a zip with many tags? We need to collect some "problem sets" (= tag configurations with many tags) before we can start to implement, because, as always, we would try to cater to as many authors and users as possible.

**Comment by XtremeOwnageDotCom** [comment]
@squidfunk I can do that.

I'll see if I can make a "somewhat" functional branch, which achieves the goal... or, at least, some of the backend logic. But- as a warning, I am not good at making pretty things! (on the frontend)

**Comment by squidfunk** [comment]
No worries! Would be good to first collect and understand different use cases, so we can gravitate towards a proposal before implementing. Otherwise, I'd have to turn down the PR, because it's too specific, as with #4751. Material for MkDocs is used by so many users with different needs, we need something that is flexible and works in at least 90% of the cases.

**Comment by squidfunk** [comment]
Please see the announcement in #6517.

**Comment by squidfunk** [comment]
We've actually implemented this functionality as part of the new tags plugin!

**Comment by XtremeOwnageDotCom** [comment]
> We've actually implemented this functionality as part of the new tags plugin!

I have been watching! Thanks! 

Also, stop working on X-mas!
