### ISSUE TITLE
Search input is disappeared after update

### ISSUE THREAD

**Issue by andreygladilin** [squidfunk/mkdocs-material#4851]
### Context

I use mkdocs material (9.0.3)+mike (1.1.2)+gitlab pages. Unfortunately, after regular update of my documentation on 10th of Jan 2023 the Search field is disappeared from my site.

### Bug description

Search input is disappeared after update. I’ve tried switching from 8.5 version to 9.0.3 and vice versa and I should note that 8.5 still works well, but after version update search input is disappeared.

### Related links

- https://squidfunk.github.io/mkdocs-material/getting-started/#installation
- https://squidfunk.github.io/mkdocs-material/upgrade/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
- 

### Reproduction

This bug can be reproduced both locally (mkdocs serve) and on Git Lab Pages when I deploy my documentation with using mike. Moreover, I can see the similar issue when using GitHub Pages, too. 

### Steps to reproduce

Set up mkdocs material
Run `mkdocs serve`

### Browser

Chrome, Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [ ] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by katharinalisalin** [comment]
Thanks for reporting. However, this issue is [incomplete](https://squidfunk.github.io/mkdocs-material/bug-report/#incomplete-issues).

Note that we have new [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/), which are also mentioned in the descriptions in the bug reporting template you filled out. You did not provide a reproduction, which is why we can't look into this issue because it might be a bug, might be related to customizations, or might be a configuration error. 
Please read our new bug reporting guidelines and how to [create a reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

We will reopen this issue when you provide a reproduction.

**Comment by katharinalisalin** [comment]
Thank you for your input.

I understand that you're having trouble, as major version updates can be challenging at times. However, in order to help you, we first need to understand whether the issue is caused by a bug, misconfiguration, or your customizations. Without a [reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/), we can't consider this a bug. Thus, there's no action here to take for us, which is why we closed this issue. As stated, we'll reopen it once the missing information has been provided.

**Comment by eddieleeallen** [comment]
Yes, we are in  the same situation, lost search on two documentation sites in very basic non customized implementation.    Here is the content of our yml file, nothing changed in our site or yml file, yet search disappeared:

Appears one User downgraded to regain search functionality

site_name: ProfitSystem Documentation
site_url: https://bblsystems.github.io/ProfitSystemHelp/
theme:
  name: material
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search:
      lang: 
        - en
        - es

**Comment by squidfunk** [comment]
Without a reproduction, we can't help you. I'm locking this conversation now, since it's going nowhere. If somebody manages to provide to [create a bug report](https://squidfunk.github.io/mkdocs-material/bug-report/) with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/) we are more than happy to fix it, possibly in the blink of an eye.

**Comment by squidfunk** [comment]
We think we found the problem with the help of @facelessuser in https://github.com/squidfunk/mkdocs-material/discussions/4850#discussioncomment-4738699

Our documentation now also mentions the solution in the [upgrade guide](https://squidfunk.github.io/mkdocs-material/upgrade/#changes-to-html-files):

<img width="740" alt="Bildschirmfoto 2023-01-20 um 17 26 59" src="https://user-images.githubusercontent.com/932156/213752010-d5636877-76c5-46a9-8bdb-37bfabe97d5a.png">

In case this doesn't fix the problem, please create a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/) and a new [bug report](https://squidfunk.github.io/mkdocs-material/bug-report/).

**Comment by andreygladilin** [comment]
Yep. I changed `{% if "search" in config["plugins"] %}` to `{% if "material/search" in config["plugins"] %}` in `partials/header.html`    and the search input has returned, but unfortunately tags and other "rubbish" can be seen in search results.

**Comment by squidfunk** [comment]
Please try a clean install of `mkdocs-material` – it may be related to stale data in your environment.

**Comment by eddieleeallen** [comment]
Thanks, we just updated to the latest material and the search returned.
Thank you.
