### ISSUE TITLE
Annotations do not work with a non-default `pygments_style` and `noclasses`

### ISSUE THREAD

**Issue by Vasperous** [squidfunk/mkdocs-material#4861]
### Context

I have a project where I implemented my own dark mode and custom colors etc., recently I have had some issues with the code color and how it shows up in certain areas.  In the end I feel like I am 'fighting' on the theme front so I looked into using a `pygments_style` since it has some of the code themes I am looking for.

I branched my project and started removing all of my custom css.  Once completed I tried using the `pygments_style` option and it worked great.  As I was reviewing the project I noticed that the code annotations worked.

### Bug description

Adding the `pygments_style` and subsequently the `noclasses` option set to `true` causes annotations to not work.

Working:
![image](https://user-images.githubusercontent.com/8703632/212345155-4a12a806-1e7c-4d46-9ebf-a6f926cf1f67.png)

Not working:
![image](https://user-images.githubusercontent.com/8703632/212345230-20848ef1-c7ca-43cf-b0bd-c16e129f8259.png)

### Related links

The first page has the issue at the bottom.

### Reproduction

Apologies, I am using Insiders and it keeps erroring out on the build saying I have to use the non-insiders version which doesn't support the futures I use.

[TestOfflineTypeset.zip](https://github.com/squidfunk/mkdocs-material/files/10412447/TestOfflineTypeset.zip)

### Steps to reproduce

1. Create a project
2. Add the following to the `markdown_extensions`

```
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: default
```

3. Add annotations to a page
4. Run project

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by facelessuser** [comment]
IIRC, the annotations feature works off of classes, so by removing classes, you remove support for annotations. So, you cannot use `noclasses` and annotations together.

I just use CSS to style my code colors properly.

**Comment by squidfunk** [comment]
Thanks for reporting and providing the excellent reproduction! We'll look into it why it wasn't possible to use the `info` plugin with Insiders. Thanks for trying it out! @facelessuser is correct – when `noclasses` is set, Material for MkDocs has nothing to know that an element within a code block contains a comment. From your example:

``` html
<code><span style="color: #008000; font-weight: bold">theme</span>:
<span style="color: #bbbbbb">  </span><span style="color: #008000; font-weight: bold">features</span>:
<span style="color: #bbbbbb">    </span>-<span style="color: #bbbbbb"> </span>content.code.annotate<span style="color: #bbbbbb"> </span><span style="color: #3D7B7B; font-style: italic"># (1)!</span>
</code>
```

Thus, `noclasses` cannot be set. Since programming languages can contain constructs that look similar to code annotations, e.g., `(1)`, we _must_ limit annotations to comments. This also has the nice property that when JavaScript is not available, code blocks can still be copied, since code annotations only reside in comments, not in code, which might make the code block invalid. For reference, those are the classes that are scanned for code annotations:

https://github.com/squidfunk/mkdocs-material/blob/89a77c5c0b42a59ae17850b63dfc5f1d6d6dcf1d/src/assets/javascripts/components/content/annotation/list/index.ts#L74

For this reason, we must consider this issue as not fixable, because the combination of configuration options that is mentioned in the OP does not work, and is likely never expected to work due to the missing information.

**Comment by Vasperous** [comment]
Thank you for the explanation!
