### ISSUE TITLE
Add available query syntax when clicking on the search box

### ISSUE THREAD

**Issue by albtam** [squidfunk/mkdocs-material#4982]
### Description

When a user wants to use the search bar for the first time, it is not clear what special syntax is available (for example [term presence](https://lunrjs.com/guides/searching.html)). It would be great to display this information somewhere (e.g. when clicking on an info button or on a menu below the search bar when the query is empty)

### Use Cases

When I enter my query, I want to make sure I can use all the available syntax "tricks" to improve the returned results

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This was already asked some time ago. I think the best idea is to create a page on our own documentation (Material for MkDocs) and link to that from the search. This means we would only need to translate something like "Learn about the query syntax", and not an entire article explaining how to use the search, since otherwise English would be mixed with the language of the site.

**Comment by squidfunk** [comment]
Closing if favor of #5557.
