### ISSUE TITLE
GitHub issue status rendered 

### ISSUE THREAD

**Issue by userbradley** [squidfunk/mkdocs-material#4988]
### Description

I include a lot of links to GitHub issues on my documentation. The issue I have is that I manually have to link it, and it doesn't look all that nice, as you're just going 

```markdown
Operators

* In
* NotIn
* Exists
* DoesNotExist
* Gt [See #39256](https://github.com/kubernetes/website/issues/39256)
* Lt [See #39256](https://github.com/kubernetes/website/issues/39256)
```

Any time an issue is referenced

I would like to have something similar to how Atlassian (boo!) does it, where when you include a link to a github issue, it displays something like below, with the status

![image](https://user-images.githubusercontent.com/41597815/216782991-8779c02f-f876-47ad-8539-ac4102a6bcac.png)

I know this really is a long shot, and sort of similar to #4332, but I feel like I may not be the only person who has this issue.

### Related links

- [GitHub api on getting an issue](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue)

### Use Cases

Ability to go

"When Issue `#123` is updated, this will be implemented`

and the page will render a small box similar to on confluence

### Visuals

Could be rendered on a new line like:

```makrdown
--<8-- gh:kubernetes/website/39256
```

Or when in a sentance

```markdown

Will be completed when ![](kubernetes/website/39256) is done
```

o

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. So as I understand, [MagicLink](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/), which [automatically links GitHub issue, pull requests and discussions](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#issues-pull-requests-and-discussions) isn't enough, right? You're specifically talking about the statuses and titles that should be rendered. In essence, we need to query the GitHub API. As far as I understand, there are two options:

1. __From the browser__: we'll be quickly running into rate limits resulting in 429s, as GitHub's public API doesn't allow for many requests without authentication. Thus, we would need to expose a GitHub token to the application, which I would consider a security risk, given that token permissions can be changed after the token has been issued.

2. __During the build__: this would probably be a better idea, since we wouldn't have to expose the token, but it would mean that titles, statuses etc. would only be updated when the documentation is rebuilt. Thus, data will become stale. A possible solution to this would be to trigger a documentation build with a GitHub action on every issue update, but that's not a very sustainable and economical solution.

In general, this is something that can be implemented outside of Material for MkDocs. We can then add support via styling, but we're not considering this to be a good fit for this project for the reasons stated. Closing as out-of-scope and/or not possible to implement with reasonable effort.

**Comment by userbradley** [comment]
That's on me. My apologies! Thanks for getting back to me
