### ISSUE TITLE
Inline latex not rendered in toc

### ISSUE THREAD

**Issue by lionpeloux** [squidfunk/mkdocs-material#5004]
### Bug description

I don't know if this is the intended behaviour or not.
I think it would enforce better consistency across documentation if inline latex symbols were rendered correctly in tocs as it is the case in headings.

<img width="1436" alt="latex in toc" src="https://user-images.githubusercontent.com/951626/217243615-65bed3ff-af9f-4bdd-8242-e2910ba63d06.png">

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

see image

### Steps to reproduce

see image

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by katharinalisalin** [comment]
Thanks for reporting. However, this issue is incomplete.

Note that we have new [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/), which are also mentioned in the descriptions in the bug reporting template you filled out. You did not provide a reproduction, which is why we can't look into this issue. Please read our new bug reporting guidelines and how to [create a reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by lionpeloux** [comment]
Hi @katharinalisalin, 

I think there is everything in the description to reproduce the error.

Your bug report template is quite heavy and does not really fit the purpose of this particular issue.
Am I supposed to ZIP a text file with just the inline latex ?? It's non-sens ...

While it is super useful to have strong guide lines ... sometimes it just does not fit the problem.
Unfortunately, this will lead you to miss valuable bug reports like this one and discourage people to contribute (which is obviously not the goal of such a wonderful project).

Please, reconsider reopening my issue.
I can modify it if you tell me what is missing to reproduce the error (even the tittle of the issue is enough in this case).

Thanks
Lionel

**Comment by squidfunk** [comment]
How do you expect that we help you, if you only give us a screenshot? Please put yourself in our shoes – we're maintaining a very popular, huge and complex Open Source project, so we have to have strong guidelines. If you follow the bug reporting and reproduction guide we linked, you will see that it is actually quite straight forward and simple to report a bug. Otherwise, we would have to invest significant time only into creating the preconditions to observe the bug before being able to fix it. Therefore, we need to require our users to cooperate and help us provide those conditions, so we can fix bugs quickly.

Without a proper reproduction, we're not able to help.

**Comment by lionpeloux** [comment]
Hello @squidfunk,

I first want to say thank for this wonderful project. I do really like your work and the way you maintain this project. And I didn't meant to be rude or anything like that. I also do contribute to several projets (some pretty big) and with not the same guide lines.

I am sorry to say that I tried to follow the guide lines but I dropped as I really do not see what is the point to add a .zip file to reproduce the behaviour of the (potential) particular issue I am reporting.

Instead of consuming my and your time producing this .zip I tried to provide a sketch to make things as clear as possible. Sometimes an image is worth hundreds of words and .zip to explain a problem and you would probably agree with that. Moreover, producing this image took some time too and please believe it or not I didn't skip the .zip because I am lazy. Just because I don't see the point.

> I said **your** time too because if I just try to produce this .zip to comply with your request but still don't know what to put inside I will also be wasting your time providing you with confusing informations.

Finally, while (again) I do think it is good practice to have strong guide lines as you do, consider the case of people that does not have the skills or maybe the time (they are not necessarily lazy !) to go through the whole reporting process but still wan't to (kindly) report something that smells wrong. You will miss all of them but their report my still be valuable and precise.

I'm sorry if I have wasted your time while trying to report this (potential) issue. 
This was not my intention.
Have a nice day

**Comment by squidfunk** [comment]
I'm locking this issue, since there's nothing more to add.
