### ISSUE TITLE
The navigation tab is not scrolling.

### ISSUE THREAD

**Issue by hmntsharma** [squidfunk/mkdocs-material#5006]
### Context

When the navigation tab at the top overflows, it does not scroll horizontally.

### Bug description

Overflowing tabs do not scroll horizontally, and there is no button to do so.

It would be difficult to access certain portions of the document without the navigation footer.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10679445/example.zip)

### Steps to reproduce

I took the bare minimum of actions to enable tabs.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Overflow scrolling works for me:

https://user-images.githubusercontent.com/932156/217377198-1b6b238d-bf50-4ab5-b272-bb860e03dc42.mp4

There are no buttons, because this case should happen very, very rarely. A better idea is to restructure your documentation to contain fewer top-level sections, because no matter what we do – add buttons, indicate that there's an overflowing container – you're hiding _very important_ information from users: the top-level structure of your whole site.

For this reason, it's not a case we're optimizing for. Closing as not planned.

**Comment by HarryMichal** [comment]
Just tried this out and the scrolling indeed works but only with touchpads (or in general, direct inputs of side scrolling). Hovering over the navigation bar and scrolling with a scroll wheel on a mouse does not make it scroll. I believe the issue deserves reopening because of this.

I agree with you that restructuring the documentation hierarchy to lower the number of top-level sections is desired. But sometimes that might not be an option (at least not immediately when adopting the use of tabs).

As an extra point, since scrolling is supported, it would increase the discoverability of the hidden navigation items by e.g., adding a shadow at the end of the visible navigation bar, adding an arrow (indicator) or something similar.

Thank you for this very helpful project!

**Comment by squidfunk** [comment]
Again, it's not a case we're optimizing for. If you need those capabilities, you can add those via [additional CSS and JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#adding-assets) – shouldn't be too hard. We might reconsider in the future, but for now, we won't invest more time into this change request.

> I agree with you that restructuring the documentation hierarchy to lower the number of top-level sections is desired. But sometimes that might not be an option (at least not immediately after adopting the use of tabs).

You can change the navigation structure without changing any links in Markdown files. In `mkdocs.yml`:

```
nav:
  - Section 1: section1.md
  - Section 2: section2.md
  - Section 3: section3.md
  - Section 4: section4.md
  - Section 5: section5.md
  - Section 6: section6.md
  - Section 7: section7.md
  - Section 8: section8.md
  - Section 9: section9.md
```

Change it to something like:

```
nav:
  - Tab 1:
    - Section 1: section1.md
    - Section 2: section2.md
    - Section 3: section3.md
    - Section 4: section4.md
    - Section 5: section5.md
  - Tab 2:
    - Section 6: section6.md
    - Section 7: section7.md
    - Section 8: section8.md
    - Section 9: section9.md
```

This way, you're reducing 10 tabs into 2 with an investment of 5-10 minutes.
