### ISSUE TITLE
Automatically insert breadcumbs schema when navigation.path is enabled

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#5091]
### Context

This proposal is about improving the how websites built with Material for Mkdocs are rendered in search engines results and probably a bit of their SEO ranking.

I've been already working on such feature using overriding blocks and partials but I think it's a good idea to implement it out-of-the-box in the theme.

## Functional and technical scenario

When a site author enables `navigation.path` to `theme/features` in mkdocs.yml, the output HTML
embeds a schema (JSON-LD) which documents the breadcrumbs in a comprehensive way for a tool based on semantic web:

```html
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Books",
        "item": "https://example.com/books"
        },{
        "@type": "ListItem",
        "position": 2,
        "name": "Science Fiction",
        "item": "https://example.com/books/sciencefiction"
        },{
        "@type": "ListItem",
        "position": 3,
        "name": "Award Winners"
     }]
}
</script>
``` 

This addition allows search indexers to better "understand" the site structure and where a page is located and search engines return more accurates results to end-users.

## Notes

- Maybe it's not compatible with instant loading?
- if I mostly give here Google references, it's also supported by other search engines, as Bing at least.

## Beyond this issue

If this feature is accepted, I can suggest other auto schema insertion:

- [blog article](https://schema.org/BlogPosting) or [Article](https://schema.org/Article) for the built-in blog plugin
- the [searchbox sitelink](https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox)

### Related links

- [navigation path option](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=bread#navigation-path)
- [schema on schema.org](https://schema.org/BreadcrumbList) and [the validator](https://validator.schema.org/)
- [documentation on Google dev](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb)

Other relevant documentation sections:

- [social cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=social#meta-tags) automatically set meta tags

### Use Cases

For authors, it's a "transparent" improvement of how much their content can be reached through search engines.

For end-users, it's a way to reach out the relevant section they are looking for in documentation websites, even quicker than today.

### Visuals

One way to check against breadcumbs is the Google Search Console:

![image](https://user-images.githubusercontent.com/1596222/221173724-ee7e7c92-c5a8-43b5-9151-f97294230b40.png)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Awesome idea! Note that `navigation.path` and the built-in blog plugin are currently in Insiders, so those would need to be added in the Insiders repository. All other features (search, ...?) can be added here. It should be compatible with instant loading. Please create separate PRs for this. We'll continue discussion in the respective PRs then.

**Comment by Guts** [comment]
Sorry @squidfunk but I'm a bit confused:

- I've not a ready PR and, and to be honest, I wasn't intending to make one
- I created an issue here because issues are not enabled on the Insiders repository

Perhaps I have misunderstood how to ask for a change?

**Comment by squidfunk** [comment]
> If this feature is accepted, I can suggest other auto schema insertion

I misinterpreted this as an offer to create a PR for this. Reopening.

**Comment by jonaharagon** [comment]
I also came here to request this feature.

I was trying to add a BreadcrumbList in [RDFa format](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb#rdfa) instead of JSON-LD because it would be super easy to just add those attributes to `partials/path-item.html`, but I couldn't figure out a way to get the current position of the breadcrumb in the trail to add the `<meta property="position" content="[current position]">` tag, otherwise I'd submit a PR.

**Comment by squidfunk** [comment]
So, I've investigated and have decided that we currently won't consider adding this to Material for MkDocs. The reason is that while I consider JSON+LD and RDF good ideas, it's completely unclear how Google and other search engines actually use them for search results. I've added the site search snippet to our own documentation and have not managed to bring it up on the Google search. Thus, IMHO, the value is questionable. As always, we might reconsider in the future.

Additionally, we're talking about metadata, so if this would be implemented in Material for MkDocs, it would very likely be in the form of a plugin. Metadata is not theme dependent, so it's also an excellent use case for a third-party plugin.

**Comment by jonaharagon** [comment]
I disagree, and I'd ask you to reconsider. Yes, [the sitelinks search box metadata is fairly useless](https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox):

> Google doesn't guarantee that a sitelinks search box will be shown in search results. Additionally, using the sitelinks search box markup doesn't make it more likely that a sitelinks search box will be shown.

`BreadcrumbList`s OTOH are absolutely used in search results, you can find plenty of examples where search results use this metadata, it looks like this where the URL is typically shown:

<img width="412" alt="Screenshot 2023-03-05 at 12 09 13@2x" src="https://user-images.githubusercontent.com/3637842/222977948-c4cf99ff-820c-44f2-8785-0589cffe3e9b.png">

Otherwise the URL is broken up and parsed as breadcrumbs instead, which is not always ideal if your URL structure is not designed for this.

<img width="383" alt="Screenshot 2023-03-05 at 12 15 42@2x" src="https://user-images.githubusercontent.com/3637842/222978218-95bd8886-044c-4a7f-a880-250613e750cd.png">

I also think this should be a theme component, because breadcrumbs are an insiders feature and not an mkdocs feature (AFAIK), which is what this issue is about.

**Comment by squidfunk** [comment]
Fair enough. In order for us to reconsider, I would kindly ask you (or somebody else) to write up a solid proposal what metadata should be supported. This would include what include a list of what metadata properties would make sense to support besides breadcrumbs. This information is essential to gravitate towards a solid implementation. I currently wouldn't regard this as a priority, but if somebody does the conceptual work, I may be willing to implement it.

In any case, this should be submitted a new issue. We won't consider implementing breadcrumbs only.

**Comment by jonaharagon** [comment]
To be honest, having looked at [all](https://developers.google.com/search/docs/appearance/structured-data/search-gallery) the structured data features Google supports, breadcrumbs are the only ones which appear relevant to this project.
