### ISSUE TITLE
Document setting page.meta.meta to add custom meta tags

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#5136]
### Description

The [current documentation](https://squidfunk.github.io/mkdocs-material/reference/?h=meta#on-a-single-page) says to extend the theme to add custom meta tags, but the code at https://github.com/squidfunk/mkdocs-material/blob/master/material/base.html#L70-L74 means that adding the `robots` meta tag from the documentation's example is as simple as adding this to the page's front matter, which feels easier:

```
---
meta:
  - property: "robots"
    content: "noindex, nofollow"
---
```

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
- https://squidfunk.github.io/mkdocs-material/reference/?h=meta#on-a-single-page

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting. Yes, it's still undocumented and must be considered internal, meaning it can change at any time. It's not yet meant for use by authors, so the recommendation is to currently not use it, which is why we won't add it to the documentation. It's likely not in its final form. Otherwise it would have been advertised 😀
