### ISSUE TITLE
Make tag index rendering configurable

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [squidfunk/mkdocs-material#5137]
### Context

The [built-in tags plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#built-in-tags-plugin) allows to define a file to render a [tags index](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#tags-file).

This prints the tag label followed by the pages which contains that tag index:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/95432492/222786386-76e43518-d0e8-4ac7-8fb0-aee5e4aa1ee6.png">

### Description

Make the tag index rendering configurable. For example render a table with one row per page which contains that tag index:

| Tag | Title |
|--|--| 
|Accepted|0001: Demo Architecture Record|

or perhaps:

| Tag | Filename| Title | Description | 
|--|--|--|--|
|Accepted|0001.md|Demo Architecture Record| Bla Bla Bla|

### Related links

- https://github.com/squidfunk/mkdocs-material/discussions/5135

### Use Cases

I have used the tags plugins to summarise ADRs: https://ministryofjustice.github.io/mkdocs-tech-docs-template/ADRs/
These are currently grouped by the ADR status.

It would be preferable if the ADRs were listed by the ADR number: https://docs.modernising.opg.service.justice.gov.uk/adr/

Putting the ADRs in a table means the rows could be sorted and filtered to make them easier to search.

The same logic could apply to other kinds of tags.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Okay, so I've investigated this feature request and yes, it would be possible to make rendering entirely configurable by exposing a template to the author that can be adjusted. However (and that's a big one), we will likely lose the table of contents on the tags index page. The reason is that currently the tags plugin will generate the tags index in Markdown, and feed that to MkDocs, so the table of contents is generated from that. If we allow a custom HTML template, MkDocs will have no way of knowing which entries to put in the table of contents. Even if we would emulate this behavior, we will definitely lose permalinks. I'm not sure what to do, but taking away the table of contents from current users is not something we can do. Thus, from current knowledge, we must consider this as not being feasible, I'm sorry.

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks for explaining!

**Comment by squidfunk** [comment]
Please see the announcement in #6517. I've solved the table of contents problem.
