### ISSUE TITLE
Odd (and hard to reproduce) search behaviour - not finding a page

### ISSUE THREAD

**Issue by StarfallProjects** [squidfunk/mkdocs-material#5363]
### Bug description

I have a page with the title "If" (https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.if/) However, when I search for "If", the page doesn't appear anywhere in the results. 

I have tried adding tags, and search boosting. Current live source is here: https://raw.githubusercontent.com/n8n-io/n8n-docs/main/docs/integrations/builtin/core-nodes/n8n-nodes-base.if.md

When I do a local build, the title, tags etc. are in the `search_index.json` as expected:
![image](https://user-images.githubusercontent.com/10284570/231435128-2a7717f6-5928-42e5-88ca-ac7d002b590a.png)

- Theme version: mkdocs_material-9.0.5+insiders.4.28.1.dist-info
- Python version: 3.10.2

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Search](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/)

### Reproduction

Extremely minimal: [example.zip](https://github.com/squidfunk/mkdocs-material/files/11210479/example.zip) It works here. 

So a bit lost as to why it doesn't with the full site (full site repo: https://github.com/n8n-io/n8n-docs), or with the slightly larger but still pretty minimal reproduction: 
[example.zip](https://github.com/squidfunk/mkdocs-material/files/11210817/example.zip) I have tried removing the whole plugin section, and it still seemed broken.

I'm wondering if there was an issue with the page at some point, which is now resolved, but somehow the search still isn't picking it up? But odd that it would do it locally for both full and minimal site, and on the live site (building on Netlify)

### Steps to reproduce

1. Clone https://github.com/n8n-io/n8n-docs
2. Install Insiders and other requirements
3. Serve site locally
4. Search for "if"

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! The current weighting and ranking is definitely not optimal, which is why I've started to rebuild the search from scratch using a different approach. This should lead to much more stable results and should solve the problems at hand. Your example is super valueable for testing, thanks you for taking the time! I hope to push this out in the coming weeks, but it's still some way to go. [I posted a first prototype on Twitter](https://twitter.com/squidfunk/status/1645023533724991489), if you haven't seen it yet ☺️

**Comment by StarfallProjects** [comment]
@squidfunk thanks. I've drifted away from Twitter a bit.
I was surprised the page didn't show _anywhere_ in the results (not just failing to rank as expected) That's what made me think there was an actual bug.

**Comment by squidfunk** [comment]
Okay, so I know what's happening: actually, the matches that are returned when you search for `if` are words that start with `if` like `iframe` or even `if.` (`.` is not part of your separator). However, `if` is filtered, because it is part of the list of stopwords, and we apply the stopword filter by default for most languages:

https://github.com/squidfunk/mkdocs-material/blob/c0cdb3ca1f7ce1cf85d021f39733c8ea14244c9a/src/partials/languages/en.html#L57

[This is the default behavior of Lunr.js, but has led to confusion in the past multiple times](https://github.com/squidfunk/mkdocs-material/issues?q=is%3Aissue+stopword+is%3Aclosed), which is why I'm considering removing stopword filtering from the default configuration of the new search implementation that is coming up.

In the meantime, you can remove stopword filtering by [overriding the default translations via customization](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#custom-translations). Something like:

``` jinja2
{% import "partials/languages/en.html" as language %} 

{% macro override(key) %}{{ {
  "search.config.pipeline": " ", <!-- Mind the whitespace, won't be necessary in the future -->
}[key] }}{% endmacro %}

{% macro t(key) %}{{
  override(key) or language.t(key)
}}{% endmacro %}

```

The result should then look like:

![screenshot-localhost-8000-1682150739097](https://user-images.githubusercontent.com/932156/233772031-3fafa2df-a569-4b51-becf-4dc555280c82.png)


I know this is not ideal, but please consider it a bandaid until the new search is here ☺️ Turns out Lunr.js (or as a bigger picture, pure tf/idf-based search engines) are not ideal for live documentation search, which is the whole motivation to rewrite that thing from scratch with everything we learned in the past. It will be worth the wait!

**Comment by squidfunk** [comment]
I've marked this as a resolved, since it's not really a bug report or change request, but pathological behavior that originates from the current implementation which can be fixed with customization.

**Comment by StarfallProjects** [comment]
Thanks for this! 🙏
