### ISSUE TITLE
index.ts:96 Uncaught TypeError: o.map is not a function

### ISSUE THREAD

**Issue by prabhatsharma** [squidfunk/mkdocs-material#5369]
### Context

Getting the below error

I have tried removing extra_css and it does not sem to resolve the issue.

### Bug description

```shell
index.ts:96 Uncaught TypeError: o.map is not a function
    at index.ts:96:40
    at map.ts:58:33
    at c._next (OperatorSubscriber.ts:70:13)
    at t.next (Subscriber.ts:75:12)
    at t._next (Subscriber.ts:119:22)
    at t.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at ct (errorContext.ts:29:5)
    at t.next (Subject.ts:61:5)
    at t.next (ReplaySubject.ts:65:15)
```

Also getting:

```shell
index.ts:87 Uncaught TypeError: o.find is not a function
    at index.ts:87:25
    at map.ts:58:33
    at c._next (OperatorSubscriber.ts:70:13)
    at t.next (Subscriber.ts:75:12)
    at t._next (Subscriber.ts:119:22)
    at t.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at ct (errorContext.ts:29:5)
    at t.next (Subject.ts:61:5)
    at t.next (ReplaySubject.ts:65:15)
```
### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

You can find the offending code at : https://github.com/zinclabs/zincobserve-docs
``

### Steps to reproduce

1. git clone https://github.com/zinclabs/zincobserve-docs
2. cd zincobserve-docs
3. mkdocs serve
4. Open documentation in chrome
5. Check dev console

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by prabhatsharma** [comment]
It was resulting from openapi plugin

**Comment by katharinalisalin** [comment]
Thanks for reporting. 
Glad to hear that you figured out the issue yourself. To ensure that we can address future issues efficiently, please follow our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/) and create a minimal reproduction .zip with the assistance of our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) the next time you open an issue. Using the [info plugin](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) described in the reproduction guide will help you rule out that your issue is caused by customizations or other plugins when creating the reproduction, and it helps us look into your issue faster.
Thank you.
