### ISSUE TITLE
Print last modified environment variable to every markdown

### ISSUE THREAD

**Issue by maestrofx** [squidfunk/mkdocs-material#537]
Hi there,

Quick question, is there any way we can print `last modified` variable for every `.md`'s file?
Goal I want to achieve, I can see the timeboard of every file: first_created, last_modified, etc.

Thank you.

**Comment by squidfunk** [comment]
Well, I thought about this too, some time ago, but the only value available to the template is `(build_date_utc)[http://www.mkdocs.org/user-guide/custom-themes/#build_date_utc]`, which is the build time of the whole documentation. Didn't find if very useful, so it's not printed anywhere, but you could include it by extending the theme (see the docs on customization). Printing the build time of every file is not practical, because - what time? The inode time? That doesn't make any sense, as it's heavily OS dependent. What if some else checks out your docs? Then all files are created at checkout time and the times won't match with those on your machine.

**Comment by maestrofx** [comment]
Hi @squidfunk , thanks for replying ASAP.

I've added functionality of `build_date_utc`, but it's precisely not practical. Why? As you mention before, that's the build time of the whole documentation itself which is useless for the large documentation. I mean, the mkdocs as a template for the contents (docs/) are loosely coupling each other.

Imagine, all the docs are frequently commited with the whole engineering team (say 50+ commits per day), what they want to know is when the last time a spesific .md modified, by whom this document signed off.

As a reference, you can check this https://cloud.google.com/docs/compare/aws/.

For my case, I add HTML script for every *.md file `Last Modified on <script type="text/javascript"> document.write(document.lastModified)`. This script will be parsed to static context as `build_time` to each documentation file.

**Comment by squidfunk** [comment]
Okay, it's fine that you found a fix. However, I think that this is not a use case that is used very wide and it boils down to MkDocs supporting this feature, not Material, as Material is only a theme. For this reason I'm closing this issue.
