### ISSUE TITLE
<span> element in toc taking up the whole vertical space

### ISSUE THREAD

**Issue by x4Cx58x54** [squidfunk/mkdocs-material#5416]
### Context

The Mathjax elements are not rendered in TOC, and the same goes for all non-plain text in headers, which is a upstream issue from Python Markdown, as in [#849](https://github.com/squidfunk/mkdocs-material/issues/849). An alternative for Mathjax is KaTeX, and it works very well until I found recently that the KaTeX elements are taking up the whole vertical space in the TOC item, as reproduced in the MWE below. Further investigations saw that force adding non-plain text in an TOC item by devtool results similarly.

### Bug description

A `<span>` element in a TOC item results in 
![image](https://user-images.githubusercontent.com/41692486/233929748-b07c4a61-a11c-466a-b5a2-e30e6baf133f.png)

html for this item (force edited in devtool in chrome) is

```html
<li class="md-nav__item">
  <a href="#some_link" class="md-nav__link">
    I am normal text in this item <span>I am text in a span element</span> I am text after the span
  </a>
</li>
```

The same goes for `<b>`, `<i>` elements.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[mkdocs-material-minumum.zip](https://github.com/squidfunk/mkdocs-material/files/11308131/mkdocs-material-minumum.zip)

### Steps to reproduce

The steps to reproduce is in two parts:
* mkdocs serve the codes in the zip file
    * one can immediately see that there is a problem in the TOC
* force edit an item in TOC using devtool, as described in "Bug description" section
    * one can see that non-plain text is making trouble

### Package versions

* python, version 3.9.12
* mkdocs, version 1.4.2
* mkdocs-material 9.1.4

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. As a temporary measure (that might impact other features), you can add the following CSS:

``` css
.md-nav__link {
  display: block;
}
.md-nav__link > * {
  display: initial;
}
```

**Comment by squidfunk** [comment]
Okay, I've investigated, and this issue definitely only happens in the community edition. [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) doesn't have this problem, and it only happens when you use something like MathJax or KaTex that also applies to the sidebar. Unfortunately, it's not economical to fix this in the community edition, since the sources have diverged quite a lot, but [once the next funding goal is hit](https://squidfunk.github.io/mkdocs-material/insiders/#funding) (we're not that far away from it), the community edition will get all updates from Insiders, which resolve the issue.

For the time being, please apply the following [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) to resolve the issue:

``` css
.md-nav--secondary .md-nav__link {
  display: block;
}
.md-nav--secondary .md-nav__link > * {
  display: initial;
}
```
