### ISSUE TITLE
Social preview for mkdocs-material showing dimensions?

### ISSUE THREAD

**Issue by perpil** [squidfunk/mkdocs-material#5520]
### Context

I just linked to mkdocs material on twitter and the preview showed dimensions around some of the elements.  Is this intentional?

https://twitter.com/rooToTheZ/status/1658166829301530624

<img width="601" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/97474956/e541d692-6205-4e55-ae94-acde0434a089">

### Bug description

Unclear whether you are intentionally making social previews to look like a blueprint for the main docs site.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://twitter.com/rooToTheZ/status/1658166829301530624

### Reproduction

I'm lying about attaching a repro to appease the checks, just follow the steps to reproduce or look at the screenshot in the context.

### Steps to reproduce

1. https://twitter.com/rooToTheZ/status/1658166829301530624

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Many thanks for reporting! This was actually a deployment error and is now a caching issue that should be gone in the coming days. The problem is that I accidentally kept [`debug` mode](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#+social.debug) enabled when committing the latest changes, which led to the social cards being built with the debug grid enabled. This is also the reason why [`7630fd0`](https://github.com/squidfunk/mkdocs-material-insiders/commit/7630fd0357d3aca419055c0c12472f1964bd1045) will now automatically disable `debug` mode on `mkdocs build`, except for when `debug_on_build` is explicitly enabled.

For reference, check the current version of the social card image – it doesn't include the debug grid:
https://github.com/squidfunk/mkdocs-material-insiders/commit/7630fd0357d3aca419055c0c12472f1964bd1045

Since we can't do anything about caching on Twitter's side, we can only mark this as resolved and have to wait.
