### ISSUE TITLE
Nav title extracted from markdown with Section index pages

### ISSUE THREAD

**Issue by tiangolo** [squidfunk/mkdocs-material#5637]
### Context

For FastAPI, I have many MkDocs directories for each language.

I have to keep several `mkdocs.yml` files with almost the same content for each language, in particular, the `nav`, because the section titles are stored on the config file.

Currently, I have some files for English with:

```yaml
- Tutorial - User Guide:
  - tutorial/index.md
  - tutorial/first-steps.md
```

And then for Japanese:

```yaml
- チュートリアル - ユーザーガイド:
  - tutorial/index.md
  - tutorial/first-steps.md
```

I have to keep multiple `mkdocs.yml` files just to be able to store the text "`チュートリアル - ユーザーガイド`", I would like to store that text in the Japanese file for `tutorial/index.md`.

### Description

This is the file I have, and that I would like to have:

```yaml
site_name: Demo
theme:
  name: material
  features:
  - navigation.indexes
nav:
- index.md
- This text is ignored:
  - tutorial/index.md
  - tutorial/first-steps.md
```

**Note**: notice the section title **`This text is ignored`**.

And a file at `docs/tutorial/index.md` with the content:

```Markdown
# Awesome Tutorial

Blah, blah
```

---

This is how it currently renders:

<img width="620" alt="Screenshot 2023-06-23 at 17 23 29" src="https://github.com/squidfunk/mkdocs-material/assets/1326112/3956c3f8-1a22-4ad5-8b7f-73ac3d21f448">

**Note**: notice how the section title has the title from the config in the `mkdocs.yml`: **`This text is ignored`**.

And this is how I would like it to render:

<img width="620" alt="Screenshot 2023-06-23 at 17 24 21" src="https://github.com/squidfunk/mkdocs-material/assets/1326112/0ad5b04a-981f-44b9-baf2-7df79a809862">

**Note**: notice how the section title has the same title as the `index.md`: **`Awesome Tutorial`**.

---

I also tried researching existing plugins and alternatives to achieve this but didn't find one that does it. And as Material for MkDocs already implements **Section index pages**, which I think is probably the most complex part, I thought there could be a way to support this too.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages

### Use Cases

Currently, I have a ton of fragile and very error-prone scripts to try and sync all the translation files and configs.

When someone adds a translation, they have to make sure they add it to the `mkdocs.yml` for that language, which means that for active languages, as each translation modifies that file, there are always conflicts in each of those translation PRs after every merge.

It also means that translators have to fiddle with and understand the config, translate text in YAML instead of staying in Markdown.

It also means that because I have to have a separate `nav` for each language, just for those section titles, I cannot use a main/central `mkdocs.yml` config with the nav that every language can inherit from, because each language would define the titles of the sections in the corresponding Markdown files.

### Visuals

I added them on top in line with the description.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for the excellent change request. I hope I understood it correctly. So yes, my first thought is also that section index pages should actually be the way to solve this issue, but as I understand, the behavior is currently not what you'd need. Currently, the title of the section index page is sourced from `mkdocs.yml`, and for your matters, it would be ideal to source from the first headline or front matter of the corresponding section `index.md`. Correct?

If this is what you need, I'm not sure we can achieve this without adding some custom logic as part of a plugin or hook, because section index pages are something that happens when rendering a specific page (inside [`nav-item.html`](https://github.com/squidfunk/mkdocs-material/blob/d8a0e36ce38ecf74051f2ea2c3e8bcab9b429c16/src/partials/nav-item.html#L61-L97) actually), not when assembling the navigation for all pages. For reference, [see here how MkDocs determines the title of a page](https://github.com/mkdocs/mkdocs/blob/7b1bc92926029058c09ac86649fb51dd7758353b/mkdocs/structure/pages.py#L225-L257).

Since the section title should be replaced with the title of the first `index.md`, this must be done in Python code, probably in the `on_env` event as part of a plugin or hook, which is the last event/hook that happens before starting to assemble entire pages with the rendered Markdown. The plugin could recursively iterate the navigation tree and hoist the title of an `index.md` page into the section. This will then be picked up by Material for MkDocs as if you've defined the title for the section in `mkdocs.yml`, rendering stuff as a section index page. You could then refrain from defining the `nav` at all, since the sections would first be set to the names of the folder the files reside in, but then be overwritten by the headline or front matter title set in `index.md`.

Does that help you? I think this could be pulled off with a hook and probably 20 lines of code. Let me know if you need help.

**Comment by tiangolo** [comment]
Thanks for the pointers! Got it working now. I'm gonna use a custom hook for now.

I have a file `hooks.py` with:

```Python
from typing import List, Union

from mkdocs.config.defaults import MkDocsConfig
from mkdocs.structure.files import Files
from mkdocs.structure.nav import Link, Navigation, Page, Section


def generate_renamed_section_items(
    items: List[Union[Page, Section, Link]], *, config: MkDocsConfig
) -> List[Union[Page, Section, Link]]:
    new_items: List[Union[Page, Section, Link]] = []
    for item in items:
        if isinstance(item, Section):
            new_title = item.title
            new_children = generate_renamed_section_items(item.children, config=config)
            first_child = new_children[0]
            if isinstance(first_child, Page):
                if first_child.file.src_path.endswith("index.md"):
                    # Read the source so that the title is parsed and available
                    first_child.read_source(config=config)
                    new_title = first_child.title or new_title
            # Creating a new section makes it render it collapsed by default
            # no idea why, so, let's just modify the existing one
            # new_section = Section(title=new_title, children=new_children)
            item.title = new_title
            item.children = new_children
            new_items.append(item)
        else:
            new_items.append(item)
    return new_items


def on_nav(nav: Navigation, *, config: MkDocsConfig, files: Files, **kwargs):
    new_items = generate_renamed_section_items(nav.items, config=config)
    return Navigation(items=new_items, pages=nav.pages)
```

and my `mkdocs.yml` now has a section at the end with:

```yaml
hooks:
  - hooks.py
```

I'm not gonna build a plugin with this yet, as I'm not sure it's that useful to others apart from me and my projects. But for now, this will work.

I'll now close the issue. Thanks! ☕

**Comment by squidfunk** [comment]
Perfect, thanks for sharing! ❤️

**Comment by squidfunk** [comment]
One opportunity for improvement: if you execute your logic in `on_env` (which also receives `nav`) and not `on_nav`, there's no necessity to read the source of the Markdown files twice – you can access the `page.title` right away.

**Comment by tiangolo** [comment]
That sounds great!

Although from what I see in the docs here: https://www.mkdocs.org/dev-guide/plugins/#on_env it seems  on_env receives the Jinja2 env and not the nav 🤔 

Is the nav elsewhere?

**Comment by squidfunk** [comment]
Meh, you're right. I didn't memorize it correctly. Adding `nav` to `on_env` would really help in some cases – you have an ideal case on your hands. Maybe we can discuss this over at MkDocs? If you're interested, you can upstream this and tag me. As a plugin developer, I'll be happy to share my viewpoint on this!
