### ISSUE TITLE
Mermaid colors overridden by theme stylesheet

### ISSUE THREAD

**Issue by analog-cbarber** [squidfunk/mkdocs-material#5681]
### Context

I was trying to use colored rect in a mermaid sequence diagram, like this:

```mermaid
sequenceDiagram
    participant A
    participant B
    activate A
    A ->> B: hello
    rect yellow
    activate B
    B -->> A: this should be yellow
    deactivate B
    end
    activate A
```

### Bug description

Instead of getting the specified color when rendered in mkdocs site built using mkdocs-material, all the
rectangles ended up using the theme based colors:

<img width="456" alt="Screenshot 2023-07-05 at 2 28 35 PM" src="https://github.com/squidfunk/mkdocs-material/assets/7408243/95b99ae0-f11d-4695-b3e4-1126fbc3c10f">

When I inspect the rectangle in chrome, I see

<img width="596" alt="Screenshot 2023-07-05 at 2 32 37 PM" src="https://github.com/squidfunk/mkdocs-material/assets/7408243/c8a5eee2-f236-4dd6-8517-486f0e6a1579">

Turning off the `__mermaid_0 rect.rect` style makes it behave as expected.

I am not a CSS expert, so I do not know whether there is an easy workaround for this.

Also not sure if this is a general problem or is specific to rect.

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/diagrams/

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/11961053/example.zip)

### Steps to reproduce

Create a mkdocs page containing a mermaid sequence diagram containing
one or more rect statements with an explicit color, as shown above.

The displayed color should be the one specified in the diagram, not the theme color.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. That is expected behavior, as Material for MkDocs adds custom styles to Mermaid.js diagrams, so they match the color palette you choose in `mkdocs.yml`. The markup that Mermaid.js generates does not allow us to discern when a fill color was explicitly set or not. However, if you wish to keep Mermaid's own color system, you can use a custom integration. You need to change the class name to another name than `mermaid`, e.g.:

``` yaml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-custom
          format: !!python/name:pymdownx.superfences.fence_code_format
```

Then, you can integrate Mermaid.js via additional JavaScript by targetting the `.mermaid-custom` class. Another option might be the [`mkdocs-mermaid2-plugin`](https://github.com/fralau/mkdocs-mermaid2-plugin).

**Comment by analog-cbarber** [comment]
Thanks for answering, but this is obviously not ideal. The element in the DOM has the correct color but it is being overridden by the style sheet. I actually like using the material theme color as the default rectangle color, but only as a default.

Is there really no way to write the style rule so that it is a default rather than an override? (I might have to go back and brush up on my CSS...)

**Comment by squidfunk** [comment]
I understand completely. Unfortunately, Mermaid.js integration is exceptionally tricky, and its the only way to theme it according to the colors defined by the author.

> Is there really no way to write the style rule so that it is a default rather than an override? (I might have to go back and brush up on my CSS...)

Not really at the moment. The problem is that Mermaid.js parses the CSS stylesheet and inlines it into the SVG, prefixing every selector with the ID of the diagram. IMHO, styling Mermaid.js is really an unsolved problem. However, if you would like to dive into this topic, I'd be happy to support a PR that retains the current functionality, while allowing for overriding colors.

**Comment by analog-cbarber** [comment]
So if we had a `mermaid-native` class that would keep the mermaid color scheme, could we then
just assign it to a different name in the config:

```yaml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid-native
          class: mermaid-native
          format: !!python/name:pymdownx.superfences.fence_code_format
```

and then use that in your documents if you wanted a particular diagram to use the mermaid colors:

~~~markdown

```mermaid-native
sequenceDiagram
   ...
```
~~~

Would that be feasible?

**Comment by PlasmaHH** [comment]
> Thanks for reporting. That is expected behavior, as Material for MkDocs adds custom styles to Mermaid.js diagrams, so they match the color palette you choose in `mkdocs.yml`. The markup that Mermaid.js generates does not allow us to discern when a fill color was explicitly set or not. However, if you wish to keep Mermaid's own color system, you can use a custom integration. You need to change the class name to another name than `mermaid`, e.g.:
> 
> markdown_extensions:
>   - pymdownx.superfences:
>       custom_fences:
>         - name: mermaid
>           class: mermaid-custom
>           format: !!python/name:pymdownx.superfences.fence_code_format
> Then, you can integrate Mermaid.js via additional JavaScript by targetting the `.mermaid-custom` class. Another option might be the [`mkdocs-mermaid2-plugin`](https://github.com/fralau/mkdocs-mermaid2-plugin).

Can you elaborate on how to do that with an additional javascript without re-doing everyhting material does for it? Would it maybe be a good idea to integrate that mermaid-native or whatever you want to call it into material, my guess would be that its just a few additions in the mountMermaid path?

**Comment by smalldust** [comment]
I think the issue is not necessarily that Mermaid's generated markup lacks the information, but rather that Material's current integration strategy discards it.

For example, Mermaid clearly distinguishes between:

```mermaid id="fdwvsr"
rect rgb(130, 250, 250)
```

and a rect without an explicit fill color, otherwise Mermaid itself could not render them differently in environments without Material's overrides.

What seems to happen here is that Material applies a blanket rule like:

```css id="ql1luh"
#__mermaid_0 rect.rect {
  fill: var(--md-mermaid-sequence-box-bg-color);
}
```

which overrides all `rect.rect` elements regardless of whether the user explicitly specified a color.

So this appears to be more a limitation of the current CSS-based theming approach than a limitation of Mermaid's markup itself.
