### ISSUE TITLE
Social plugin: Clarify why `site_url` is needed

### ISSUE THREAD

**Issue by jartins** [squidfunk/mkdocs-material#5850]
### Description

The "social" plugin needs the "site_url" configuration option to be defined. It will likely not work correctly.

<img width="953" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/38277424/24a565f8-5964-474e-8343-726d71273de5">

**Comment by squidfunk** [comment]
Yes. This is a warning issued by the social plugin and it was mentioned in our documentation why this is the case, but somehow got lost. The reason is that URLs must be absolute for Twitter and other services to pick them up, and we can only generate absolute URLs when `site_url` is set. We'll update the documentation.

**Comment by squidfunk** [comment]
Updated the documentation in 0a7e9d21b and improved the warning reported by the plugin in 914df5fe7.
