### ISSUE TITLE
Mobile nav drawer shows table of contents on page with `hide: [toc]` front matter

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5948]
### Bug description

When configuring the table of contents to be hidden on a page

```md
---
hide:
  - toc
---

# Heading

## Sub-heading
```

it's hidden in the content area but not in the mobile nav drawer for screens smaller than 960px. I think this is a bug because it's inconsistent to hide it on large screens but not on small ones.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Hide table of contents](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hide-table-of-contents)

### Reproduction

[9.2.7-hide-toc-mobile-nav.zip](https://github.com/squidfunk/mkdocs-material/files/12504528/9.2.7-hide-toc-mobile-nav.zip)

### Steps to reproduce

1. Open the minimal reproduction site.
2. Reduce the window width below 960px, then open the drawer.
3. Notice the table of contents icon, also notice that it can be clicked and the table of contents appears in the drawer.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. You're talking about the [hiding the sidebars](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars) feature – it's working as intended, as both flags will hide the __sidebars__ on tablet/desktop, but will not influence the navigation drawer in any way. In fact, if they would, hiding the navigation sidebar would need to remove the drawer altogether, because the drawer hosts the navigation and the current page in the drawer hosts the table of contents. This makes no sense, because then your users will be unable to navigate.

Note that hiding the navigation sidebar only makes sense if you use a [navigation tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs). Hiding the table of contents is a little less involved, but for consistency, it is also scoped to just hide the sidebar, not the table of contents in the drawer.

I agree that this might be a little confusing at first, but it makes total sense, because it is essentially not about taking information away from the user, but for getting more screen estate. On mobile, all navigation is collapsed, so it doesn't impact the available screen estate, and the full screen is used anyway.

**Comment by sisp** [comment]
Thanks for your detailed and prompt reply, @squidfunk! :bow: Your comparison with the navigation makes sense and the behavior is consistent and logical when interpreting those two hide identifiers in the context of sidebars &ndash; as the documentation indeed does. I still think there are cases in which you'd want to hide the table of contents _also in the mobile nav drawer_, e.g. on a custom home page that uses Markdown headings and highly customized styling, so that those headings shouldn't necessarily be interpreted as sections to jump to. I think [your suggested workaround](https://github.com/squidfunk/mkdocs-material/issues/2162#issuecomment-752917362) is good enough for me, [I only added a minor fix to also hide the icon](https://github.com/squidfunk/mkdocs-material/issues/2162#issuecomment-1704107905).

**Comment by squidfunk** [comment]
@sisp I can't find an email address of yours and you're the only one subscribed to this issue.

We recently got sponsored by SIEMENS, and since you're pretty active here lately and publicly disclose that you work for SIEMENS, I suspect that you have something to do with it. If you can spare 30m, it'll be amazing to talk to you to get some feedback on how Material for MkDocs is used in your organization. You can book a slot in my [calendly](https://calendly.com/squidfunk/enterprise), if you're interested, or reach out via martin.donath@squidfunk.com. I speak English and German. If not, no problem! Just ignore this message then.

This message will be deleted 10s after posting.
