### ISSUE TITLE
New darker slate theme feels like it lacks contrast/readability

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#6061]
### Context

> Disclaimer: I realize this issue is _highly_ subjective, but I do hope it provides meaningful feedback. ❤️ 

### Description

[9.4.0](https://github.com/squidfunk/mkdocs-material/releases/tag/9.4.0) changed:

> Improved slate color scheme (dark mode) - now even darker

I realize this is subjective, but I feel the changes make it harder to read because normal text is so faint and grey now. Also **bolded** text is _much_ brighter relatively, which makes it pop out almost too much.

I'm all for darker themes in general, but I would prefer keeping the contrast/brightness high for normal text and text to be closer to white so that it is readable easily, even for people with poorer eyesight.

Perhaps it would be useful to have a "muted-slate" or "vivid-slate" option that is closer to the previous?

### Related links

- 970670bb4adac974edaa590d31c3ab79f42bce75
- 859b8bcaee31e4a7d854eb77d741c8fba762465c

### Use Cases

Anyone using `slate` theme (which, normally I thought was a great, simple default dark theme).

I first noticed this issue when we updated to 9.4.0 on a work project, but then went to one of my open source projects to show as an example

- https://github.com/johnthagen/python-blueprint

### Visuals

Personally, I find the faded text color doesn't pop and read as well. Also note how much _brighter_ **bold text** is, which I felt like is now more of a "highlight" than a "bold" in standard Markdown terms.

<img width="2556" alt="Screenshot 2023-09-21 at 2 03 42 PM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/e7ee5fb7-abb9-4713-8fbe-464201895e32">

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting. In fact, I find it harder on the eyes when contrast is too bright. We can increase the contrast slightly, but we're not going to increase it to the value we had before. As the background is darker now, it is also okay to make the text a little fainter. Bold text is brighter so it has the same contrast when viewing in light mode. Otherwise, bold text is lost. That being said, we'll increase the value slightly, but you can also add a single line to revert back to the old style.

``` css
[data-md-color-scheme=slate] {
  --md-default-fg-color: hsla(var(--md-hue), 15%, 90%, 1);
}
```

Themes are _always_ subjective 😉

**Comment by squidfunk** [comment]
As an addendum: text in GitHub's dark theme is also not white. White text on dark background is too hard too read.

**Comment by saltydk** [comment]
I agree with OP that this makes things harder to read at first glance, the change was fairly jarring. Not possible to just implement more themes instead of making such large changes?

**Comment by squidfunk** [comment]
We could've implemented a new color scheme, but this would increase the size of the payload at no upside, since we only changed some tints. Personally, I was sick of the old color theme, which is why I adapted it to something I believe is much better than what we had before. Yes, it is subjective after all.

Please know that when you maintain a project of this size _any change you make is unpopular_, but we have big plans and need to move this project forward to keep it sharp, so we have to change things. The previous dark scheme did not go well with certain color combinations, e.g. black, so we adapted it, and to have actually more overall contrast (link colors, tabs, etc.). We'll slightly increase the contrast of the text and will have a better situation as before.

That being said, we put great emphasize on [customization](https://squidfunk.github.io/mkdocs-material/customization/), and it's actually so easy to adjust with a few lines of CSS (as noted in [my last comment](https://github.com/squidfunk/mkdocs-material/issues/6061#issuecomment-1730194281)), that you can revert back to the old colors, or even better: build your own custom color theme!

**Comment by squidfunk** [comment]
For comparison, here's the text color that GitHub uses (top) vs. the one that we currently use:

<img width="640" alt="Bildschirm­foto 2023-09-22 um 12 28 53" src="https://github.com/squidfunk/mkdocs-material/assets/932156/466aed7c-5377-4656-85e1-5113915b289f">

Nonetheless, I'll slightly tweak the colors again, so they fit together a little better ☺️

**Comment by squidfunk** [comment]
I've adjusted the colors in c9e4a5e26513d34a5438d6c0268a6344814bd48f.

- Slightly lightened body copy
- Removed extra styling for bold text (that was an experiment)
- Adjusted color of text in code blocks as suggested in #6062, but slightly differently
- Made content tabs to match color of body copy for less noise
- Moved to a slightly more neutral tint

This issue is now considered resolved. If you wish to tweak the colors – go ahead, it is super simple! This is our new dark mode that we regard superior to the prior one, which was too light and had problems with contrast.

__Before__

![screenshot-squidfunk-github-io-mkdocs-material-getting-started-1695384114879](https://github.com/squidfunk/mkdocs-material/assets/932156/67d0f71b-26fd-42ff-af01-1c74cce167c5)

__After__

![screenshot-localhost-8000-mkdocs-material-getting-started-1695384121468](https://github.com/squidfunk/mkdocs-material/assets/932156/4fe2796b-5cc0-4010-8a8e-3419941a7a39)

**Comment by johnthagen** [comment]
Thanks @squidfunk. I was in the process of posting that your idea to compare to GitHub's dark theme as a reference is a great idea!

Here was a comparison side by side between the 9.4.0 dark theme and GitHub's dark theme, showing the difference is background and foreground color & contrast.

<img width="978" alt="Screenshot 2023-09-22 at 8 07 09 AM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/643757cb-c69d-4898-808e-ea3c1b69fe91">

As always thanks for the awesome tool you've created and for your feedback and work. ❤️

**Comment by squidfunk** [comment]
I'm using dark dimmed which is closer to what the slate theme is now 😉

**Comment by squidfunk** [comment]
Released as pat of [9.4.1](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.1).

**Comment by vedranmiletic** [comment]
@squidfunk good work, I particularly like

> Removed extra styling for bold text (that was an experiment)

**Comment by johnthagen** [comment]
@squidfunk Just wanted to follow up that we upgraded to 9.4.1 and want to report that the new tweaked `slate` theme feels a lot better at first glance than 9.4.0 -- thank you for your thoughtful consideration and quick updates. ❤️
