### ISSUE TITLE
Override clipboard text for code blocks

### ISSUE THREAD

**Issue by ti-mo** [squidfunk/mkdocs-material#6086]
### Description

Our documentation contains shell snippets including a command's expected output, like:

![image](https://github.com/squidfunk/mkdocs-material/assets/3214460/87edd8fe-260a-45b0-b11e-383cccb37af5)

One of our users complained about the clipboard button grabbing everything in the block, which is indeed rather annoying for something like `shell-session`. Even though the code highlighter correctly recognizes the prompt and the output, that doesn't translate to the behaviour of the clipboard button.

### Related links

I ended up here (https://github.com/facelessuser/pymdown-extensions/issues/1802) in my search, but that only really affects text selection. It's still a nice UX improvement, though, and I'll follow the advice given there as well.

### Use Cases

I started out trying to influence clipboard.js' behaviour by setting `{ .shell-session data-clipboard-target="foo !important" data-clipboard-text="go mod init ebpf-test && go mod tidy" }` on the block (ending up on the div), but this only works when I remove the `data-clipboard-target` property from the button using my browser's devtools. 

Since it can't easily be determined what the correct behaviour is in `shell-session` blocks containing multiple lines with commands, I figured it would be nice to be able to manually specify the snippet used by the clipboard button. XYProblem, but it looks like a relatively straightforward change from a distance.

It looks like `setupClipboardJS()` already takes `data-clipboard-text` into account, but `data-clipboard-target` seems to take precedence if both are specified on an element. Not sure why that's the case.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Could you please provide a self-contained minimal reproduction that allows us to run what you describe? We would like to understand if we can move properties around to allow for this use case, but for this, we need something we can run and experiment with.

**Comment by ti-mo** [comment]
@squidfunk Please reopen, didn't have more time to dedicated to this last week. Here's a repro: [9.4.3-clipboard-text-override.zip](https://github.com/squidfunk/mkdocs-material/files/12785673/9.4.3-clipboard-text-override.zip)


Observation: **without** superfences, the hierarchy is as follows:
```html
<pre>
  <button></button>
  <code data-clipboard-text="go mod init ebpf-test && go mod tidy"></code>
</pre>
```

This won't allow the user to override the property on the button, since the `<code>` is a sibling.

With superfences enabled, the attribute is defined on the surrounding `<div>` instead:

```html
<div class="highlight" data-clipboard-text="go mod init ebpf-test && go mod tidy">
  <pre>
    <button></button>
    <code></code>
  </pre>
</div>
```

Note that the `data-clipboard-text` attr is ignored in both scenarios. Maybe this is something that can be addressed. It depends on a particular configuration, though, making this a little fragile.

Would it be an option to add an extra argument to the block header (fence?) instead? Something like:

```
    ```shell-session clipboard-text="foo"
    this should copy 'foo'
    ```
```

Thank you.

**Comment by squidfunk** [comment]
Thanks for providing the reproduction. We'll look into it.

**Comment by squidfunk** [comment]
However, note that it will be very cumbersome to provide clipboard text via attributes, because everything must fit into a single line without line breaks. I'm not sure this is viable or comfortable to use, so my current guess is: not feasible.

**Comment by ti-mo** [comment]
Our use case would be providing shorthands/one-liners for longer code blocks, so not being able to use line breaks is fine.

**Comment by squidfunk** [comment]
The thing is, I'm not sure it's a good user experience. The user clicks on the copy-to-clipboard icon and whats copied is not what's listed. It's counter-intuitive. I understand that there's need for not copying specific lines, but that's actually what [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) are for. You can annotate each line with additional content without influencing what's copied.

**Comment by ti-mo** [comment]
Agreed on the premise of principle of least surprise, but that's not what our users are telling us.

If we could somehow exclude the `%` and output lines in the snippet in the screenshot, that would be ideal, it would make the output reproduce 1:1 in the user's terminal. (basically, make clipboard.js obey `user-select: none;`) Not sure if that's currently supported by the library, though.

**Comment by squidfunk** [comment]
Added support in a9da0b632. Note that this will probably always only work properly for single line statements, as you cannot supply multi-line clipboard text in the prologue of a Markdown code block. It might be possible to pull something of with custom blocks, or by using literal line feeds, but I'm not sure and it is currently not a priority for us.

Also note that we cannot call the attribute `data-clipboard-text`, because the whole code block will be copied on click, since Clipboard.js considers it to be a target. Thus, we named it `data-copy`. It now works with and without superfences by looking for the closest ancestor defining a `data-copy` attribute and falling back to the inner text.

**Comment by squidfunk** [comment]
Released as part of [9.4.4](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.4).

**Comment by ti-mo** [comment]
@squidfunk Thank you! Works like a charm!

**Comment by squidfunk** [comment]
We've decided to remove this feature from our documentation in ee0a3c6ed. There are severe problems with the implementation in Python Markdown, most prominently that the content needs to be escaped as HTML entities. After thorough discussion in https://github.com/Python-Markdown/markdown/issues/1390, it is not expected that this issue is solved any time soon.

The current implementation is too fragile to advertise as something that we feel comfortable maintaining and providing support for. We will not change the source code for now, meaning it will likely keep working, but we cannot promise anything. The general advise is not to use the `data-copy` attribute, because it might be removed in the future, e.g. when we're working on the copy-to-clipboard functionality again.

This is the very first time we're removing a feature that we tagged as experimental. Thank's for your understanding.

**Comment by squidfunk** [comment]
Addendum: if somebody comes up with another extension that allows to comfortably set `data-copy`, we might consider not removing it and adding it back. The [blocks extension](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/) could be of help here, but I haven't had the time to look into it.

**Comment by ti-mo** [comment]
Hi @squidfunk, what's your current stance on this? I'm still manually checking if this behaviour broke on each dependency bump. Looks like there's been some progress in https://github.com/Python-Markdown/markdown/pull/1414, would that be sufficient to support this long-term?

If not, what could we do on our end to make sure this keeps working? Thanks!

**Comment by squidfunk** [comment]
There are currently no plans of removing it from our code base, but we're still not advertising it. In the end, Markdown support is necessary for this, which is provided by Python Markdown and friends, so we have no control over this. Maybe, in the future, we find some time to create our own Markdown parser? Who knows? 😅

**Comment by jpluscplusm** [comment]
Hi there 👋 - just dropping in with a quick note on how the `data-copy` attribute has been working **really well** for us.

I'm part of [the CUE docs community](https://cuelang.org/docs/), and we’ve recently adopted Material for MkDocs for a new site we're building: https://cue.dev/docs/. Huge thanks to everyone involved for creating such a powerful and well-thought-out tool - we’ve really enjoyed working with it.

We’re building this new site with a strong emphasis on tested documentation. Many of our pages contain shell command snippets interleaved with their expected output, alongside runnable CUE code blocks. We need the code *and* the shell commands to be tested together as part of each complete example - but we only want the copy button to include the actual command the user should run, and not the accompanying output. That’s exactly where `data-copy` comes in.

To make this maintainable, we write the original code and shell commands as source input. A [custom preprocessor](https://github.com/cue-lang/cuelang.org/tree/master/internal/cmd/preprocessor) then tests those examples holistically (validating both the code and the shell commands' output) and emits Markdown suitable for static site generation. That Markdown includes `data-copy` attributes for shell blocks, ensuring users can copy just the command, even when the rendered block includes output lines for context.  Here's [a live example of one of our pages](https://cue.dev/docs/spotting-errors-earlier-github-actions-files/) - notice that while the "TERMINAL" block [halfway down the page](https://cue.dev/docs/spotting-errors-earlier-github-actions-files/#validate-the-workflow-file) includes the command's output, the block's copy button only picks up the command itself.

We’re already using MkDocs and `data-copy` in this new site and, even with HTML entity encoding, it works exactly as we need. Because we're generating the attribute programmatically, encoding isn’t a burden or source of fragility.

We completely understand the concerns about long-term maintainability and upstream parser limitations - and we’re *not* asking for support or guarantees. We just wanted to share a real-world use case where the feature is solving a real problem and working reliably.

> There are currently no plans of removing it from our code base, but we're still not advertising it.

Totally understood - we just hope this example is useful context if the feature’s future is reconsidered. We'd love to see it stay, and if a supported path emerges (e.g. via code blocks, or some other extension) we’d be glad to share usage patterns and to help test it.

Thanks again for your work on Material for MkDocs - it’s been a pleasure to use!

**Comment by squidfunk** [comment]
Awesome, thank you so much for sharing! As part of our foundational work, we're also looking into making annotation with structured data of arbitrary elements easier (like the `data-copy` attribute for the copy to clipboard button). Your feedback is very valuable for us. CC @alexvoss for visibility
