### ISSUE TITLE
Not clear how to disable `navigation.instant` for local pages

### ISSUE THREAD

**Issue by VelocityRa** [squidfunk/mkdocs-material#6105]
### Description

When using `navigation.instant`, the Table of Contents becomes un-scrollable. It only shows the top part, with no scrollbar. The bug is presumably only visible if there are many entries (more than a page view's worth, vertically). It goes away if I remove `navigation.instant` from my config.

I use both `gh-deploy` (for online docs), and ship built html files to my users (for local browsing).

More of a question (or bug report?) but, It's not clear how I would only use instant navigation when deploying to GH pages without hacks, like programmatically appending `- navigation.instant` to my `mkdocs.yml` before the `gh-deploy` on my CI runner.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
- https://www.mkdocs.org/user-guide/deploying-your-docs/#local-files

### Proposed change

One of:
- Fix instant loading on local pages
- Disable instant loading on local pages (loading locally is instant anyway)
- Document a way / workaround for disabling instant loading for `file://` browsing.

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment]
The [building for offline usage page](https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/) says that instant navigation needs to be turned off, amongst other things. You may want to give the [group plugin](https://squidfunk.github.io/mkdocs-material/plugins/group/) a try. 

I realize the information is not conveniently in one place.  Would adding a line or two here have helped? https://squidfunk.github.io/mkdocs-material/creating-your-site/#building-your-site

**Comment by squidfunk** [comment]
Thanks for reporting. Since you're deliberately building for offline usage, the [building for offline usage guide](https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/) is the canonical place for information around that topic. The page lists all features that are not compatible with offline usage, not because Material for MkDocs doesn't support them, but because browsers don't allow for the underlying implementation of those features to work. This is all expained in the [limitations](https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/#limitations) sections of the offline plugin.

> More of a question (or bug report?) but, It's not clear how I would only use instant navigation when deploying to GH pages without hacks, like programmatically appending - navigation.instant to my mkdocs.yml before the gh-deploy on my CI runner.

You can use configuration inheritance. Define your entire online configuration in `mkdocs.yml` and use the `group` plugin as suggested by @alexvoss to toggle the plugin with an environment variable. Then, create a second configuration, e.g. `mkdocs.offline.yml`, and add all `theme.features` flags without `navigation.instant`, something like:

``` yaml
INHERIT: mkdocs.yml
theme:
  features:
    # everything but navigation.instant
```

We'll check if we can make this easier in the future, but for now, this is the recommended way to go. We'll also be adding an example in our documentation that can be downloaded and used as a started in the coming weeks.
