### ISSUE TITLE
We're closing our Gitter channel

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#6120]
__We've decided to close our Gitter channel in favor of GitHub Discussions. Read our blog post to learn why:__
https://squidfunk.github.io/mkdocs-material/blog/2023/10/02/sunsetting-gitter-towards-efficient-community-engagement/

__Timeframe__

- October 2, 2023: We're going to limit conversation to administrators, users can still read past messages, but not post.
- October 13, 2023: We're closing the channel and will not allow new users to join.

**Comment by squidfunk** [comment]
Sorry, I blocked you because you didn't include any reference to your question in your PR and just sent a PR with no further information provided. We talk about this in our block, as you can see from the link in my OP. The reason why I blocked you instantly is that we're having some problems with bot accounts lately that make a mess on our issue tracker and discussion board, posting gibberish.

**Comment by shubhalgupta** [comment]
> Sorry, I blocked you because you didn't include any reference to your question in your PR and just sent a PR with no further information provided. We talk about this in our blog, as you can see from the link in my OP. The reason why I blocked you instantly is that we're having some problems with bot accounts lately that make a mess on our issue tracker and discussion board, posting gibberish.
> 
> Edit: ah, you've added it to the commit message. Sorry again, I unblocked you again. However, we don't need this note in our documentation, as we wrote in our blog about it.

Then where I need to make changes if not in documentation?

**Comment by facelessuser** [comment]
What changes do you feel you need to make?

Gitter is just a chat room where people could ask @squidfunk questions about Material. With the addition of GitHub Discussions, there is no need to maintain such a chat room, so it is being discontinued. The only thing you need to do is ask MkDocs Material related questions on GitHub Discussions instead of using the MkDocs Material chat room. Nothing needs to be done in your projects as they are separate from Mkdocs Material.
