### ISSUE TITLE
Allowing usage of script within admonitions

### ISSUE THREAD

**Issue by EssentialAI** [squidfunk/mkdocs-material#6271]
### Context

Here is how script works to insert an image outside admonition and it works perfectly.

![Screenshot 2023-11-01 at 12 45 41 PM](https://github.com/squidfunk/mkdocs-material/assets/54857609/eda52496-69e9-43e1-98c3-1c9853ff3035)

Code:

`!!! info "Title"
    some text

<div style="text-align: center;">
<div id="imageContainer1"></div>

<script>
    fetch('../assets/text.txt')
        .then(response => response.text())
        .then(url => {
            const imageContainer = document.getElementById('imageContainer1');
            imageContainer.innerHTML = `<img src="${url}" alt="Image">`;
        })
        .catch(error => {
            console.error('Error fetching the URL:', error);
        });
</script>

<div style="margin-top: -15px; text-align: center;">
    <a href="http://neuralnetworksanddeeplearning.com/chap1.html" target="_blank">Source</a>
</div>
</div>`

And here is the output with the same code inside an admonition.

![Screenshot 2023-11-01 at 12 46 21 PM](https://github.com/squidfunk/mkdocs-material/assets/54857609/c90910c3-62f7-4787-ab6b-42f5e4a2b237)

Code:

`!!! info "Title"
    some text

    <div style="text-align: center;">
    <div id="imageContainer1"></div>
    
    <script>
        fetch('../assets/text.txt')
            .then(response => response.text())
            .then(url => {
                const imageContainer = document.getElementById('imageContainer1');
                imageContainer.innerHTML = `<img src="${url}" alt="Image">`;
            })
            .catch(error => {
                console.error('Error fetching the URL:', error);
            });
    </script>
    
    <div style="margin-top: -15px; text-align: center;">
        <a href="http://neuralnetworksanddeeplearning.com/chap1.html" target="_blank">Source</a>
    </div>
    </div>`

Is there a way to make the script work within the admonition tab? Thank you for the amazing project and thanks in advance.

### Description

Ability to use script within admonition

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- 

### Use Cases

Ability to use script within admonition

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
The 'normal' admonitions syntax requires you to indent everything that is to go into the admonition. The code you posted here is incomplete (the script is missing in the 2nd example), so I cannot see if you have done this. 

I use the [alternative block syntax for admonitions](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/), which uses delimiters instead of indentation and works just fine in Material as it produces the same HTML as the traditional syntax. Note that you should disable the usual `admonition` entry in `markdown_extensions` and replace it with `pymdownx.blocks.admonition`.

**Comment by alexvoss** [comment]
Right, I think my first comment is valid but I now realize that this might be to do not with whether the script is inside the HTML produced for the admonition. Rather, you should probably delay its execution until the browser has rendered the DOM. This can be done by putting your code into a callback function:

```
document$.subscribe(function() {
  // your code here
})
```

**Comment by squidfunk** [comment]
Thanks for reporting. As @alexvoss said, you shouldn't put `script` tags in Admonitions. Behavior will be erratic – you should always use `document$.subscribe` to register custom JavaScript logic. That being said, this problem is not exclusive to Material for MkDocs, but to all MkDocs themes. Closing as upstream.
