### ISSUE TITLE
Code copy button without adding new line

### ISSUE THREAD

**Issue by maxsitt** [squidfunk/mkdocs-material#6323]
### Description

Currently, when copying code with the code copy button, a new line is automatically added when pasting the copied code somewhere else. This does not happen if the code is copied manually by selecting everything in the code block. The expected behaviour of copying the code with the code copy button should be to copy only the content in the code block, without adding a new line.

### Related links

- [Code copy button documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button)

### Use Cases

Especially when copying code that should be run in a Terminal/command prompt, the new line that is automatically added when copying the code with the code copy button can lead to problems in some cases, e.g. code is run immediately when pasting. Expected behaviour of the code copy button should be exactly the same as for copying code manually: copy only the content in the code block without adding a new line.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Actually, this sounds more like a potential bug report, but it does not have a reproduction. If so, it iss either related to Python Markdown or to Clipboard.js, since we're only providing the glue between both. We use the HTML that comes out of Python Markdown and add the copy button. Thus, please report this upstream. I recommend to create a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) to understand where the newline is coming from.
