### ISSUE TITLE
Neutral colors for content tabs can sometimes make web pages look unsightly

### ISSUE THREAD

**Issue by RemyYYZ** [squidfunk/mkdocs-material#6362]
### Description

In version 9.4.1, the color of Content tabs has been changed to a neutral color, which makes me feel unsightly (Especially when combined with the colorful admonitions).

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://squidfunk.github.io/mkdocs-material/reference/content-tabs/

### Use Cases

Can you please change it to custom Content tabs color? Like this
In mkdocs.yml
```
- pymdownx.tabbed:
      alternate_style: true
      color: xxxx
```

This allows for more freedom in web color combinations.

### Before submitting

- [x] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
As pretty much every aspect of styling, this is easily solved by customization. For example, I like a border around the tabbed content because otherwise I may not see where it ends. 

```css
.md-typeset .tabbed-set {
  border: 1px dotted lightgray;
}
```

Similarly, you should be able to assign a different color to the elements you want so change. Just put it into the [extra.css](https://squidfunk.github.io/mkdocs-material/customization/?h=extra+css#additional-css). Your browser's web developer tools should help you find the necessary classes to apply the styling to. AFAIK, Chrome, Firefox and Safari all support right-clicking on an element and choosing `Inspect` to take you to the Inspector tab directly.

**Comment by squidfunk** [comment]
@alexvoss is right. [Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) is the way to go – it's actually 1 line of CSS (if you don't count the selector and the closing brace), so trivial to achieve:

``` css
.js .md-typeset .tabbed-labels:before {
  background-color: deeppink;
}
```
