### ISSUE TITLE
Get projects plugin to pick up new projects

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#6399]
### Context

When working with the projects plugin, a newly created project is not getting picked up. While it is relatively easy to trigger a re-build by touching the main `mkdocs.yml`, it would be nice if new projects were picked up automatically.

It is debatable whether this constitutes a bug or a change request. I went with the latter since this should not be blocker for anyone.

### Description

I am proposing to add something to the configuration of the file system watcher that would identify a new subdirectory in  the `projects_dir`. Looking at the documentation of the watchdog library used, it seems this should be possible.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://python-watchdog.readthedocs.io/en/stable/api.html#watchdog.events.FileSystemEventHandler.on_created
- https://github.com/squidfunk/mkdocs-material-insiders/blob/199b01479f8770cee3a3b3456edf0103c68bd468/src/plugins/projects/plugin.py#L336

### Use Cases

This applies for any use of the projects plugin. It may be more important to some uses than others, since in some there will be plenty new subprojects being created all the time, while other users may have a limited and static set of subprojects.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! I must say, I just love your usability suggestions – this one is definitely a must have.

**Comment by squidfunk** [comment]
Fixed in [`f1cb613`](https://github.com/squidfunk/mkdocs-material-insiders/commit/f1cb6134213ccb947fb55c055961f8ad3f654b58). 🫠 I've invested the last 4 days to refactor the projects plugin and pave the way for more complex interactions and modes between projects. Although I'm already happy with the result, there's still a lot of room for improvement, but I'll fix this on the way. The most important problem here was to improve the user experience.

Additionally, projects are now automatically resolved and built in topological order, which means that nested index pages are also possible now. I've developed a scalable approach that is based on tainting projects for rebuilding. Currently, a file change taints a project, and schedules it for rebuild in the next iteration, however tainting can also be done programatically.

What was _particularly_ tricky was not only to pick up new projects, but to add them to the watched files, so that you can start editing right away. Bonus points for the "Rückrichtung": same is true for removing projects, so if you delete a project, it'll be automatically unwatched.

**Comment by squidfunk** [comment]
Released as part of [9.5.2+insiders-4.47.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.47.1).

**Comment by alexvoss** [comment]
You are on fire, dude! Thanks for doing this.
