### ISSUE TITLE
Undocumented issue if Grids don't work?

### ISSUE THREAD

**Issue by karl-police** [squidfunk/mkdocs-material#6405]
### Description

I tried testing Grids

![image](https://github.com/squidfunk/mkdocs-material/assets/12023782/c880c30d-f5a9-4142-91f0-4f6fd13266f0)

```
<div class="grid" markdown>
Test
{ .card }

Test2
{ .card }

Test3
{ .card }

>Test4
{ .card }
</div>
```

but they don't work even though I have the required ``markdown_extensions`` from this documentation https://squidfunk.github.io/mkdocs-material/reference/grids/

**Comment by squidfunk** [comment]
Thanks for reporting: First of all, you're using the feature request template for a potential bug report. This does not follow our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Second: are you using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? Card grids are currently resolved to sponsors.

Closing because of wrong template.

**Comment by karl-police** [comment]
> Thanks for reporting: First of all, you're using the feature request template for a potential bug report. This does not follow our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Second: are you using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? Card grids are currently reserved to sponsors.
> 
> Closing because of wrong template.

I don't think so, I am just using md_in_html and copy pasted the stuff from the docs


I am more wondering about this now, that I asked in all 3 repositories

https://github.com/squidfunk/mkdocs-material/discussions/6406
