### ISSUE TITLE
"Stay on page when switching language" does not work after build

### ISSUE THREAD

**Issue by janvanveldhuizen** [squidfunk/mkdocs-material#6515]
### Context

Issue [4835](https://github.com/squidfunk/mkdocs-material/issues/4835) was resolved in a recent version.

### Bug description

Staying on the same page when switching language does work when running locally. But after a build it doesn't seem to work anymore.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[multi-language-blog.zip](https://github.com/squidfunk/mkdocs-material/files/13693758/multi-language-blog.zip)

### Steps to reproduce

1. Unzip the multi language example in a new directory
2. Run the website with local docker container of the insiders branch
```
docker run -p 8000:8000 -v ./:/docs mkdocs-material
```
3. Go to the German blog page: http://localhost:8000/de/blog/
4. Switch to English and notice that the proper page is shown: http://localhost:8000/en/blog/
5. Stop the website
6. Build the website
```
docker run -p 8000:8000 -v ./:/docs mkdocs-material build
```
7. Navigate to the directory with the built website en start a web server
```
cd site
python3 -m http.server
```
8. Go to the German blog page: http://localhost:8000/de/blog/
9. Switch to English and notice that it shows the Home page instead of the Blog page

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! This happens because none of the projects set a [`site_url`](https://www.mkdocs.org/user-guide/configuration/#site_url). MkDocs automatically sets the `site_url` to `http://localhost:8000` when you serve the site, so this is not an issue when serving. The projects plugin tries its best to deduce the `site_url` of nested projects, but for this to work, the top-level project must have a `site_url`. 

Setting `site_url` to __any__ URL in the top-level `mkdocs.yml` fixes the problem:

``` yaml
site_url: https://example.com/
```

You should set `site_url` to the final URL of your site.  Next time we work on the plugin, we'll investigate whether we can automatically set the site URL, issue a warning, or add a warning to the documentation. Until then, this issue is considered resolved.
