### ISSUE TITLE
Allow body and article CSS based on page `status`

### ISSUE THREAD

**Issue by phreed** [squidfunk/mkdocs-material#6553]
### Context

Cause page to be styled based on the status.

### Description

There is already a https://squidfunk.github.io/mkdocs-material/reference/?h=status#setting-the-page-status 
It is possible to set the style of the menu elements (nav:) based on the `status`.
I would like a class added to elements of the page to make it possible to style them as well.
Supposing a foo status I would like the div containing the article (and the `body`) to be classified:
```html
<div class="md-content md-status--foo" data-md-component="content">
       <article class="md-content__inner md-typeset">
...
       </article>
</div>
```

### Related links

- [indicate specific pages as new or deprecated](https://github.com/squidfunk/mkdocs-material/issues/2991)
- [setting the page status](https://squidfunk.github.io/mkdocs-material/reference/?h=status#setting-the-page-status)

### Use Cases

This extends the capability already present in https://squidfunk.github.io/mkdocs-material/reference/?h=status#setting-the-page-status
The styling will be done with CSS.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for the suggestion. Interesting idea, but we're currently not considering adding more switches to the templates, because we're planning to do a face lift, and for that we will need to move some things around with possibly breaking changes. We'll consider this when we rework the templates and styles.

In the meantime, please use [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) and override [`base.html`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/base.html).
