### ISSUE TITLE
Clicking the same version from the version dropdown takes you to the home page

### ISSUE THREAD

**Issue by syeda-git** [squidfunk/mkdocs-material#6657]
### Bug description

I am using Mike for the version picker function. If there are two versions and you select the other version, the same page in that version show up. However, if you click the same version, you are taken to the Home page of the version. 
The expected behavior should be to load the current page and not go to the Home page of the selected version.

### Related links

- [Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)
-

### Reproduction

https://syeda-git.github.io/mkdocs-sandbox/2.0/about/

### Steps to reproduce

1. Open the link/page provided above.
2. Click 2.0 from the version dropdown.
3. You are taken to the Home page of 2.0.
4. Expected behavior - The current page of 2.0 should be reloaded.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Unfortunately, this issue does not include a self-contained reproduction, as demanded by our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/), so we're unable to investigate. Yes, I can see that the error happens on your site, but we don't have the possibility to debug it. Note that [our version example repository](https://squidfunk.github.io/mkdocs-material-example-versioning/0.3/bar/) does not exhibit this behavior. If you are on version 0.3 (built with Material for MkDocs 8.x), and click on the version selector, you stay on the same page. If you witch to 0.2, the error is prevalent, but 0.2 was built with Material for MkDocs 7.x, so the error was fixed in the meantime.

Thus, this issue is not reproducible and can be closed. Next time, please provide a reproduction right away. Thank you!

**Comment by syeda-git** [comment]
@squidfunk This defect is for a use case where there are more than one versions of the doc. The info plugin creates a zip for a version. So, i have to upload at least two zip files and you have to merge them. Is that fine or is there any other way?

**Comment by squidfunk** [comment]
I don't think two reproductions are necessary. Please create the most basic reproduction and provide steps for us, i.e., something like:

1. Unzip reproduction
2. Deploy with mike with `...`
3. etc.

Also, please, please, please make sure to go through _all_ steps mentioned in our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/), most importantly upgrading to the latest version. Additionally, did you check the link to our example repository? Does that work for you?
