### ISSUE TITLE
Language Selector Icon: Add Two-Character language code of the current language next to icon

### ISSUE THREAD

**Issue by ztheory** [squidfunk/mkdocs-material#6692]
### Description

Print the two-character language code (ex: EN) of the current language next to the language selector icon to make it more obvious that it's a language selector.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

Not all readers of documentation will recognize the "language" icon in the header which signifies a language selector. What would make it more obvious is to also display the two-character language code next to it. Imagine older or non-technical readers, who are not experts in modern website design and theory.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We're currently not considering this change for integration into core, because we regard it as customization. One of the problems is that it would take up more space on mobile, leaving less space for the title. Another problem is that there's currently no logic except for "stay on the same page" that detects the current language being present. The reason is that there's no explicit binding between URL and selected language.

We'll consider this as an extension request in the future once we work on site language selection again, but for the time being it is considered out of scope and should be resolved with customization.
