### ISSUE TITLE
Colours: Enable the Primary and Accent colours to be configured using HEX colour codes

### ISSUE THREAD

**Issue by chrimaho** [squidfunk/mkdocs-material#6793]
### Context

In the [Changing the colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/) page, there is some very detailed and helpful instructions for setting the site colour scheme. Particularly, there is info about changing the config in the [Primary color](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color) and [Accent color](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color) sections. Here, it specifies a suite of text values which can be translated in to colour behind the scenes by CSS. For anything outside of this list of colours, there is info provided in the [Custom colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors) section for adding it.

### Description

What I'd like to see is the ability to add Hex values directly to the configuration. See below example for what the configuration may look like. By adding this HEX value here would enable the page to render with the primary colour being whatever HEX code is specified here. This would not replace the current setup of specifying the colours as text values; it would be in addition to it. So, the site colour selector would need to determine if the text specified is within the list of default colours then use that, and if not then is the value a valid HEX code then use that, and if not then throw an error because the colour configuration would either need to be a valid text value or a valid HEX value.

### Related links

- [Changing the colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)
- [Primary color](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
- [Accent color](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color)
- [Custom colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors)

### Use Cases

By adding this functionality, it would:

1. Enable more flexible additions of a whole range of colours.
2. Reduce the complexity when adding custom colours. Not everyone will easily be able to add this required custom CSS script.

### Visuals

The current configuration looks like this:

```yaml
theme:
  palette:
    primary: teal
    accent: indigo
```

I'd like to be able to add a custom colour like this:

```yaml
theme:
  palette:
    primary: "#167D86"
    accent: indigo
```

This `#167D86` colour is close to `teal`, but a little bit darker.

You may say 'why not just use teal?' The exact color used in this example is unimportant. I simply include it here as an example of how the configuration may look like if we were to add a HEX code instead of a text value.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! This was already suggested several times before, but I currently can't find it. We're not considering of implementing this, because it makes customization more tedious. One reason is that there is no single primary or accent color, but there are different shades of a color, that are currently not possible to deduce from one canonical color in CSS:

https://github.com/squidfunk/mkdocs-material/blob/4fd52fd6ef02e203035c016c2b81606d998e1352/src/templates/assets/stylesheets/main/_colors.scss#L27-L43

Users would need to specify all shares, or results will look very weird, as only parts of the color palette are replaced when using a single color. Customization is actually only a little more involved in that you create a file where you put those definitions, so only one additional level of indirection. This is, and will likely forever be the way to customize Material for MkDocs, because this is also where all visual other customizations must go.

Closing as resolvable with [customization](https://squidfunk.github.io/mkdocs-material/customization/).

**Comment by squidfunk** [comment]
One more thing:

> Reduce the complexity when adding custom colours. Not everyone will easily be able to add this required custom CSS script.

You only need to copy and paste 5 lines of CSS and 5 lines of `mkdocs.yml` [from our documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors-docsstylesheetsextracss). I'm afraid we cannot make it any simpler than that without introducing additional (in my view) unnecessary complexity.
