### ISSUE TITLE
Default CSS preventing embedded tweets from having transparent borders

### ISSUE THREAD

**Issue by perpil** [squidfunk/mkdocs-material#6889]
### Context

I'm trying to embed a tweet into my site.  In dark mode, borders on a tweet show up as white and not transparent.  It has something to do with material css. If I create a blank html page with a dark background and embed a tweet the corners look fine.  I cut this as a [discussion](https://github.com/squidfunk/mkdocs-material/discussions/6602) originally but it also happens on the mkdocs material site.  I have been unable to pinpoint which piece of material CSS is causing this.

<img width="353" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/97474956/a1da1eb5-e2c9-419d-91c2-478a154f32ca">

### Bug description

Material's CSS is causing corners on embedded tweets to look bad in dark mode when they are rendered.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Discussion #6602](https://github.com/squidfunk/mkdocs-material/discussions/6602)

### Reproduction

[9.5.13+insiders.4.53.1-css-twitter-embed-corners.zip](https://github.com/squidfunk/mkdocs-material/files/14542241/9.5.13%2Binsiders.4.53.1-css-twitter-embed-corners.zip)

### Steps to reproduce

1. Embed a tweet on any mkdocs material site in dark mode.  Or look at [this page](https://squidfunk.github.io/mkdocs-material/insiders/#what-sponsorships-achieve) in dark mode.
2. Corners will be square and white instead of the color of the background.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by alexvoss** [comment]
The tweet is embedded using an `iframe`. That means that all of the styling of it is controlled by Twitter and is unrelated to the styling applied by Material. I am afraid that there is no pure CSS way to influence the styling. You can get Twitter to render the tweet in dark mode by adding `data-theme="dark"` to the embed code. However, that makes things worse...

<img width="571" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/4134224/d8fb1afc-fec8-4141-ac90-9a1a946f0e71">

I could not find anything on the [embedded tweet parameter reference](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference) that would change the background of the iframe. Not sure if it is possible to do from outside as the browser security model should prevent this? Unless you can convince Twitter to put a dark themed embedded tweet into an iframe with a dark background, I am afraid you may be stuck. That said, I am not an expert on matters of web design, so there is a chance I have missed a trick.

**Comment by squidfunk** [comment]
@perpil is right – it does not happen with the  `mkdocs` and `readthedocs` themes, only `material` seems to replace the transparent background. I've not yet managed to find out why. It's very weird. Here's `readthedocs` with red background for demonstration purposes. If you switch to `material`, the background appears.

<img width="481" alt="Bildschirm­foto 2024-03-09 um 13 52 03" src="https://github.com/squidfunk/mkdocs-material/assets/932156/cdd046e1-f8fd-476e-8488-bf2dc92c6ee4">

**Comment by squidfunk** [comment]
This line is causing the problem:

https://github.com/squidfunk/mkdocs-material/blob/9d387d042887908c1644251f25312a4b81361717/src/templates/assets/stylesheets/palette/_scheme.scss#L34

If you remove the declaration, borders are transparent. I'm not sure why. This might be a bug in or an interference with Twitter's CSS. We should not remove the `color-scheme` declaration, because it denotes to the browser that it should render unstyled UI elements in light or dark appearance. For this reason, I've added a new declaration in 1d6dd99, which will reset the property for `iframes` only, fixing the problem:

<img width="574" alt="Bildschirm­foto 2024-03-09 um 14 04 28" src="https://github.com/squidfunk/mkdocs-material/assets/932156/52f9644f-ca27-4a34-9f03-da6967b8cd94">

**Comment by perpil** [comment]
Thanks for the quick work, I tested it and it does indeed resolve it for the repro I attached, but when you set a palette, it doesn't.  You can repro by toggling to dark mode with what I attached.  Is there a fix that works if for all scenarios?

[9.5.13+insiders.4.53.1-css-twitter-embed-palette.zip](https://github.com/squidfunk/mkdocs-material/files/14551534/9.5.13%2Binsiders.4.53.1-css-twitter-embed-palette.zip)

**Comment by squidfunk** [comment]
Hmm, indeed, very strange. I'd expect that `color-scheme: initial` resets the value appropriately, but it doesn't. My testing shows that `color-scheme: auto` seems to fix both cases, so I applied it in 8244ff3. Can you confirm?

**Comment by perpil** [comment]
I'm on the insiders version, can you push it there too?

**Comment by squidfunk** [comment]
I just did, could you please check `master`?

**Comment by perpil** [comment]
Hmm, it still looks like this for me on Firefox 123.0 Mac:

<img width="724" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/97474956/56aaba3a-21e0-4173-a3cb-b0dfcb4a9f2f">

But it looks fine on Chrome 122:

<img width="585" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/97474956/66230d5a-f634-4eca-8c54-cd496c639f7c">

**Comment by squidfunk** [comment]
I have not tested Firefox. I'll look into it again. This is really weird...

**Comment by squidfunk** [comment]
Related: https://fvsch.com/transparent-iframes

**Comment by squidfunk** [comment]
I think it's fixed with 750b79889 (already on Insiders). `color-scheme: light` omits the background in Chrome, Safari and Firefox on macOS. However, reading the article, it seems to be underspec'd or a browser bug.

**Comment by squidfunk** [comment]
Released as part of [9.5.14](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.14).

**Comment by squidfunk** [comment]
The changes had another side effect – now Giscus rendering is broken. I'm not yet sure how we can ensure that both work.

**Comment by squidfunk** [comment]
I'm sorry, but we have to revert the changes we made to fix the issue mentioned here. The reason is that I currently see no way forward to fix this in a general fashion. If we apply `color-scheme` to `.md-typeset iframe`, it will override any value set by the `iframe` itself. For instance, this will lead to Giscus looking like this ([screenshot from our website right now](https://squidfunk.github.io/mkdocs-material/blog/2023/11/30/adding-a-badge-to-your-project/)):

<img width="734" alt="Bildschirm­foto 2024-03-23 um 08 29 06" src="https://github.com/squidfunk/mkdocs-material/assets/932156/ad503b48-efd4-4c5d-b89f-635c30311d2f">

Twitter expects us to set `color-scheme` to `light`, or you will get the borders we tried to fix here. Giscus expects us to set it to `light dark`. Thus, it is very much dependent on the contents of the `iframe` what value you need. Another option would be to refrain from setting `color-scheme` entirely, but would decrease accessibility, as unstyled form elements will now always appear light, even in dark mode. We could try to use a selector like `.md-typeset :not(iframe)`, but that is even more invasive and have unforeseen other side effects, as it would mean that this selector would apply to _every_ element inside `.md-typeset`, except for iframes.

For this reason, I decided to revert the changes we made in https://github.com/squidfunk/mkdocs-material/commit/750b79889d43a343ad8b5864c4f461991690901a until a better solution is found. I'm quite at the end of ideas how to support borderless arbitrary iframes. If somebody cooks up a solution, please create a PR!

**Comment by squidfunk** [comment]
The ideal solution would be Twitter CSS settting the value on the `iframe`, or Firefox fixing the problem.

**Comment by perpil** [comment]
Is it possible to override the `color-scheme` for just twitter tweets in my extra css?  The twitter iframe always is inside a div with class `twitter-tweet`

**Comment by squidfunk** [comment]
Yes, of course, this should do the trick:

``` css
.twitter-tweet iframe {
  color-scheme: light,
}
```

**Comment by perpil** [comment]
Ok that's a good enough workaround for me if you don't want to pollute the main css with it, I tested it and it works in FF and Chrome, thanks!

**Comment by squidfunk** [comment]
Perfect, thanks! Sorry for the inconvenience this is causing, but I hope my explanation made sense and outlines that the situation is tricky, to say the least.
