### ISSUE TITLE
Filter files based on frontmatter property

### ISSUE THREAD

**Issue by nonsonogio** [squidfunk/mkdocs-material#6926]
### Description

I would like to suggest implementing a feature that control whether a certain file gets published or not based on a specific property (or tag) in the front matter.

For example, only files with this property `visibility: public` would get published.

The default behaviour could be either (configurable):
- that a file is published by default, while property `visibility: private` would prevent a file from being published
- or that a file is _not_ published by default, and the property `visibility: public` would let it be published

I believe this is a nice to have in this project because external plugins are prone to interoperability issues.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

An author may not want to publish some markdown files, yet keep them in the project.
This is a case, for example, if I have my documentation md files in a private repository and want to publish only part of them to a public website.
Or if some specific files contain sensitive inforamtion and the author does not want to publish them.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by kamilkrzyskow** [comment]
Not in the front matter, but MkDocs has an `exclude_docs` config option: 
https://www.mkdocs.org/user-guide/configuration/#exclude_docs

Also considering the exclusion logic:
https://github.com/mkdocs/mkdocs/blob/00b648f0884244a139f034554b59a032113176f6/mkdocs/structure/files.py#L323-L336
I guess you could create a hook that changes the Inclusion of a file based on the front matter property 🤔 

I'm not sure how tricky it would be as the front matter is read later, probably after the inclusion check.

**Comment by squidfunk** [comment]
Thanks for suggesting. 

I'm not sure it can be easily implemented as a hook, because as I understand you would want to exclude the file from the navigation as well, so the hook must be run _before_ [`on_nav`](https://www.mkdocs.org/dev-guide/plugins/#on_env). However, front matter is available only as late as [`on_page_markdown`](https://www.mkdocs.org/dev-guide/plugins/#on_page_markdown) which means the navigation has already been populated. This means you would need to find the relevant entries in the navigation and remove them again.

As @kamilkrzyskow also points out, it's already supported via [`exclude_docs`](https://www.mkdocs.org/user-guide/configuration/#exclude_docs). A much simpler idea would be to use a naming convention and use an exclude pattern like `*.hidden.md`:

``` yaml
exclude_docs: |
  *.hidden.md
```

It is equivalent to having it in the front matter, but uses MkDocs built-in functionality. Please understand that we're not considering implementing something that is already equivalently supported with a native feature.

**Comment by nonsonogio** [comment]
Hi, thank you for your time considering this anyway.

I am of the opinion that the existing functionality is a different use case, as what I was proposing is based on the frontmatter, which is something that the author can decide while writing and change later, as such it's bound to the document lifecycle, and not to the filename or folder name. 

A static ignore list works better what you know beforehand which are the patterns you want to exclude, does not support an explicit-include logic, and may require you move a document from one folder to another.

Anyway I understand the situation, maybe this idea could better fit within mkdocs framework itself :)
