### ISSUE TITLE
Blog post date-only format

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#7001]
### Context

Use of the blog plugin without further settings.

### Bug description

As discussed in https://github.com/squidfunk/mkdocs-material/discussions/6998#discussioncomment-8973038, the post date by default contains a time was well, which is set to 12:00AM. It should display only a date, regardless of whether the page header contains only a date or a date and time. This has also been observed in https://github.com/squidfunk/mkdocs-material/discussions/6996. 

While is is possible to fix this through customization, the default should be only the date.

Note that the default was date only as late as 9.5.13+insiders.4.53.1.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.post_date_format

### Reproduction

[9.5.16+insiders.4.53.4-datetime-blog.zip](https://github.com/squidfunk/mkdocs-material/files/14824075/9.5.16%2Binsiders.4.53.4-datetime-blog.zip)

### Steps to reproduce

1. mkdocs serve
2. navigate to http://localhost:8000/blog/
3. Observe the date and time in the blog index
4. Click though to the blog post itself
5. Observe the data and time in the post metadata

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is a regression of accepting and merging https://github.com/squidfunk/mkdocs-material/pull/6981, which switched to `format_datetime` instead of `format_date`. The predefined format `long` will now refer to [a format string that includes the time](https://babel.pocoo.org/en/latest/api/dates.html#date-and-time-formatting). Rendering the blog post without time should be the default, as our current assumption is that that's what most users would expect.

1041766d81ccdd53200f206860d17e6a64d4e65b adds a condition that checks if the author uses one of the [predefined time formats](https://github.com/python-babel/babel/blob/e0d10183635b9ae1d37c31811e23c8974a1bc31e/babel/dates.py#L41), the blog plugin should use `format_date`. However, if a custom string is given, the plugin will make use of `format_datetime`, so we allow explicitly opting into using format strings including time. This still fixes #6981 but allows us to keep sensible defaults.

**Comment by squidfunk** [comment]
Released as part of [9.5.17](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.17).
