### ISSUE TITLE
Instant preview is enabled on footnotes

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#7051]
### Context

Ideally I'd like to enable `material.extensions.preview` on every page, but it looks bad when hovering over footnote links.

### Bug description

1. Previews for footnotes are generated when `material.extensions.preview` is enabled, even when `content.footnote.tooltips` is not.
2. Previews for footnotes which are generated with the new Markdown extension show the footnote text at H3 size with extra padding:
    ![hVSCj1ooGdVoOAvr](https://github.com/squidfunk/mkdocs-material/assets/3637842/b555bd75-6b78-443f-bae2-4aa0f93441d3)

Either one of these being fixed would be fine with me, but I think it probably makes the most sense to just not handle footnote links with the instant preview markdown extension.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/reference/footnotes/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/

### Reproduction

[9.5.17+insiders.4.53.6-instant-preview-enabled-on-footnotes.zip](https://github.com/squidfunk/mkdocs-material/files/14985262/9.5.17%2Binsiders.4.53.6-instant-preview-enabled-on-footnotes.zip)

### Steps to reproduce

1. Enable instant previews on page
2. Add footnote

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting.

> Ideally I'd like to enable material.extensions.preview on every page, but it looks bad when hovering over footnote links.

I strongly recommend not to do that. We'll also likely be removing the global feature flag again, as it was the one of the earliest ideas of how instant previews could look, and we really should make them selective. Otherwise, too many links will get previews. We'll look into whether we can somehow "catch" instant previews adding a link to footnotes, but I recommend using our new [Markdown extension](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#automatic-previews). I'm curious, does this relate to #7040?

**Comment by jonaharagon** [comment]
> but I recommend using our new [Markdown extension](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#automatic-previews).

The automatic markdown extension is what I'm reporting the bug with though? Sorry if that wasn't clear. Your documentation says "you can use them on any internal link that points to a header on another page," but they are also being generated on internal links that point to footnotes, which is the whole problem.

Actually, I've otherwise been pretty happy with having them enabled globally, with the exception of a couple pages we added to `sources.exclude`.

**Comment by jonaharagon** [comment]
Just to be perfectly clear, this report is **not** related to this setting (which I didn't know was a thing, but I might've been confusing with my use of the term "globally"):

```
theme:
  features:
    - navigation.instant.preview
```

**Comment by squidfunk** [comment]
Oops, sorry. I wasn't on my laptop and could only answer quickly, so I got stuck on:

> Ideally I'd like to enable material.extensions.preview on every page, but it looks bad when hovering over footnote links.

Which I mixed up with `navigation.instant.preview` due to "every page" 🤦‍♂️ I agree that footnotes should definitely not be mounted, so we'll need to find a way to ensure that. I'm still not sure how we handle links to the same page. Previously, we excluded anchor tags, but added them back because it was asked for, see https://github.com/squidfunk/mkdocs-material/issues/6704#issuecomment-1955851957. Any thoughts?

**Comment by jonaharagon** [comment]
I'm kind of confused now, because I seem to get the same behavior as `navigation.instant.preview` by simply enabling `material.extensions.preview` without any options (i.e. all internal links get previews, even without the `data-preview` attribute set). That is how the Markdown extension is supposed to work though right? I just don't get why both options to enable them globally exist.

Anchor links to _headers_ on the same page work fine for my website, so it doesn't *really* matter to me, but I also think if I had the option to disable that behavior I probably would.

**Comment by squidfunk** [comment]
If you read #6704, you'll see that `navigation.instant.preview` predates the Markdown extension. Enabling this feature flag led to all internal links rendering previews. And no, the Markdown extension without any options should do exactly nothing, so that's an error we have to fix.

> Anchor links to headers on the same page work fine for my website, so it doesn't really matter to me, but I also think if I had the option to disable that behavior I probably would.

We can check if we can add this as another option to the Markdown extension.

**Comment by squidfunk** [comment]
Fixed in [`1f5fb72`](https://github.com/squidfunk/mkdocs-material-insiders/commit/1f5fb72d901aeb391bebf9e79d197bc94fdbbe0e).

**Comment by squidfunk** [comment]
Released as part of [9.5.19+insiders-4.53.8](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.8).
