### ISSUE TITLE
`tags_file` deprecation, strict mode, and non-Insiders compatibility

### ISSUE THREAD

**Issue by kcgthb** [squidfunk/mkdocs-material#7146]
### Context

```
mkdocs                     1.6.0
mkdocs-material            9.5.20+insiders.4.53.8
```

### Bug description

The new `tags_file` deprecation prevents building sites in strict mode. But removing that option breaks compatibility with non-Insiders builds.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [`tags_file` documentation](https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.tags_file)
- [`tags_file` deprecation](https://github.com/squidfunk/mkdocs-material/blob/5cb3117f50c78abfef6817b72cb09910decd272b/CHANGELOG#L228)

### Reproduction

With the following recommended configuration in `mkdocs.yml`:
```
  - tags:
      tags_file: docs/tags.md
```
building the site in strict mode now fails, because of the deprecation warning:
```
$ mkdocs build -s
WARNING -  Config value 'plugins': Plugin 'material/tags' option 'tags_file': The configuration option 'tags_file' has been deprecated and will be removed in a future release.

Aborted with 1 configuration warnings in 'strict' mode!
```

But removing that option is not really possible, as it would break the tag index functionality for non-Insiders builds.

How can we continue to build in strict mode (especially to catch errors in CI/CD scenarios) while retaining compatibility between Insiders and regular builds?

### Steps to reproduce

1. use `tags_file`
2. build in strict mode

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. [We're using MkDocs own `Deprecated` configuration helper](https://github.com/squidfunk/mkdocs-material-insiders/blob/0bbf520045f25af8278c2dd512b4181d01c7f906/src/plugins/tags/config.py#L85), and it could be considered a bit unlucky that this emits a WARNING and not an INFO message, which fails the build in `strict` mode. If we would go and fix this on our side, we would need to entirely opt-out of MkDocs canonical way of deprecating configuration options, which should be considered as a last resort, since we should try to abide to best practices and what MkDocs offers us.

IMHO, the most sensical thing would be that the [`Deprecated`](https://github.com/mkdocs/mkdocs/blob/53fec50e57f6bad152ad589a83ae83d1cd72b2f5/mkdocs/config/config_options.py#L384-L452) helper emits something like the following, which are deprecation warnings we fixed when upgrading to 1.6, as was reported in https://github.com/squidfunk/mkdocs-material/issues/7119#issuecomment-2081713974:

```
INFO    -  DeprecationWarning: Do not access Theme._vars, instead access the keys of Theme directly.
             File "/opt/homebrew/lib/python3.10/site-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 82, in on_config
               theme_locale = custom_theme._vars.get("locale")
             File "/opt/homebrew/lib/python3.10/site-packages/mkdocs/theme.py", line 87, in _vars
               warnings.warn(
INFO    -  DeprecationWarning: To replace an existing file, call `remove` before `append`.
             File "<snip>/mkdocs-material/material/plugins/privacy/plugin.py", line 445, in _queue
               self.assets.append(file)
             File "/opt/homebrew/lib/python3.10/site-packages/mkdocs/structure/files.py", line 100, in append
               warnings.warn(
```

MkDocs uses this approach itself for their internal APIs, e.g., the `Files` collections, [see an example](https://github.com/mkdocs/mkdocs/blob/53fec50e57f6bad152ad589a83ae83d1cd72b2f5/mkdocs/structure/files.py#L100-L102), but emit warnings for plugin configurations. IMHO, this is inconsistent, so before we act here, we should discuss this with the maintainers of MkDocs. Interestingly, the aforementioned `DeprecationWarnings` were formerly also raised with level WARNING and de-escalated to INFO [in a subsequent release](https://github.com/mkdocs/mkdocs/blob/53fec50e57f6bad152ad589a83ae83d1cd72b2f5/docs/about/release-notes.md?plain=1#L810).

@kcgthb could you maybe help us and raise this as an issue over at MkDocs? Please also link to this issue and tag me. I'm closing this issue as upstream. If after discussion, no solution can be found upstream, we can reopen and discuss how we want to handle this, but we would effectively need to build around MkDocs, so nothing we fancy doing.

**Comment by kcgthb** [comment]
@squidfunk Sure thing: see https://github.com/mkdocs/mkdocs/issues/3696
Thanks for the suggestion!

**Comment by kcgthb** [comment]
@squidfunk doesn't seem like there's much traction on the MkDocs side :\
So what are our options here, with `tags_file` being deprecated, but still needed for non-Insiders builds?

**Comment by squidfunk** [comment]
I really don't think it's a good idea to speed-run this, because `tags_file` is not the only problem. We have several deprecated options that all suffer from the same problems, which comes from MkDocs. It's a systemic thing that, IMHO, definitely needs to be solved in MkDocs not here, so we should try an ask Tom, who announced being back as a maintainer what his view is. Otherwise we'd effectively need to build around MkDocs, as mentioned in https://github.com/squidfunk/mkdocs-material/issues/7146#issuecomment-2092364939.

**Comment by squidfunk** [comment]
See https://github.com/mkdocs/mkdocs/issues/3696#issuecomment-2117407805

**Comment by kcgthb** [comment]
Thanks! In the interim, maybe a middle-ground approach would be to un-deprecate `tags_file`, until this is addressed at the MkDocs level? 

Because right now, the issue is that `tags_file` still needs to be present for non-Insider builds, which makes it difficult to build a site using Insiders, and still have it gracefully degrade for non-Insiders builds (I'm thinking external PRs and contributions, for instance).

Does that make sense?

**Comment by squidfunk** [comment]
Hmm, why not, yes. It doesn't impact any functionality. Would you like to create a PR for this on the Insiders repository?
