### ISSUE TITLE
multi blog instances share the same `post_date_format` date filter

### ISSUE THREAD

**Issue by kamilkrzyskow** [squidfunk/mkdocs-material#7175]
### Context

Depending on the topic of a blog, it could require a different level of formality/detail with the date display.

### Bug description

The last instance of a blog sets its own date filter in `on_env` and overrides the previous ones.
Only the last `date` filter is used inside the Jinja2 templates. 

---

I believe there is a minor/major rewrite required where each `Post` would get a reference to the instance of the Blog plugin that processed it, and then in the templates something like this would perhaps be possible 
```jinja2
post.config.date.created | post.blog.date_filter
```
but that's just an idea, not tested.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [post_date_format option](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.post_date_format)
- [`on_env` that runs for each instance of the blog plugin](https://github.com/squidfunk/mkdocs-material/blob/b2b6571e7e82f92fccf55bd0cb63eb8628964ba8/material/plugins/blog/plugin.py#L297-L323)
- [Example usage of the `date` filter in the templates](https://github.com/squidfunk/mkdocs-material/blob/b2b6571e7e82f92fccf55bd0cb63eb8628964ba8/material/templates/partials/post.html#L19)

### Reproduction

[9.5.22-post_date_format.zip](https://github.com/squidfunk/mkdocs-material/files/15287013/9.5.22-post_date_format.zip)

### Steps to reproduce

1. Run `mkdocs serve`
2. Notice that both the `Blog` and `Movies` use the `YYYY` format, which was set only to the `Movies` instance.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by kamilkrzyskow** [comment]
Additionally, when making this reproduction, a very odd thing happened. Even though I've set the movies examples to 2018 and 2011 in the files, they display as 2018 and 2010 when rendered on the website. First was floating point imprecision and now date imprecision 😆

**Comment by squidfunk** [comment]
Thanks for reporting. Hmm. I think this one will be very hard to solve, since we cannot guarantee a specific environment for each blog page. Thus, I'd say this is currently unfixable with the architecture of MkDocs, as all plugins have to go through `on_env`, and it's not possible to scope the environment to specific pages.

**Comment by squidfunk** [comment]
Note that what you proposed, i.e, attaching a date filter explicitly to a blog post is a pattern that is not encouraged by MkDocs. Thus, opening a discussion upstream might be the best idea. I'm tagging this as not feasible for now. This must be taken upstream in order to find a way how to register environment variables _per page_.

**Comment by kamilkrzyskow** [comment]
Hmm, when you mentioned `on_env` for each page, I thought of `on_page_context`. I'm not sure if a filter needs to be defined via `env.filters` to work with the `| filter` syntax, would have to check if it works with any variable available, also I'm not sure if the event isn't skipped for the posts.

Aside from that I don't think there is a need for `on_env` for each page 🤔
Considering that in the blog plugin each structure class `Post`, `View` etc. extends `Page` and later adds custom properties to them I would say it has long passed the point of "pattern that is not encouraged by MkDocs", but to your point is there any docs where MkDocs truly actively discourages a specific approach?

`File.generated_by` was accepted as a valid marker with the release of 1.6.0, and before it was just a convention. Just like `File.page` and `Page.file` have a sibling connection, I would promote the same for `GeneratorPlugin.page` and `Page.generator` 😅 

So if my approach with
```jinja2
post.config.date.created | post.blog.date_filter
```
isn't feasible, because it uses a filter through a chain of references that are attached to a post, then how about this:
```py
def get_creation_date(post: Post):
    # Using the blog plugin reference from the post
    format = post.blog.config.post_date_format
    return self._format_date(post.config.date.created, format, config)
env.filters["post_creation_date"] = get_creation_date
env.filters["post_update_date"] = get_update_date  # omitted the definition above
```
```jinja2
post | post_creation_date
```

---

Yet another idea to work around it would be to save the `post_date_format` in the front matter / config of the `Post`
Later on set it inside the template in the context `set post_date_format = post.config.post_date_format`
And later pass the context to the filter, but I'm not sure if using the `@pass_context` decorator would be enough.
Use the `post_date_format` from the context 🤔 
That's probably my least favourite solution to this issue, too many sequential actions.

**Comment by squidfunk** [comment]
I've tagged this as upstream now ✌️

**Comment by kamilkrzyskow** [comment]
I wrote the Issue upstream, I've considered another one to ask about extending the `generated_by` of the File object to the Page object itself. However, the Page object by default has a reference to the File object, even if it's virtual, so I guess this is not needed.

So given that the Post/Page object should have a reference to the File object is there a way to get the Blog instance? 
I initially thought, that it's not possible as the `generated_by` value is a string with the name of the plugin `material/blog`.
However, during my testing it turned out that each next instance of the blog has a number in the name `material/blog #2` etc. 

So given that the now non-hacky approach of using the external `File.generated()` constructor would properly set the unique name with the number it would be possible to get the blog instance via `config.plugins[post.file.generated_by]`, but still the template would have to be modified to include a `post` aware filter, so let's hope MkDocs will extend `on_page_context` with `env`.

Given `File.generated()` this is outdated :v::
https://github.com/squidfunk/mkdocs-material/blob/7368c7f759e6163f7cce9af15d0b0d7bfc7a1d52/src/plugins/blog/plugin.py#L839-L844

**Comment by squidfunk** [comment]
> So given that the Post/Page object should have a reference to the File object is there a way to get the Blog instance?

Currently not. The thing is: you don't want the blog instance, which is a [`View`](https://github.com/squidfunk/mkdocs-material/blob/7368c7f759e6163f7cce9af15d0b0d7bfc7a1d52/src/plugins/blog/structure/__init__.py#L219), a subclass of page, you want the blog plugin instance to access the formatting capabilities. I don't think it's a good idea to pass the plugin instance to the template, since template authors could call hooks from the template, potentially leading to infinite loops. I've lately started to implement far more modular plugins, and the blog plugin is a good candidate to switch to the same approach, factoring out the formatting capabilities, but I currently have no bandwidth to do it, as I'm working tirelessly on very big upcoming changes (still tba).

> Given File.generated() this is outdated ✌️:

Correct. We can definitely switch to the new `File.generated` API, but I'd consider it a very low priority issue, since everything works the same right now, so why change something that currently works nicely 😉
