### ISSUE TITLE
Cannot use numbers as titles

### ISSUE THREAD

**Issue by PlasmaHH** [squidfunk/mkdocs-material#7209]
### Bug description

When adding a title that is only a number like:
```yaml
---
tags:
    - 1234
---
```

in the header, then `material/plugins/tags/plugin.py` line 149 in `_render_tag_index` errors out in the `sorted(self.tags.items())`  part because for some reason I was not able to figure out it did convert the key part to an int and thus python complains about the inability to compare ints and strings.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

Just add a number only as the title to any project that is using tags.

### Steps to reproduce

Just add a number only as the title to any project that is using tags.

### Before submitting

- [ ] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [ ] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed in 1b346eb57b2871eca8f5e78444cfc83d35ab2a2e. I'm pretty sure this is a regression, as I remember to already have fixed this, but it may have got lost in an Insiders merge somehow. Regardless, numbers should work again now.

Next time, please respect the time and effort we put into supporting our users, by sticking to our bug reporting process and providing a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). It is absolutely mandatory per our bug reporting guidelines. Thank you.
