### ISSUE TITLE
Table display “flickers” when refreshing the page

### ISSUE THREAD

**Issue by syxc** [squidfunk/mkdocs-material#7219]
### Bug description

Table display “flickers” when refreshing the page.

https://github.com/squidfunk/mkdocs-material/assets/315633/3e572985-f3e9-4ddd-bb5b-42565d4c7a09

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[mkdocs-demo.zip](https://github.com/squidfunk/mkdocs-material/files/15470534/mkdocs-demo.zip)

### Steps to reproduce

refreshing page

### Browser

Chrome, Safari, Edge, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by alexvoss** [comment]
Thanks for reporting. You could help us figure out what is going on by removing things from your projects that are not needed to reproduce the effect. The [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) page suggests starting from the other end by producing a new project and then adding things in until the effect is observed.

**Comment by syxc** [comment]
Sorry, just confirmed, this issue doesn't seem to be a problem with mkdocs-material, I found that the `tables` extension for mkdocs also has the problem I reported.

**Comment by squidfunk** [comment]
Thanks for reporting. The slight repositioning comes from the fixes that Material for MkDocs has to apply in the browser to make tables properly scrollable, which is implemented in JavaScript. If you turn JavaScript off in your browser, you can see that the jittering stops. It could be fixed, if and only if the tables extension would create the necessary markup from the start. 

Providing a wrapper element should be easy to implement in the [tables extension](https://python-markdown.github.io/extensions/tables/) – I recommend raising this as a potential feature request to [Python Markdown](https://github.com/Python-Markdown/markdown), in order to allow for improving mobile user experience:

``` html
<div class="table">
  <div class="table-wrapper">
    ...
  </div>
</div>
```

The extension could hide it behind a feature flag, so it's downward compatible:

``` yaml
markdown_extensions:
  - tables:
      use_wrapper: true
```

This is what Material for MkDocs currently needs to do:

https://github.com/squidfunk/mkdocs-material/blob/2412a1b7bc0713730ec3d134b26fe503d9421c41/src/templates/assets/javascripts/templates/table/index.tsx#L29-L44

Without this fix, large tables would break the layout on mobile and overflow.

**Comment by syxc** [comment]
I retried it and found something, I recorded a video that you can watch, hopefully it will help with the `mkdocs-material` improvements.

[mkdocs-demo-20240529.zip](https://github.com/squidfunk/mkdocs-material/files/15483989/mkdocs-demo-20240529.zip)

https://github.com/squidfunk/mkdocs-material/assets/315633/8bf91bc6-036c-4af8-9bd3-ad07865c8e81

**Comment by squidfunk** [comment]
Thanks for sharing! We'll check it out ☺️
