### ISSUE TITLE
Use section named file as section index

### ISSUE THREAD

**Issue by SuibianP** [squidfunk/mkdocs-material#7386]
### Description

With `navigation.indexes` enabled and without `nav`, mkdocs-material automatically picks up `section/index.md` as the section index.

It could be helpful to recognise `section.md` as the index page as well.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages

### Use Cases

GitLab wiki uses `section.md` as the index page of `section/` (same base name as section folder name). The proposed change would make it possible to use Gitlab wiki repo directly as the docs storage for easier WYSIWYG experience for non-technical authors.

While much less important and easily changed, it is also the way of [mdsplit.py](https://github.com/markusstraub/mdsplit), which might help with [breaking down large markdown files into chunks for MkDocs](https://github.com/mkdocs/mkdocs/discussions/3765).

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! Definitely a good idea to improve interop with GitLab Wiki. However, this could be an opinionated change that might break existing installations. Could you please provide some more information how you would imagine this to work, e.g., how a directory tree might look and what you would consider a section. It's not apparent to me from the description. Do you mean `section/section.md` or `section.md` alongside a `section/...` folder?

**Comment by SuibianP** [comment]
Thanks for the prompt response! I meant `section.md` alongside `section/*.md`, as GitLab is doing.

```
├── My-Section
│   └── My-Article.md
└── My-Section.md
```

It definitely is opinionated and backward incompatible, and as far as I know the only consumer would be GitLab (GitHub Wiki [does not support page hierarchies](https://github.com/orgs/community/discussions/23914); Hugo seems to be using [`_index.md`](https://gohugo.io/content-management/sections/)). Sadly there is no unified convention for hierarchical document file structures.

Nonetheless, from a user perspective, the chances of breaking existing pages could be slim -- I don't think anyone would have identically named page and folder, without intending the former to be the index page when they enable `navigation.indexes`.

Off the top of my head, maybe there could be an `index_page` configuration under `navigation.indexes`, accepting a document filename to be found in the section directory (mostly `index.md`/`_index.md`), or the special case `"section"` to cover the GitLab case?

**Comment by squidfunk** [comment]
Thanks for providing the additional information. So please note that currently, index support (i.e. special treatment for files called `index.md` when `navigation.indexes` is enabled) is implemented as part of the [`nav-item.html`](https://github.com/squidfunk/mkdocs-material/blob/914bed290098dbac50e609657ec97776477375fe/src/templates/partials/nav-item.html) template:

https://github.com/squidfunk/mkdocs-material/blob/914bed290098dbac50e609657ec97776477375fe/src/templates/partials/nav-item.html#L100-L108

MkDocs itself doesn't treat `index.md` files differently, but there are plugins like [mkdocs-section-index](https://github.com/oprypin/mkdocs-section-index) that add additional functionality. Thus, currently, support would need to be implemented as part of a plugin, because the resulting structure does not resonate with MkDocs, since MkDocs would create two items: a `Section` and a `Page`. While sections can only have a title and child pages, pages cannot have children. Thus, the fix we're applying is to hoist index pages one level up, but that's not possible with siblings, which we would have in the case you described.

However, [the maintainers of MkDocs](https://github.com/mkdocs/mkdocs/discussions/3677) announced that they are working on "[the next version](https://github.com/mkdocs/sketch)" of MkDocs. I recommend [raising this feature request upstream](https://github.com/mkdocs/mkdocs/issues), because it might be a good time to discuss this, as from what I've read it appears that [they're also working on a new data model](https://github.com/mkdocs/mkdocs/issues/3698#issuecomment-2102236287). 

We're closing this as upstream for now.

**Comment by SuibianP** [comment]
For what it's worth, I pieced together some (very unhygienic) workaround which somehow works in my case. It just relocates the Page under the Section as index.

```python
from urllib.parse import unquote
from mkdocs.structure import StructureItem
from mkdocs.structure.files import Files
from mkdocs.structure.nav import Navigation
from mkdocs.config.defaults import MkDocsConfig

def merge(tree: list[StructureItem]):
    for item in tree:
        if item.is_section:
            merge(item.children)
            for other in tree:
                if other.is_page:
                    last_seg = unquote(other.url.rstrip('/').rsplit('/', 1)[-1])
                    if last_seg == item.title:
                        print(other.file)
                        other.parent = item
                        other.file.name = "index"
                        item.children.insert(0, other)
                        tree.remove(other)

def on_files(files: Files, config: MkDocsConfig):
    print(files.src_uris)
    file = files.get_file_from_path("home.md")
    file.dest_uri = "index.html"
    file.name = "index"
    file.url = "./"

def on_nav(nav: Navigation, config: MkDocsConfig, files: Files) -> Navigation:
    merge(nav.items)
    return nav
```

I'm still trying to understand the design of mkdocs internals.
