### ISSUE TITLE
the search for icons on the official docs does not return them in the format they should be used in a website header

### ISSUE THREAD

**Issue by ryzenpay** [squidfunk/mkdocs-material#7416]
### Context

When setting an icon for a page, it goes in the format `<distribution>/<icon>`, but when using the provided search engine on the documentation (https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/?h=icon) they are returned in the format of emojis `(:<emoji>:)`.

### Description

I did find that for example when searching "mail" for icons, you find `":material-mail:"`, and making this `"material/mail"` in the header of the webpage allows for it to work.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

finding icons to use for webpages much simpler

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

edit: github syntax removed my words

**Comment by squidfunk** [comment]
Thanks for noting! The icon search on this page is meant for using them in Markdown, yes. It's because it's part of the reference, which is our guide on writing with Material for MkDocs. If you want to search for icons to be used in one of the settings in `mkdocs.yml`, jump to the appropriate section and find a dedicated search there, e.g. here:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo-icon-bundled

<img width="719" alt="Bildschirm­foto 2024-08-03 um 09 25 12" src="https://github.com/user-attachments/assets/271d7f8b-3c69-43f8-84cb-3aaf6444db64">

We don't want to add another switcher to the icon search in the reference, so we're currently not considering this change, given that there are dedicated icon searches at every location in the documentation where icons can be used.
