### ISSUE TITLE
how to set navigation?

### ISSUE THREAD

**Issue by jzoy** [squidfunk/mkdocs-material#742]
## Description

I noticed that your demo site have a navigation menu above the logo, and i follow the documentation set the structure. But my menu dose not show up. 

Can anybody please tell me how to set this navigation menu?

![image](https://user-images.githubusercontent.com/10555775/37876038-d27d6958-3079-11e8-8a90-e51a162af3e6.png)

**Comment by squidfunk** [comment]
https://squidfunk.github.io/mkdocs-material/getting-started/#tabs

**Comment by CesMak** [comment]
Hey there I have a similar question :) 

Is it possible to kind of not waste so much space for showing the table of contents on the right side or make that optional so that it pops in and out - So that you have more space e.g. show more columns of a large table before it gets scalable.

Another feature that I would prefer would be that the content itself scales more with the size of the screen - it is kind of focused in the mid for bigger screens and not enlarged - e.g. I do not see all columns of a huge table on a 1080x1920 and on a 1366x786 screen....

**Comment by jzoy** [comment]
thanks a lot for your link

**Comment by squidfunk** [comment]
@CesMak: both remarks have been discussed in #242, #410, #619 and #664.
