### ISSUE TITLE
Blog + Social Cards + RSS + Insiders issue

### ISSUE THREAD

**Issue by perpil** [squidfunk/mkdocs-material#7518]
### Context

Setting up rss feeds when you have a blog with social cards per the instructions doesn't work.  It's possible this is a `mkdocs-rss-plugin` issue vs a `mkdocs-material` issue.

### Bug description

`mkdocs build` is looking for the social cards at the wrong path when you add the rss plugin per the docs.
The path in the resulting `feed_json_created.json` has social card paths that are missing the date and are incorrect: http://localhost:8000/assets/images/social/blog/posts/mission.png instead of http://localhost:8000/assets/images/social/blog/2023/09/01/the-mission-statement.png

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#rss
- https://github.com/Guts/mkdocs-rss-plugin/issues/257

### Reproduction

[9.5.34+insiders.4.53.12-rss-social-blog.zip](https://github.com/user-attachments/files/16968446/9.5.34%2Binsiders.4.53.12-rss-social-blog.zip)

### Steps to reproduce

1. `mkdocs build` list errors about loading images with the wrong path.
2. `mkdocs serve` succeeds, but the file at http://localhost:8000/feed_json_created.json has incorrect social links.

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting.

> mkdocs build is looking for the social cards at the wrong path when you add the rss plugin per the docs.

Please report this to the authors of the RSS plugin, since the problem manifests in a file generated by that plugin (`feed_json_created.json`). Furthermore, there have been some issues with the social plugin, e.g., https://github.com/Guts/mkdocs-rss-plugin/issues/257, so it might be related. Essentially, the RSS plugin does not correctly handle the computed blog posts URLs, so this might be an ordering issue among plugins.

The URLs are computed as early as possible (before `on_page_markdown`, in [`on_files`](https://github.com/squidfunk/mkdocs-material/blob/8df393d11158ebc87026e4eea9ed0c887eae2371/src/plugins/blog/plugin.py#L134)), so I'm quite confident the RSS plugin doesn't use the computed URLs correctly.
