### ISSUE TITLE
Unwanted folder index behavior

### ISSUE THREAD

**Issue by FlagHunter01** [squidfunk/mkdocs-material#7561]
## Example setting

Here is the nav for the illustrations:

```yml
nav:
  - Home:
    - Homepage: index.md
    - Ships:
      - Sailships: ships/sails/index.md
      - Steam ships: ships/coal/index.md
    - Trains:
      - trains/index.md
      - Steam trains: trains/coal/index.md
      - Diesel trains: trains/diesel/index.md
```

### Expected behavior

When `navigation.indexes` is active, I expect MkDocs to create a section index page when a nameless index.md page is placed inside in the `nav` as described in the [Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation#section-index-pages) article, and **NOT** create it otherwise.

<img width="734" alt="2024-09-24_15h28_56" src="https://github.com/user-attachments/assets/a89f2f82-b261-4891-9679-802ab40d8cce">

### Witnessed behavior

If a file path ends with `index.md`, this file is elected as a section index regardless of its name.

<img width="742" alt="2024-09-24_15h30_37" src="https://github.com/user-attachments/assets/3fa04ffd-63ff-4bd1-9a67-e0d190a39ff3">

## Interpretation

This issue is due to the fact that my files are named "index". I understand that I could rename them to something else and they won't be interpreted as section indexes. 

However, I am doing a perpetually growing doc and each topic that is single file will probably need multiple files in the future, so I want to be able to create a folder with a single index file per topic. 

This mechanic might stem from MkDocs directly and might not be related to Material:

> When a directory is requested, by default, most web servers will return an index file (usually named index.html) contained within that directory if one exists. For that reason, the homepage in all of the examples above has been named index.md, which MkDocs will render to index.html when building the site.
>Many repository hosting sites provide special treatment for README files by displaying the contents of the README file when browsing the contents of a directory. Therefore, MkDocs will allow you to name your index pages as README.md instead of index.md. In that way, when users are browsing your source code, the repository host can display the index page of that directory as it is a README file. However, when MkDocs renders your site, the file will be renamed to index.html so that the server will serve it as a proper index file.
>If both an index.md file and a README.md file are found in the same directory, then the index.md file is used and the README.md file is ignored.
[MkDocs, writing your docs page](https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages)

> [!WARNING]  
> When doing tests, please create all pages that are reported in your nav. If not, this behavior is unpredicteable.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[9.5.36-unwanted-index-behavior.zip](https://github.com/user-attachments/files/17115892/9.5.36-unwanted-index-behavior.zip)

### Steps to reproduce

Compare the rendering of the "ships" and the "trains" folder. Ships doesn't follow the [Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation#section-index-pages) and should not have a section index, and "trains" should.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting.

> This mechanic might stem from MkDocs directly and might not be related to Material.

Correct. Unfortunately, with MkDocs' limited capabilities, we have to rely on [`Page.is_index`](https://github.com/mkdocs/mkdocs/blob/bb7e8b62185b11d9f59bb7f50b13c15134f62f8a/mkdocs/structure/pages.py#L125-L127) to check whether a page is an index page or not. MkDocs deems all pages called `index.md` or `README.md` index pages. We're using MkDocs official API for that in the template:

https://github.com/squidfunk/mkdocs-material/blob/fd984136badbc6ca708c1a3528fcfb15364ee7f0/src/templates/partials/nav-item.html#L102-L108

The fact whether a page contained an explicit title set in `mkdocs.yml` is not available to us at that point, as MkDocs will [set the title from 3 other sources](https://github.com/mkdocs/mkdocs/blob/bb7e8b62185b11d9f59bb7f50b13c15134f62f8a/mkdocs/structure/pages.py#L228-L240) if you don't add it in `mkdocs.yml`. There will __definitely__ be a title for every page (last fallback is the filename, which is always available), so the information is lost:

``` md
- value provided on init (passed in from config)
- value of metadata 'title'
- content of the first H1 in Markdown content
- convert filename to title
```

Thus, I recommend raising this to the [maintainers of MkDocs](https://github.com/mkdocs/mkdocs).

> This issue is due to the fact that my files are named "index". I understand that I could rename them to something else and they won't be interpreted as section indexes.

Also correct. We can currently only work with this convention. If something in MkDocs changes, we're happy to adapt. Until then, we consider this as not fixable for now, but since [we're currently back at the drawing board](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/), I'm taking this use case with me. It definitely makes sense to consider.

Closing as upstream issue. CC @alexvoss – we should look for a way to decouple section index configuration entirely.
