### ISSUE TITLE
Use the whole screen in landscape for iOS (extend into safe area)

### ISSUE THREAD

**Issue by RyanLua** [squidfunk/mkdocs-material#7570]
### Context

When making my documentation website a PWA, I noticed that landscape mode on iOS was subpar and wondered if there was a fix for it. I found that it was possible to ignore the device's safe area and extend into the safe zone but you need explicit support for it and Material for MkDocs doesn't quite officially support it.

### Description

Material for MkDocs should be updated to use the entire screen for iOS when it is in landscape mode. All screen elements should extend through safe areas. This means that contents have proper padding, the navbar extends into safe zones, the drawer accounts for the safe zone, etc.

Examples of what I am describing:
- https://webkit.org/blog/7929/designing-websites-for-iphone-x/
- https://dev.to/oncode/display-your-pwa-website-fullscreen-4776

### Related links

- [Content area width](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#content-area-width)
- [Setting up the header](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#setting-up-the-header)

### Use Cases

Use cases for this is the iOS experience for everyone using Material for MkDocs is improved, including non-PWA and PWA uses. Sites will feel more native and finished with proper landscape support.

#### Current behavior
<img width="920" alt="Current" src="https://github.com/user-attachments/assets/a29aefe2-df6d-453e-9bb1-c3b0cf95e43a">

#### Behavior with `<meta name='viewport' content='initial-scale=1, viewport-fit=cover'>`
<img width="920" alt="Meta" src="https://github.com/user-attachments/assets/19ef4b24-ac1b-4971-89e6-9ec33c738db5">

#### Preferred behavior (mock-up)
<img width="920" alt="Preferred" src="https://github.com/user-attachments/assets/1e3bb425-4716-4176-a5b7-2390867b5f36">

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting! I've tested it on my iPhone in Safari, and it looks like this – almost like what you described as your preferred case. Only the header does not stretch appropriately, but it's doesn't look like the first image you posted:

![IMG_2297](https://github.com/user-attachments/assets/7bc5b558-20cd-472b-9caa-593107714743)

Thus, in a non-PWA context, it's working "good enough", IMHO. Honestly, this isn't something we can currently afford to invest time into, as we're working on much bigger changes in the background, as mentioned in [our latest blog post](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/). Additionally, it's rather an edge case – PWA + landscape on iPhone is a rather small group of users that would be impacted, as non-PWA doesn't seem to be impacted.

If you still want this fixed, you can submit a PR and explain how we can test it thoroughly. However, we're currently not considering deep changes on the theme, i.e., visual components due to the fact that our time is bound in bigger topics.

**Comment by squidfunk** [comment]
Oh, and PWA is currently not a priority for us. We will however, definitely reconsider in the future!
