### ISSUE TITLE
Feed filename from rss plugin configuration

### ISSUE THREAD

**Issue by fpuga** [squidfunk/mkdocs-material#7574]
### Description

The filename of the rss feed is harcoded with the default name used in the the mkdocs-rss-plugin. But this plugin allows to change the filename.

I think that this situation should be explained in the documentation, or change the code to get the name from the `feed_filename` setting of the rss plugin.

There is an issue slightly related, where is commented that sometimes is better to use an override.

https://github.com/squidfunk/mkdocs-material/pull/6907

### Related links

- https://guts.github.io/mkdocs-rss-plugin/configuration/#feeds_filenames
- https://github.com/squidfunk/mkdocs-material/blob/70db88f41449f6e801178457944ceb26279dd464/src/templates/base.html#L69
- https://squidfunk.github.io/mkdocs-material/tutorials/blogs/engage/#rss-feeds

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. This setting was added in 1.13.0. Our integration predates this version, so yes, it's a new setting that we're currently not supporting. I'm not sure it's possible for us to support, because MkDocs doesn't easily allow for reading plugin settings, and it seems that the RSS plugin doesn't export any variables ([no `on_page_context` defined](https://github.com/Guts/mkdocs-rss-plugin/blob/a44922c53fc09fae8c278eb67ffc6465c2ff8f2a/mkdocs_rss_plugin/plugin.py)) to the Jinja context, which is why we have no method of obtaining this information.

I've added our regular disclaimer that only the options listed are officially supported.

**Comment by squidfunk** [comment]
As a workaround, the [`site_meta` block](https://github.com/squidfunk/mkdocs-material/blob/e1b817a7065bde198b7ca9893a2f52f52d3b2a30/src/templates/base.html#L30-L87) can be overridden using [block overides](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks) to adjust the names.
