### ISSUE TITLE
When using the "--dirty", the search plugin fails

### ISSUE THREAD

**Issue by Xiaokang2022** [squidfunk/mkdocs-material#7638]
### Context

- Python: `3.13.0`
- OS: `Windows11 23H2`
- mkdocs: `1.6.1`

### Bug description

In exceptional cases, the search plugin will fail. See the reproduced instructions below.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/search/

### Reproduction

[9.5.42-search-fail-with-dirty.zip](https://github.com/user-attachments/files/17501378/9.5.42-search-fail-with-dirty.zip)

### Steps to reproduce

1. Build once, with or without "--dirty"
3. Build again, this time with "--dirty"
4. At this point, the content of the `site/search/search_index.json` is incorrect

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Unfortunately, the whole handling of incremental builds is a problem of MkDocs which [I already reported](https://github.com/mkdocs/mkdocs/issues/3695). I'm not sure whether work has been started on improving the situation.

The problem is that the search plugin needs MkDocs to read all pages, but [the `--dirty` flag instructs it to only read the pages that changed](https://github.com/mkdocs/mkdocs/issues/2220#issuecomment-719994435). Thus, the search plugin does not see the pages to extract the information from, and writes an empty index. The general advise is to never use `--dirty` with `mkdocs build`, as it leads to incorrect navigation. 

In fact, it it not dependent on Material for MkDocs – the situation is the same for the `mkdocs` and `readthedocs` themes. We can't fix it here, as we do not control how MkDocs builds. For this reason, it's an upstream issue.
