### ISSUE TITLE
Separate Navigation Title, from Page/Tags/etc.

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [squidfunk/mkdocs-material#7670]
### Context

The use-case-

A pages title is used in quite a few places.

1. At the top of the page itself
2. On Tags Listings
3. Inside of the Navigation

---------------------------------------------------------------

## Issue 1 - Loss of Context

The problem- If you set a title, based on the context of where a page resides in the navigation, the title of the page is missing context when used on a tags listing page.

Ie.

MySite
---- Installation
--------Database
---- Configuration
--------Database

In this over-simplified example, assuming you have a tags listing, you would just see "Database" twice without any context over then hovering your mouse over the URL.

---------------------------------------------------------------

## Issue 2 - Length

So, lets account for this issue, and give the pages extremely descriptive titles.

MySite
---- My App: Installation
--------My App: Database Installation
---- My App: Configuration
--------My App: Database Configuration

Well, when looking at a tags listing, RSS feed, or page title, its very obvious to know the exact context of what you are looking at.

However, your nav menu is now bloated by additional information, which is already provided by the context of the navigation menu.

---------------------------------------------------------------

## Potential Solution - Adjustable Navigation Title

Allowing the navigation title to be adjusted, seems like the easiest solution to this problem. This, allows you have a short-concise navigation title relying on the context of which navigation entry it is listed under, As well as, it allows the tags listing to contain all of the relevant details needed to know what the context of the page is.

For implementation, I found just overriding the `render_content` macro in `partials/nav-item.html` seems to allow this.

Specifically, changing https://github.com/squidfunk/mkdocs-material/blob/ac3315fd3e25b9449306d0dac6cd535d4d32d9ea/src/templates/partials/nav-item.html#L49-L52 

to 

``` markdown
  <!-- Navigation link title -->
  <span class="md-ellipsis">
    {% if nav_item.is_page and nav_item.meta.nav_title %}
      {{ nav_item.meta.nav_title }}
    {% else %}
      {{ ref.title }}
    {% endif %}    
  </span>
```

Afterwards, if your page contains meta.nav_title, this value is used.

The solution is simple, backwards compatible, etc.

Honestly, I feel like this may be a good fit for the parent repo, especially regarding tags_listings, and having titles which makes sense.

If- you agree with this, I can start drafting a PR.

### Description

All in context.

### Related links

All in context.

### Use Cases

All in context.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. There is `page.title`,`page.meta.title` already + [MkDocs uses the file name and the H1 to choose from](https://github.com/mkdocs/mkdocs/blob/bb7e8b62185b11d9f59bb7f50b13c15134f62f8a/mkdocs/structure/pages.py#L229-L240). If we add another one, say `page.meta.nav_title`, it won't help the already confusing situation. For this reason, this should really be solved in MkDocs. Page titles are a mess, and adding more metadata that is only consumed in the templates is not something we're currently considering. For instance, should `nav_title` be only used in the sidebar, or also in the header? Or the next/prev navigation in the footer – it's also navigation, right?

I recommend discussing this with the maintainers of MkDocs. IMHO, the best idea to detach navigation entirely from the page structure, with the option to configure in which order titles are sourced from the navigation. This is at least how I'd approach the problem, if I'd maintain MkDocs. Maybe the maintainers are open to it? Note that there are some discussions already on this topic, specifically:

- https://github.com/mkdocs/mkdocs/issues/3532
- https://github.com/mkdocs/mkdocs/issues/3357
- https://github.com/mkdocs/mkdocs/issues/3356

Closing as upstream. Material for MkDocs is "only a theme".

**Comment by ogs-oke17219** [comment]
I certainly agree- this one, is... a bit chaotic. I spent an hour or two digging through some of the previous tickets, code, and implementation.

I came here since I found a few tickets upstream, which mentioned this as a custom-theme implementation issue.

But, did want to clarify- this one was specifically put in, to address issues with issues with tags listings:

Examples:

![image](https://github.com/user-attachments/assets/e8852f41-ac2c-4243-af3a-428172c596c5)

The problem was, when viewing a tags listing- just having a title of "Edit", eh, Really wasn't very descriptive or useful. At least- this one allows me to have both descriptive titles used for tags listings, references from other pages- while maintaining a short nav-specific title.

**Comment by XtremeOwnageDotCom** [comment]
I certainly agree- this one, is... a bit chaotic. I spent an hour or two digging through some of the previous tickets, code, and implementation.

I came here since I found a few tickets upstream, which mentioned this as a custom-theme implementation issue.

But, did want to clarify- this one was specifically put in, to address issues with issues with tags listings:

Examples:

![image](https://github.com/user-attachments/assets/da134b66-6ea2-4e07-9d26-193e0e833cd4)

The problem was, when viewing a tags listing- just having a title of "Edit", eh, Really wasn't very descriptive or useful. At least- this one allows me to have both descriptive titles used for tags listings, references from other pages- while maintaining a short nav-specific title.

**Comment by squidfunk** [comment]
I do not believe it is a theme issue, since themes can only work with what they're given, and MkDocs only gives us the resolved title after going through the process I linked in my last comment. There is absolutely no way to explicitly access the title as defined in the navigation in `mkdocs.yml`.

So while we can't properly and cleanly solve this with what MkDocs is giving us right now, please know that we're heavily working in the background on [big changes that are coming to Material for MkDocs](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/), and that navigation is one topic that will be addressed a well. We already have a solid concept and want to provide more flexibility than what MkDocs currently offers.

As a way out – you might implement your patch as a hook + template override, until we can provide a better solution. Please understand that we're not considering adding more hacks to our software to account for shortcomings that need to be fixed in MkDocs.

**Comment by XtremeOwnageDotCom** [comment]
Understandable, Thanks for the context, and replies!  Love the project!
