### ISSUE TITLE
I would like to add a translation for Tibetan (no flag) However, there is no Tibetan flag currently available

### ISSUE THREAD

**Issue by daniel-wojahn** [squidfunk/mkdocs-material#7681]
### Description

I would like to add a translation for Tibetan. However, there is no Tibetan flag currently available. 

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

We want to write a documentation for our Handwriting Text Recognition workflow and want to translate this into Tibetan as well.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is nothing we can fix, unfortunately, as flags are sourced from FontAwesome. You can provide the Tibetan translations and just leave the flag empty.

**Comment by squidfunk** [comment]
Okay, so our general policy here is to find the "next best fitting" flag. For regions like Catalonia or the Basque country, we fall back to the Spanish flag, so we would need to use the Chinese flag here. However, we understand that this is a hugely controversial topic, which is why I recommend that we just fall back to the the mountan snow emoji. :mountain_snow: here. This should not get anybody upset, and does not require us to write extra code to add the translations.
