### ISSUE TITLE
Landing page/Hero/fullscreen background

### ISSUE THREAD

**Issue by daniel-wojahn** [squidfunk/mkdocs-material#7686]
### Description

I am really amazed by MKdocs Material's landing page with the space-age full screen background and the two buttons. I am still trying to wrap my head around how I could also achieve that. 

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
-

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment]
Not really a documentation issue because we do not promise that you can build everything we build. What you are asking [has been asked a few times in the discussions](https://github.com/squidfunk/mkdocs-material/discussions?discussions_q=+parallax+). It is absolutely possible to build the same thing but we are talking a customization here, not something we can provide as an option. Building it requires knowledge of HTML, CSS and JS (at the moment, see below), topics we won't try to cover because they are not specific to Material for MkDocs.

The landing page is a custom template. I can tell you that achieving similar effects will be a lot of effort but may become easier in the future if browsers start supporting a bunch of CSS features. Search for "parallax effect" on Youtube and you will find tons of tutorials. Most depend on JavaScript at the moment.

**Comment by squidfunk** [comment]
As an outlook: we're definitely listening to these kind of requests, and looking into making creation of nice landing pages simpler, as this is something that has been asked many times. As mentioned in [our latest blog post](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/), we're currently working heavily in the background on big changes. A lot of things will be much, much easier soon.

**Comment by alexvoss** [comment]
In that case, all you might need is to [override the `hero` block](https://squidfunk.github.io/mkdocs-material/customization#overriding-blocks) and to [add buttons](https://squidfunk.github.io/mkdocs-material/reference/buttons).
