### ISSUE TITLE
Locally cached external content fails in strict mode

### ISSUE THREAD

**Issue by pana-exfo** [squidfunk/mkdocs-material#7727]
### Context

Build server is offline and external content is cached locally

### Bug description

**Current behavior** 
Privacy plugin is using files from local cache and gives warnings.
When running in strict mode, these warnings cause build to fail.

**Expected behavior**
Privacy plugin is using files from local cache and prints warning if files are missing from local cache.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [config.cache](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.cache)
- [config.cache_dir](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.cache_dir)

### Reproduction

[9.5.44-cached-privacy-fail-in-strict-mode.zip](https://github.com/user-attachments/files/17832012/9.5.44-cached-privacy-fail-in-strict-mode.zip)

### Steps to reproduce

1. Comment assets_fetch (assets_fetch: false) in config 
2. Run build with `mkdocs build` to download content to cache
3. Run build with `mkdocs build --strict`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is intended behavior. Setting [`assets_fetch`](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.assets_fetch) to `false` sets the privacy plugin into "reporting" mode, which ensures that you are not using external assets. The use case is that you self-host by yourself, but want a safety net so that you do not use external assets accidentally. This is also why this has to be a warning:

> Use this setting to control whether the plugin should downloads or only report external assets when they're encountered. If you already self-host all external assets, this setting can be used as a safety net to detect links to external assets placed by the author in pages.

However, you can easily achieve what you want by setting [`log_level`](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.log_level) to `error`:

``` yaml
plugins:
  - privacy:
      cache_dir: dir/
      assets_fetch: false
      log_level: error
```

Result:

```
$ mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/squidfunk/Desktop/Reproductions/9.5.44-cached-privacy-fail-in-strict-mode/site
INFO    -  Documentation built in 0.15 seconds
```

It's always a good idea to check the plugin settings, as our plugins have plenty.
