### ISSUE TITLE
Bring back `redirect`

### ISSUE THREAD

**Issue by ZhiyuanChen** [squidfunk/mkdocs-material#7790]
### Context

The Redirect feature allows a page to be redirected to another page. 
This feature is deprecated in MkDocs 5.5, and removed in MkDocs 6.0, in favour of `mkdocs-redirect` package. 

### Description

The `mkdocs-redirect` package has a long standing problem of compatibility with other plugins, like `i18n` ([suffix](https://github.com/mkdocs/mkdocs-redirects/issues/33) and [folder](https://github.com/mkdocs/mkdocs-redirects/issues/63)), [`use_directory_urls`](https://github.com/mkdocs/mkdocs-redirects/issues/24), etc.

This makes it practically useless. 

It is therefore important to keep the `redirect` option until it works with the rest of the `MkDocs` environment. 

### Related links

- https://github.com/mkdocs/mkdocs-redirects/issues/24
- https://github.com/mkdocs/mkdocs-redirects/issues/33
- https://github.com/mkdocs/mkdocs-redirects/issues/63

### Use Cases

Redirect can be useful when pages are moved, and when using README as index page where they have different locations in repo and on web. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure what you exactly mean about the redirect feature, but you're probably referring to the `redirect` front matter property that once existed. You can use the [`redirect.html` template](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/redirect.html), which is undocumented because it is not part of our public API, but it's not expected to be removed anytime soon. In any Markdown file, just set:

``` md
---
template: redirect.html
location: https://example.com
---

```

The bugs should be fixed in mkdocs-redirects, which is the canonical plugin to provide redirects, since those are a theme-agnostic feature. Thus, we consider this as an upstream issue, but you can use the workaround in the meantime.
