### ISSUE TITLE
Gitignore should contain /material/

### ISSUE THREAD

**Issue by taocnrut** [squidfunk/mkdocs-material#840]
## Description
I think that .gitignore sould contain /material/ probably in # Files generated by build section

### Expected behavior

After checking out theme and building it (even without any changes), git should not report that anything changed. The directory material is removed and then recreated every time npm run build is executed.

### Actual behavior

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    material/assets/javascripts/application.e72fd936.js
	modified:   material/base.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	material/assets/javascripts/application.6cf77876.js

no changes added to commit (use "git add" and/or "git commit -a")
```

### Steps to reproduce the bug

1. git clone https://github.com/squidfunk/mkdocs-material
2. cd mkdocs-material
3. pip install -r requirements.txt
4. npm install
5. npm run build
6. git status

### Package versions

* Python: `Python 3.6.6`
* MkDocs: `mkdocs, version 1.0 (Python 3.6)`
* Material: `Version: 3.0.1`

### Project configuration
NA

### System information

* OS: Fedora 28
* git version 2.17.1

**Comment by squidfunk** [comment]
Well, this is something that I thought about a lot. In general I totally agree, the distribution files should not be part of version control. However, my initial aim was to make the theme installable via `git` so you could use the latest `master` without going through all the build steps yourself. For this reason I decided to include the distribution files and yes, it sucks at times because sometimes there are conflicts on merges and other problems, but I think the convenience as an upside in this particular case outweighs the downsides.

**Comment by taocnrut** [comment]
I'm OK with that if that was what was intended, just wanted to help in case you missed it... I'm also OK with downloading tar.gz from releases page :)

**Comment by squidfunk** [comment]
Downloading tars would imply releases and they are currently automatically created and pushed to PyPI after the build was successful on a release branch, so we would need to restructure the workflow for that. I think we'll leave it as it is :-) Your point, however, is valid.
