### ISSUE TITLE
Getting Github star / fork count is somewhat expensive

### ISSUE THREAD

**Issue by jrudolph** [squidfunk/mkdocs-material#843]
## Description

Great work on the design!

Each time a page is opened, the star / fork count is loaded another time. Also it seems it tries to find the repository by enumerating all repositories of the user which might even need several round-trips to github to get this simple info.

No Javascript developer here, so please bear with me ;)

I'd suggest to:

 * cache Github results locally for some time
 * Fetch repository info directly (there's a comment somewhere that the enumeration is done to prevent 404, but why would 404s be a problem?)

**Comment by squidfunk** [comment]
Actually, GitHub stars are cached in a Cookie (could use Local Storage, yeah, but it works for now). The theme loads all projects from a user/organization because some people like to link their organization. This was implemented in #337.

**Comment by jrudolph** [comment]
Ah, I guess then the problem was that I tested on localhost.

I think with caching usually working, no reason to optimize further.

Sorry for the hiccup.

**Comment by squidfunk** [comment]
Skimming through the code, I remember why we did it: some users use Material to host documentation for their private repositories. They enter the URL to their repository in `mkdocs.yml` in the `repo_url` attribute which Material reads and uses for querying the GitHub API. Private repos are not exposed, so the result when querying GitHub is a 404 error. Actually it's not possible to get private information from the GitHub API without authenticating (thankfully), so to omit the 404 error in the console we just query for all repos and see if we can find it. If not, Material will just show the name of the repo without any counts. This also introduced a new feature - just linking the organization will show how many repositories this organization has.

Why would somebody want to use this feature with a private repo? Because the `repo_url` in conjunction with `edit_uri` enables the inclusion of EDIT links on every page directly linking to the private repository.

The issue in which this was reported and discussed is #329.

**Comment by jrudolph** [comment]
Thanks for the information! :+1:

**Comment by yashu1wwww** [comment]
github tools

https://yashawanthtechprojects.on.drv.tw/GitHub/uploaddatefinder.html
