### ISSUE TITLE
How to search a single language translation

### ISSUE THREAD

**Issue by maurelian** [squidfunk/mkdocs-material#867]
## Description

Our documentation site recently had a full translation of Korean submitted. This is obviously wonderful. 

Unfortunately, the search functionality mixes the two languages, which reduces the usability for readers in either language. Adding more languages in this way would presumably make it worse.

![image](https://user-images.githubusercontent.com/23033765/44856948-b2a56880-ac3c-11e8-87f8-decf9886f771.png)

### Expected behavior

I would prefer if there was a site wide toggle for the active language. Does such an option exist?

### Package versions

python==3.6
mkdocs==0.17.2
mkdocs-material==2.2.5

### Project configuration

https://github.com/ConsenSys/smart-contract-best-practices/blob/master/mkdocs.yml

Thanks very much for this excellent project, and for your help in advance!

**Comment by squidfunk** [comment]
MkDocs doesn't support language toggling/branching, so Material cannot add this functionality either. To solve this, you would need to build two separate versions of your docs, one for each language configuring the correct search language in `mkdocs.yml`. By customizing the theme you could link to the other language inside the header or where you want, effectively switching between the two separate builds.

**Comment by maurelian** [comment]
Great explanation, thank you!

**Comment by rllola** [comment]
@squidfunk I have been following your recommendation and done it for ZeroNet documentation. The most tricky part was the lunr search_index.json file which was containing the text. Also for convenient I wanted to have the 2 languages folders in the docs (so we don't need to modify twice and forget).

Here what I have which I believe might be useful for people willing to do it in the future : 
https://github.com/rllola/Documentation/tree/french

It has : 
* The icon with dropdown button
* The nginx conf file which does the magic to get the proper `search_index.json`
* A python script to generate everything
* Dockerfile because why not
* Insctructions in README

Your feedback would be appreciated.

**Comment by squidfunk** [comment]
@rllola Thanks for sharing your setup! It will be beneficial for anyone wanting to achieve this until MkDocs adds support for multi-language builds (if ever).

**Comment by rllola** [comment]
@maurelian Sure. https://zeronet.io/docs-dev/en/

I am not done with the french translation tho. I have been focusing on the multi-language support side of it.

Here the PR with a little bit more information : https://github.com/HelloZeroNet/Documentation/pull/117

Let me know if you have questions or need help.

**Comment by squidfunk** [comment]
Hmm, thinking about it, maybe we could add something like this to Material by default. If somebody can come up with a good spec on how to integrate it in a way that is easily workable, I'm happy to help integrating it or pull it of my self. Here are some problems to tackle:

- How do we link different-language translations (URLs are different)?
- Do all translations/versions require the same structure?
- Would it be practical to do it with the metadata extension?
- How would it look on desktop? tablet? mobile?

**Comment by suricactus** [comment]
Would be interesting if someone found a better solution than building a seperate site and search index for each language and share it here.

**Comment by squidfunk** [comment]
There's the [mkdocs-static-i18n plugin](https://github.com/ultrabug/mkdocs-static-i18n) which allows for building a single site and index, as I understand. I'm not a user of it, since this comes with some other caveats, which is why we're following the approach to build multiple sites alongside each other and will add better support for this in the future with the new [projects plugin](https://squidfunk.github.io/mkdocs-material/plugins/projects/), but it might be something to consider.

**Comment by alexvoss** [comment]
I think a separate search index is a good thing because the size of a single search index would blow up with each translation added. 

The projects plugin feels like the right path to me. I have recently started helping @squidfunk develop more [examples](https://github.com/mkdocs-material/examples) for Material for MkDocs functionality, which means I am a heavy user of this plugin. One thing I like about the approach taken with it is that it will facilitate more use cases. (I am looking to develop an example that produces a second, stripped-down version of a site -e.g., for including training material in Open edX).
