### ISSUE TITLE
Expand admonitions in print css?

### ISSUE THREAD

**Issue by akhmerov** [squidfunk/mkdocs-material#869]
Right now (mkdocs v1.0.3 and mkdocs-material v3.0.0) collapsed admonitions stay collapsed in print preview:

![image](https://user-images.githubusercontent.com/2069677/44959013-90377780-aee8-11e8-9405-74861e45b0d2.png)

While this may be the desired behavior, I wanted to double-check whether this is the intention (I think expanding all of these would make more sense).

**Comment by squidfunk** [comment]
That's indeed a bug. Will fix it in the next release.

**Comment by squidfunk** [comment]
This is actually trickier than expected as it's not solvable via CSS. My research leads me to believe that we need to fix it in JavaScript (see [this StackOverflow question](https://stackoverflow.com/questions/19646684/force-open-the-details-summary-tag-for-print-in-chrome)) for which I need some more time. Again, happy to merge a PR.

**Comment by squidfunk** [comment]
Added a hack in 71fc5d1

**Comment by squidfunk** [comment]
Released as part of 4.0.1

**Comment by bs-jena** [comment]
Am I doing something wrong, or doesn't this work any longer? It used to, and we all were happy, but now it doesn't. (MkDocs 1.0.4 + MkDocs Material 4.2.0)

**Comment by squidfunk** [comment]
Still works on my machine. Just tested in with Chrome, Firefox and Safari in the official docs. If you're having trouble, please always state your browser, operating system etc.

**Comment by bs-jena** [comment]
I played around on different OSs (Mojave + Bionic), with different Python, MkDocs/Material versions ... all with the same effect. So I tested different doc sources (extension combinations, theme overrides, etc.) to narrow that down.
Well: Obviously, there is a dependency (which I don't understand) between the search output div in partials/search.html and this functionality to open the details on print. I replaced the built-in search with a Google CSE and removed that bit of code, now I put that back in (which does not do anything, otherwise), and it works. Weird.

**Comment by squidfunk** [comment]
@bs-jena could you check if at any stage of your experiments there are errors in the browser console?

**Comment by bs-jena** [comment]
Removing `<div class="md-search-result__meta">{{- lang.t("search.result.placeholder") -}}</div>` from search.html prevents the details from being auto-opened and produces this error:
```
Uncaught TypeError: Cannot read property 'textContent' of undefined
    at new e (application.b260a35d.js:1)
    at Object.initialize (application.b260a35d.js:1)
    at (index):247
e @ application.b260a35d.js:1
initialize @ application.b260a35d.js:1
(anonymous) @ (index):247
```

**Comment by squidfunk** [comment]
I see. Overriding the template, I didn't account for all possibilities of missing elements due to theme customization. For this reason, the script execution is halted and the logic which registers the auto-open handler is never executed. One could restructure the flow in `application.js` and/or make the whole search logic more resilient. However, an easier way for you is to disable search entirely by removing it from the plugins array in your `mkdocs.yml`:

``` yaml
plugins:
  # - search
```

**Comment by bs-jena** [comment]
Sorry, I am not a developer: "restructure the flow in application.js" would mean to move the `Before-print hook` and `Open details before printing` sections in front of the entire search section - and that would do the trick? I suppose I can't do this in my locally installed instance ...
Unfortunately, disabling the search is no option, because we do use the search box in the page header, we just put this CSE code snippet there.
Anyway, thanks for your research!
