### ISSUE TITLE
How to use custom syntax highlighting?

### ISSUE THREAD

**Issue by wongjiahau** [squidfunk/mkdocs-material#873]
I had read that `Pygment` allows you to [define custom syntax highlighting](http://pygments.org/docs/lexerdevelopment/), but how should I integrate it with mkdocs-material?

**Comment by facelessuser** [comment]
You just create a python module (properly providing the correct entry points), and then include as a python dependency in your project.  This isn't really a mkdocs-material question as much as it is a Pygments question though.

**Comment by facelessuser** [comment]
It may help to have a simple example.  I use a custom language in my pymdown-extensions documents for [CriticMarkup](https://facelessuser.github.io/pymdown-extensions/extensions/critic/#usage).  It highlights CriticMarkup syntax so it stands out in plain text.  I think I use the `critic-markup` language name.

I have my own custom lexers here: https://github.com/facelessuser/pymdown-lexers.

I had it in my requirements file here: https://github.com/facelessuser/pymdown-extensions/blob/master/requirements/docs.txt.  I just reference the repo directly instead of adding it officially to PyPI.

Anyways, when the documents are deployed via Travis and Python's tox, these requirements get installed, and then when mkdocs deploys, it has applied the custom language.
